export type SectionKind = "default" | "evidence" | "recommendation" | "risk" | "example" | "decision";
export type VisualKind = "flow" | "cards" | "timeline" | "maturity-heatmap" | "waste-friction" | "value-stream";
export type EvidenceClassification = "E1" | "E2" | "E3" | "H1";
export type SourceMark = "E" | "I" | "R" | "V";
export type ReviewConfidence = "high" | "medium" | "low" | "unreviewed";
export type ValidationStatus = "confirmed" | "pending" | "rejected";
export type SourceReference = { title:string; locator:string; note?:string };
export type EvidenceReference = {
  id:string;
  sourceMark:SourceMark|null;
  classification:EvidenceClassification|null;
  statement:string;
  sourceLocator:string;
  sourceArea:string;
  supports:string[];
  confidence:ReviewConfidence;
  validationStatus:ValidationStatus;
};
export type EditorialNotice = {
  title:string;
  status:"PENDING VALIDATION"|"PENDING EVIDENCE REVIEW"|"CLIENT VALIDATION REQUIRED";
  detail:string;
};
export type ImpactSemantics = "OBSERVED IMPACT" | "INFERRED IMPACT" | "POTENTIAL RISK" | "UNREVIEWED";
export type ClientValidationId = "CL-01"|"CL-02"|"CL-03"|"CL-04"|"CL-05"|"CL-06"|"CL-07"|"CL-08"|"CL-09"|"CL-10"|"CL-11"|"CL-12"|"CL-13"|"CL-14";
export type ClientValidation = { id:ClientValidationId; subject:string; status:"CLIENT VALIDATION REQUIRED" };
export type CanonicalLayer = "STRATEGY / OUTCOMES"|"DISCOVER"|"DECIDE"|"DELIVER"|"ADOPT"|"LEARN"|"GOVERNANCE"|"ROLES"|"METRICS"|"TOOLING / JIRA"|"EVIDENCE"|"CONTINUOUS IMPROVEMENT"|"UNMAPPED";
export type HowDimension = "WHAT"|"WHY"|"HOW"|"WHO"|"WHEN"|"INPUT"|"OUTPUT"|"ARTIFACT"|"DECISION"|"METRIC"|"TOOL"|"EXAMPLE";
export type CompletenessStatus = "SOURCE COMPLETE"|"SOURCE PARTIAL"|"SOURCE MISSING";
export type OperatingConcept = {
  id:string;
  title:string;
  canonicalLayers:CanonicalLayer[];
  sourceChapters:string[];
  sourceLocators:SourceReference[];
  contentClass:ContentClass;
  completeness:Partial<Record<HowDimension,CompletenessStatus>>;
  gapIds:string[];
};
export type SourceSubStage = { title:string; locator:string; relationship:"SOURCE SUB-STAGE"|"SOURCE TERMINOLOGY"|"CONTROLLED ALIAS" };
export type OperatingStage = {
  canonicalStage:Extract<CanonicalLayer,"DISCOVER"|"DECIDE"|"DELIVER"|"ADOPT"|"LEARN">;
  sourceSubStages:SourceSubStage[];
  purpose?:string;
  triggers?:string[];
  inputs?:string[];
  steps?:string[];
  outputs?:string[];
  source:SourceReference;
};
export type ResponsibilitySemantics = "ACCOUNTABLE"|"RESPONSIBLE"|"CONTRIBUTOR"|"CONSULTED"|"INFORMED"|"FACILITATOR"|"DECISION OWNER";
export type RoleMappingStatus = "SOURCE ROLE"|"ROLE MAPPING PENDING";
export type OperatingRole = {
  id:string;
  sourceRole:string;
  purpose?:string;
  responsibilities?:string[];
  accountabilities?:string[];
  decisionRights?:string[];
  inputs?:string[];
  outputs?:string[];
  interactions?:string[];
  cadences?:string[];
  artifacts?:string[];
  metrics?:string[];
  canonicalStages?:Extract<CanonicalLayer,"DISCOVER"|"DECIDE"|"DELIVER"|"ADOPT"|"LEARN">[];
  semantics?:ResponsibilitySemantics[];
  mappingStatus:RoleMappingStatus;
  completeness:Partial<Record<HowDimension,CompletenessStatus>>;
  sourceLocators:SourceReference[];
  clientValidationIds?:ClientValidationId[];
};
export type DecisionRight = {
  id:string;
  decision:string;
  stage?:Extract<CanonicalLayer,"DISCOVER"|"DECIDE"|"DELIVER"|"ADOPT"|"LEARN">;
  trigger?:string;
  inputs?:string[];
  decisionOwner?:string;
  participants?:string[];
  decisionCriteria?:string[];
  output?:string;
  escalation?:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type ArtifactTaxonomy = "STRATEGY"|"DISCOVERY"|"DECISION"|"DELIVERY"|"ADOPTION"|"LEARNING"|"GOVERNANCE"|"EVIDENCE"|"UNMAPPED / PENDING REVIEW";
export type OperatingArtifact = {
  id:string;
  name:string;
  purpose:string;
  taxonomy:ArtifactTaxonomy[];
  canonicalStages?:Extract<CanonicalLayer,"DISCOVER"|"DECIDE"|"DELIVER"|"ADOPT"|"LEARN">[];
  createdWhen?:string;
  owner?:string;
  inputs?:string[];
  requiredFields?:string[];
  lifecycle?:string[];
  lifecycleCompleteness:CompletenessStatus;
  decisionEnabled?:string;
  outputs?:string[];
  relatedMetrics?:string[];
  relatedRoles?:string[];
  toolRelationship?:string;
  contentClass:ContentClass;
  completeness:Partial<Record<HowDimension,CompletenessStatus>>;
  sourceLocators:SourceReference[];
  clientValidationIds?:ClientValidationId[];
};
export type ArtifactRelationship = {
  from:string;
  to:string;
  relationship:string;
  canonicalTransition?:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type DiscoveryCompletenessDimension = HowDimension|"EVIDENCE QUALITY"|"EXIT / DECISION CRITERIA"|"FEEDBACK LOOP";
export type DiscoveryConceptKind = "TRIGGER"|"SIGNAL"|"PROBLEM / OPPORTUNITY"|"FRAMING"|"ASSUMPTION"|"HYPOTHESIS"|"RESEARCH"|"EXPERIMENT"|"EVIDENCE"|"SYNTHESIS"|"DECISION"|"LEARNING";
export type DiscoveryConcept = {
  id:string;
  kind:DiscoveryConceptKind;
  title:string;
  purpose:string;
  trigger?:string;
  inputs?:string[];
  activities?:string[];
  outputs?:string[];
  roles?:string[];
  artifacts?:string[];
  evidenceExpected?:string[];
  decisionEnabled?:string;
  metric?:string;
  cadence?:string;
  toolRelationship?:string;
  sourceLocators:SourceReference[];
  contentClass:ContentClass;
  completeness:Partial<Record<DiscoveryCompletenessDimension,CompletenessStatus>>;
};
export type DiscoveryFlowConnection = {
  from:string;
  to:string;
  status:"SUPPORTED CONNECTION"|"PARTIAL CONNECTION"|"MISSING CONNECTION";
  rationale:string;
  source?:SourceReference;
};
export type DiscoveryEvidenceTerm = {
  term:"ASSUMPTION"|"HYPOTHESIS"|"EVIDENCE"|"INSIGHT"|"DECISION";
  definition?:string;
  qualityModel?:string[];
  sourceStatus:CompletenessStatus;
  source?:SourceReference;
};
export type DiscoveryGate = {
  id:string;
  decision:string;
  trigger:string;
  inputs:string[];
  evidenceRequired:string[];
  participants?:string[];
  decisionOwner?:string;
  possibleOutputs:string[];
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type DiscoveryTechnique = {
  id:string;
  name:string;
  purpose:string;
  whenUseful?:string;
  input?:string[];
  output?:string[];
  evidenceGenerated?:string;
  example?:string;
  source:SourceReference;
};
export type DiscoveryCadence = {
  name:string;
  cadenceType:"CONTINUOUS"|"EVENT-DRIVEN"|"SCHEDULED"|"GATE";
  purpose:string;
  participants?:string[];
  source:SourceReference;
};
export type ArtifactUse = {
  artifactId:string;
  artifactName:string;
  relationship:"CREATES"|"UPDATES"|"READS"|"SOURCE TERMINOLOGY CONFLICT"|"INPUT TO DECISION"|"UPDATED BY DECISION"|"OUTPUT OF DECISION"|"RECORD OF DECISION";
  usage:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type AntiPatternAssessment = {
  antiPattern:string;
  status:"NOT PRESENT"|"SOURCE RISK"|"OPERATING MODEL RISK";
  rationale:string;
  source:SourceReference;
};
export type DecideCompletenessDimension = HowDimension|"DECISION CRITERIA"|"TRADE-OFF"|"CAPACITY CONSTRAINT"|"REVISIT CONDITION"|"DECISION RECORD";
export type DecisionSemanticTerm = "ASSESSMENT"|"PRIORITIZATION"|"RANKING"|"SEQUENCING"|"DECISION"|"COMMITMENT"|"CAPACITY ALLOCATION"|"FUNDING / INVESTMENT"|"BACKLOG ORDERING";
export type DecisionSemantic = {
  term:DecisionSemanticTerm;
  definition?:string;
  sourceStatus:CompletenessStatus;
  source?:SourceReference;
};
export type DecideConceptKind = "DECISION TRIGGER"|"DECISION OBJECT"|"EVIDENCE PACKAGE"|"DECISION CRITERIA"|"EVALUATION"|"PRIORITIZATION"|"TRADE-OFF"|"CAPACITY CONSTRAINT"|"DECISION"|"COMMITMENT"|"REVISIT"|"STOP / DEFER";
export type DecideConcept = {
  id:string;
  kind:DecideConceptKind;
  title:string;
  what:string;
  why:string;
  trigger?:string;
  inputs?:string[];
  criteria?:string[];
  method?:string;
  participants?:string[];
  decisionOwner?:string;
  outputs?:string[];
  artifacts?:string[];
  metric?:string;
  cadence?:string;
  toolRelationship?:string;
  example?:string;
  sourceLocators:SourceReference[];
  contentClass:ContentClass;
  completeness:Partial<Record<DecideCompletenessDimension,CompletenessStatus>>;
};
export type DecisionObject = {
  sourceTerm:string;
  objectType:string;
  decisionApplied:string[];
  artifactRelationship:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type PrioritizationMethod = {
  name:string;
  methodClass:"CURRENT PRACTICE"|"SOURCE RECOMMENDATION"|"H1 / PROPOSED"|"EXAMPLE"|"PENDING VALIDATION";
  criteria?:string[];
  scale?:string[];
  formula?:string;
  weights?:string[];
  thresholds?:string[];
  purpose:string;
  caveat?:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type PriorityCommitmentAssessment = {
  priorityDefinition:string;
  executionApprovalDefinition:string;
  capacityCommitmentDefinition:string;
  distinctionStatus:"SUPPORTED"|"PARTIAL"|"OPERATING MODEL GAP";
  source:SourceReference;
};
export type DiscoveryDecideConnection = {
  element:string;
  status:"SUPPORTED"|"PARTIAL"|"MISSING";
  rationale:string;
  source:SourceReference;
};
export type DecisionRecordModel = {
  artifactName:string;
  fields:Partial<Record<"DECISION"|"DATE / CADENCE"|"INPUTS"|"EVIDENCE"|"PARTICIPANTS"|"DECISION OWNER"|"RATIONALE"|"TRADE-OFF"|"RESULT"|"REVISIT CONDITION",CompletenessStatus>>;
  sourceFields:string[];
  source:SourceReference;
};
export type DecisionCadence = {
  name:string;
  cadenceType:"DECISION CADENCE"|"MEETING CADENCE"|"EVENT-DRIVEN";
  purpose:string;
  decisions:string[];
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type DecisionMetric = {
  name:string;
  metricClass:"VALUE"|"CUSTOMER"|"FLOW"|"RISK"|"EFFORT"|"FINANCIAL"|"LEARNING";
  definition:string;
  baseline?:string;
  target?:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type DeliveryCompletenessDimension = HowDimension|"FLOW"|"QUALITY"|"RELEASE CRITERIA"|"RECOVERY"|"POST-RELEASE OBSERVATION";
export type DeliverySemanticTerm = "DONE"|"READY FOR RELEASE"|"RELEASED"|"IN PRODUCTION"|"AVAILABLE"|"ADOPTED"|"VALUE VALIDATED";
export type DeliverySemantic = {
  term:DeliverySemanticTerm;
  definition?:string;
  sourceStatus:CompletenessStatus;
  source?:SourceReference;
};
export type DeliveryConceptKind = "COMMITMENT"|"DELIVERY OBJECT"|"WORK DECOMPOSITION"|"VALUABLE SLICE"|"WORK IN PROGRESS"|"FLOW"|"DEPENDENCY"|"BLOCKER"|"QUALITY"|"VALIDATION"|"RELEASE READINESS"|"RELEASE"|"PRODUCTION"|"TECHNICAL FEEDBACK"|"POST-RELEASE OBSERVATION";
export type DeliveryConcept = {
  id:string;
  kind:DeliveryConceptKind;
  title:string;
  what:string;
  why:string;
  trigger?:string;
  inputs?:string[];
  activities?:string[];
  outputs?:string[];
  participants?:string[];
  artifacts?:string[];
  decision?:string;
  metric?:string;
  cadence?:string;
  toolRelationship?:string;
  example?:string;
  sourceLocators:SourceReference[];
  contentClass:ContentClass;
  completeness:Partial<Record<DeliveryCompletenessDimension,CompletenessStatus>>;
};
export type DeliveryConnection = {
  element:string;
  status:"SUPPORTED"|"PARTIAL"|"MISSING";
  rationale:string;
  source:SourceReference;
};
export type DeliveryObject = {
  sourceTerm:string;
  purpose:string;
  parentChildRelationship?:string;
  owner?:string;
  lifecycle?:string[];
  decisionRelationship?:string;
  releaseRelationship?:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type ValuableSliceAssessment = {
  sourceStatus:CompletenessStatus;
  optimizes:Array<"VALUE"|"LEARNING"|"RISK"|"FLOW">;
  definition:string;
  risks:Array<{risk:string;status:"NOT PRESENT"|"SOURCE RISK"|"OPERATING MODEL RISK";rationale:string}>;
  source:SourceReference;
};
export type DeliveryMetric = {
  name:string;
  metricClass:"FLOW"|"DORA"|"QUALITY"|"RELIABILITY"|"RELEASE"|"VALUE";
  definition:string;
  formula?:string;
  owner?:string;
  decisionEnabled?:string;
  baseline:string;
  target:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type ReleaseDecision = {
  decision:string;
  trigger:string;
  inputs:string[];
  decisionOwner?:string;
  participants:string[];
  criteria:string[];
  outputs:string[];
  evidence:string[];
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type DeliveryCadence = {
  name:string;
  cadenceType:"OPERATING CADENCE"|"DECISION CADENCE"|"MEETING CADENCE"|"EVENT-DRIVEN ACTIVITY";
  purpose:string;
  frequency?:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type DeliveryToolReference = {
  tool:string;
  classification:"CURRENT STATE"|"RECOMMENDATION"|"H1 / TO VALIDATE";
  relationship:string;
  source:SourceReference;
  validationStatus:ValidationStatus;
};
export type ContentTableKind = "simple" | "comparison" | "scorecard" | "maturity" | "evidence-map";
export type ContentTable = {
  id:string;
  caption:string;
  kind:ContentTableKind;
  headers:string[];
  rows:string[][];
  source:SourceReference;
  assessmentLabel?:string;
  validationStatus?:ValidationStatus;
};
export type ContentBlock =
  | { type:"paragraph"; text:string; source:SourceReference }
  | { type:"list"; items:string[]; source:SourceReference }
  | { type:"table"; table:ContentTable };
export type ContentClass = "source-fact" | "assessment-interpretation" | "recommendation" | "hypothesis" | "mixed";
export type Section = {
  id:string;
  title:string;
  body?:string;
  bullets?:string[];
  kind?:SectionKind;
  visual?:VisualKind;
  blocks?:ContentBlock[];
  evidence?:EvidenceReference[];
  sources?:SourceReference[];
  contentClass?:ContentClass;
  impactSemantics?:ImpactSemantics[];
  impactValidationStatus?:ValidationStatus;
  clientValidations?:ClientValidation[];
};
export type ExecutiveLayer = {
  keyFindings:string[];
  implication:string;
  evidenceConfidence:ReviewConfidence;
  evidenceStatus:ValidationStatus;
  primaryVisual?:VisualKind;
  sources:SourceReference[];
};
export type Chapter = {
  slug:string;
  group:string;
  title:string;
  sourceTitle?:string;
  eyebrow:string;
  summary:string;
  takeaway:string;
  executive?:ExecutiveLayer;
  sections:Section[];
  related:string[];
  source?:SourceReference;
  editorialNotices?:EditorialNotice[];
  clientValidations?:ClientValidation[];
  operatingConcepts?:OperatingConcept[];
  operatingStages?:OperatingStage[];
  sourceOperatingSequence?:SourceSubStage[];
  operatingRoles?:OperatingRole[];
  decisionRights?:DecisionRight[];
  operatingArtifacts?:OperatingArtifact[];
  artifactRelationships?:ArtifactRelationship[];
  discoveryConcepts?:DiscoveryConcept[];
  discoveryFlowConnections?:DiscoveryFlowConnection[];
  discoveryEvidenceModel?:DiscoveryEvidenceTerm[];
  discoveryGates?:DiscoveryGate[];
  discoveryTechniques?:DiscoveryTechnique[];
  discoveryCadences?:DiscoveryCadence[];
  artifactUses?:ArtifactUse[];
  antiPatternAssessments?:AntiPatternAssessment[];
  decisionSemantics?:DecisionSemantic[];
  decideConcepts?:DecideConcept[];
  decisionObjects?:DecisionObject[];
  prioritizationMethods?:PrioritizationMethod[];
  priorityCommitment?:PriorityCommitmentAssessment;
  discoveryDecideConnections?:DiscoveryDecideConnection[];
  decisionRecord?:DecisionRecordModel;
  decisionCadences?:DecisionCadence[];
  decisionMetrics?:DecisionMetric[];
  deliverySemantics?:DeliverySemantic[];
  deliveryConcepts?:DeliveryConcept[];
  commitmentDeliveryConnections?:DeliveryConnection[];
  deliveryObjects?:DeliveryObject[];
  valuableSliceAssessment?:ValuableSliceAssessment;
  releaseDecisions?:ReleaseDecision[];
  deliveryCadences?:DeliveryCadence[];
  deliveryMetrics?:DeliveryMetric[];
  releaseAdoptConnections?:DeliveryConnection[];
  deliveryTooling?:DeliveryToolReference[];
};
export type InfographicPlacement = { src:string; title:string; caption:string; chapterSlug:string; sectionId?:string };
export type GlossaryTerm = { term:string; definition:string; why:string; example:string; related:string[] };
