import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ChevronLeft,ChevronRight } from "lucide-react";
import { chapters,chapterBySlug } from "@/content/chapters";
import { infographicsFor } from "@/content/infographics";
import { Callout } from "@/components/callout";
import { ContentBlocks } from "@/components/content-blocks";
import { Flow } from "@/components/flow";
import { Infographic } from "@/components/infographic";
import { PageTools } from "@/components/page-tools";

const structuralMarkerStatements=new Set(["Evidencia","Interpretación","Recomendación","Evidencia SRE","Evidencia Customer Success"]);
const contentClassLabel={"source-fact":"SOURCE FACT","assessment-interpretation":"ASSESSMENT INTERPRETATION",recommendation:"RECOMMENDATION",hypothesis:"HYPOTHESIS",mixed:"MIXED SOURCE / PROPOSITION"} as const;

export function generateStaticParams(){return chapters.map(chapter=>({slug:chapter.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
  const {slug}=await params,chapter=chapterBySlug(slug);
  return chapter?{title:chapter.title,description:chapter.summary}:{};
}

export default async function ChapterPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params,chapter=chapterBySlug(slug);
  if(!chapter)notFound();
  const index=chapters.indexOf(chapter),previous=chapters[index-1],next=chapters[index+1];
  return <div className="chaptergrid"><article className="chapter">
    <nav className="breadcrumbs"><Link href="/">Inicio</Link><span>/</span><span>{chapter.group}</span><span>/</span><b>{chapter.title}</b></nav>
    <header className="chapterhead"><p className="kicker">{chapter.eyebrow}</p><h1>{chapter.title}</h1><p>{chapter.summary}</p><div className="meta"><span>v0.1</span><span>Actualizado 19 ago 2026</span><span>{index<9?"Contenido fuente estructurado":"Lectura · 4 min"}</span></div></header>
    {chapter.editorialNotices?.map(notice=><aside className="editorialnotice" key={`${notice.title}-${notice.status}`} role="note"><div><strong>{notice.title}</strong><p>{notice.detail}</p></div><span>{notice.status}</span></aside>)}
    {chapter.clientValidations?.map(validation=><aside className="clientvalidation" key={validation.id} role="note"><b>{validation.id} · {validation.subject}</b><span>{validation.status}</span></aside>)}
    <Callout title="Executive takeaway">{chapter.takeaway}</Callout>
    {chapter.executive&&<section className="executivelayer" aria-labelledby="executive-layer-title">
      <div className="layerhead"><span>EXECUTIVE LAYER</span><h2 id="executive-layer-title">Lectura ejecutiva</h2></div>
      <div className="executivegrid"><div><h3>Key findings</h3><ul>{chapter.executive.keyFindings.map(finding=><li key={finding}>{finding}</li>)}</ul></div><div><h3>Implicación</h3><p>{chapter.executive.implication}</p><p className={`evidencestatus status-${chapter.executive.evidenceStatus}`}><b>Evidence status</b><span>{chapter.executive.evidenceConfidence} · {chapter.executive.evidenceStatus}</span></p><details className="sourcerefs"><summary>Source reference</summary>{chapter.executive.sources.map(source=><p key={source.locator}>{source.title} · {source.locator}</p>)}</details></div></div>
    </section>}
    {(chapter.operatingConcepts?.length||chapter.operatingStages?.length||chapter.operatingRoles?.length||chapter.decisionRights?.length||chapter.operatingArtifacts?.length||chapter.discoveryConcepts?.length||chapter.decideConcepts?.length||chapter.deliveryConcepts?.length||chapter.adoptionConcepts?.length||chapter.learningConcepts?.length)&&<section className="operatinglayer" aria-labelledby="operating-layer-title">
      <div className="layerhead"><span>OPERATING LAYER</span><h2 id="operating-layer-title">Cómo opera el modelo propuesto</h2><p>Lectura editorial del TO-BE. Los nombres fuente y sus locators se conservan en cada correspondencia.</p></div>
      {chapter.sourceOperatingSequence&&<div className="sourcesequence"><b>SOURCE MODEL — ORIGINAL SEQUENCE</b><div>{chapter.sourceOperatingSequence.map((stage,index)=><span key={`${stage.title}-${stage.locator}`}><strong>{stage.title}</strong><small>{stage.locator}</small>{index<chapter.sourceOperatingSequence!.length-1&&<i>→</i>}</span>)}</div></div>}
      {chapter.operatingStages&&<div className="canonicalmap">{chapter.operatingStages.map(stage=><article key={stage.canonicalStage}><header><small>CANONICAL OPERATING STAGE</small><h3>{stage.canonicalStage}</h3></header>{stage.purpose&&<p>{stage.purpose}</p>}<div className="substages"><b>SOURCE SUB-STAGE / TERMINOLOGY</b>{stage.sourceSubStages.map(item=><span key={`${item.title}-${item.locator}`}><strong>{item.title}</strong><small>{item.relationship} · {item.locator}</small></span>)}</div>{stage.inputs&&<p><b>Inputs</b> {stage.inputs.join(" · ")}</p>}{stage.steps&&<p><b>Activities</b> {stage.steps.join(" · ")}</p>}{stage.outputs&&<p><b>Outputs</b> {stage.outputs.join(" · ")}</p>}</article>)}</div>}
      {chapter.operatingRoles&&<div className="rolecards">{chapter.operatingRoles.map(role=><article key={role.id}><header><div><small>SOURCE ROLE</small><h3>{role.sourceRole}</h3></div><span>{role.mappingStatus}</span></header>{role.purpose&&<p>{role.purpose}</p>}{role.responsibilities&&<div><b>Responsabilidades</b><ul>{role.responsibilities.map(item=><li key={item}>{item}</li>)}</ul></div>}{role.decisionRights&&<p><b>Decisiones respaldadas por la fuente</b>{role.decisionRights.join(" · ")}</p>}{role.interactions&&<p><b>Interacciones</b>{role.interactions.join(" · ")}</p>}<footer>{role.canonicalStages?.join(" → ")}{role.sourceLocators.map(source=>` · ${source.locator}`).join("")}</footer></article>)}</div>}
      {chapter.decisionRights&&<details className="decisionrights"><summary>Derechos de decisión respaldados por la fuente ({chapter.decisionRights.length})</summary><div>{chapter.decisionRights.map(right=><article key={right.id}><header><b>{right.decision}</b><span>{right.validationStatus==="pending"?"CLIENT VALIDATION REQUIRED":right.validationStatus}</span></header>{right.decisionOwner&&<p><b>La fuente asigna</b>{right.decisionOwner}</p>}{right.participants&&<p><b>Consulta / participación</b>{right.participants.join(" · ")}</p>}{right.output&&<p><b>Output</b>{right.output}</p>}<footer>{right.source.title} · {right.source.locator}</footer></article>)}</div></details>}
      {chapter.operatingArtifacts&&<div className="artifactcards">{chapter.operatingArtifacts.map(artifact=><article key={artifact.id}><header><div><small>BUSINESS OBJECT</small><h3>{artifact.name}</h3></div><span>{artifact.taxonomy.join(" · ")}</span></header><p>{artifact.purpose}</p>{artifact.requiredFields&&<details><summary>Campos especificados por la fuente ({artifact.requiredFields.length})</summary><p>{artifact.requiredFields.join(" · ")}</p></details>}{artifact.owner&&<p><b>Owner fuente</b>{artifact.owner}</p>}{artifact.decisionEnabled&&<p><b>Decisión habilitada</b>{artifact.decisionEnabled}</p>}{artifact.lifecycle&&<p><b>Lifecycle fuente · {artifact.lifecycleCompleteness}</b>{artifact.lifecycle.join(" → ")}</p>}<footer>{artifact.canonicalStages?.join(" → ")}{artifact.sourceLocators.map(source=>` · ${source.locator}`).join("")}</footer></article>)}</div>}
      {chapter.artifactRelationships&&<div className="artifactflow"><b>OBJECT FLOW — SOURCE SUPPORTED</b><div>{chapter.artifactRelationships.map(relationship=><span key={`${relationship.from}-${relationship.to}`}><strong>{relationship.from} → {relationship.to}</strong><small>{relationship.relationship} · {relationship.source.locator}</small></span>)}</div><p>Las transiciones no mostradas permanecen <b>SOURCE MISSING</b>; esta secuencia no define tipos de issue ni workflows de Jira.</p></div>}
      {chapter.discoveryConcepts&&<div className="discoveryplaybook"><div className="discoveryflow"><b>DISCOVERY PLAYBOOK · SOURCE MODEL</b>{chapter.discoveryConcepts.map(concept=><article key={concept.id}><header><small>{concept.kind}</small><h3>{concept.title}</h3></header><p>{concept.purpose}</p>{concept.trigger&&<p><b>Trigger</b>{concept.trigger}</p>}{concept.activities&&<p><b>Activities</b>{concept.activities.join(" · ")}</p>}{concept.evidenceExpected&&<p><b>Evidence expected</b>{concept.evidenceExpected.join(" · ")}</p>}{concept.decisionEnabled&&<p><b>Decision</b>{concept.decisionEnabled}</p>}<footer>{concept.sourceLocators.map(source=>source.locator).join(" · ")}</footer></article>)}</div>
      {chapter.discoveryEvidenceModel&&<div className="evidencemodel"><h3>Assumption ≠ Hypothesis ≠ Evidence ≠ Insight ≠ Decision</h3>{chapter.discoveryEvidenceModel.map(item=><article key={item.term}><header><b>{item.term}</b><span>{item.sourceStatus}</span></header>{item.definition?<p>{item.definition}</p>:<p>La fuente no define este término de forma independiente.</p>}{item.qualityModel&&<ul>{item.qualityModel.map(level=><li key={level}>{level}</li>)}</ul>}<footer>{item.source&&`${item.source.title} · ${item.source.locator}`}</footer></article>)}</div>}
      {chapter.discoveryGates&&<div className="gatecards"><h3>Discovery Decision Gate</h3>{chapter.discoveryGates.map(gate=><article key={gate.id}><header><b>{gate.decision}</b><span>CLIENT VALIDATION REQUIRED</span></header><p>{gate.trigger}</p><p><b>Evidencia requerida por la fuente</b>{gate.evidenceRequired.join(" · ")}</p><p><b>Possible output</b>{gate.possibleOutputs.join(" · ")}</p><footer>{gate.source.locator}</footer></article>)}</div>}
      {chapter.artifactUses&&<div className="artifactuses"><h3>Integración con artefactos existentes</h3>{chapter.artifactUses.map(use=><article key={`${use.artifactId}-${use.relationship}`}><b>{use.artifactName}</b><span>{use.relationship}</span><p>{use.usage}</p><small>{use.source.locator}</small></article>)}</div>}
      {chapter.discoveryTechniques&&<details className="techniques"><summary>Técnicas fuente, no ceremonias obligatorias ({chapter.discoveryTechniques.length})</summary><div>{chapter.discoveryTechniques.map(technique=><article key={technique.id}><header><b>{technique.name}</b><small>{technique.source.locator}</small></header><p>{technique.purpose}</p>{technique.whenUseful&&<p><b>Útil cuando</b>{technique.whenUseful}</p>}{technique.evidenceGenerated&&<p><b>Evidencia</b>{technique.evidenceGenerated}</p>}</article>)}</div></details>}
      {chapter.discoveryCadences&&<div className="discoverycadence"><h3>Cadencia respaldada por la fuente</h3>{chapter.discoveryCadences.map(item=><article key={item.name}><span>{item.cadenceType}</span><b>{item.name}</b><p>{item.purpose}</p><small>{item.source.locator}</small></article>)}</div>}
      {chapter.discoveryFlowConnections&&<details className="flowcomparison"><summary>Conexión con el object flow existente</summary><div>{chapter.discoveryFlowConnections.map(item=><article key={`${item.from}-${item.to}`}><b>{item.from} → {item.to}</b><span>{item.status}</span><p>{item.rationale}</p><small>{item.source?.locator??"SOURCE MISSING"}</small></article>)}</div></details>}
      {chapter.antiPatternAssessments&&<details className="antipatternreview"><summary>Anti-pattern assessment ({chapter.antiPatternAssessments.length})</summary><div>{chapter.antiPatternAssessments.map(item=><article key={item.antiPattern}><header><b>{item.antiPattern}</b><span>{item.status}</span></header><p>{item.rationale}</p><small>{item.source.locator}</small></article>)}</div></details>}
      <details className="completeness"><summary>HOW completeness de Discovery ({chapter.discoveryConcepts.length})</summary><div>{chapter.discoveryConcepts.map(concept=><article key={concept.id}><header><b>{concept.title}</b><span className={`contentclass class-${concept.contentClass}`}>{contentClassLabel[concept.contentClass]}</span></header><div>{Object.entries(concept.completeness).map(([dimension,status])=><span key={dimension}><b>{dimension}</b>{status}</span>)}</div><footer>{concept.sourceLocators.map(source=>`${source.title} · ${source.locator}`).join(" | ")}</footer></article>)}</div></details>
      </div>}
      {chapter.decideConcepts&&<div className="decideplaybook"><div className="decisionpath"><b>DECIDE · SOURCE-SUPPORTED PATH</b><div>{["EVIDENCE","CRITERIA","TRADE-OFF","DECISION","COMMITMENT / DEFER / STOP","DECISION RECORD"].map((step,index)=><span key={step}><strong>{step}</strong>{index<5&&<i>→</i>}</span>)}</div></div>
      {chapter.decisionSemantics&&<div className="decisionsemantics"><h3>Separación semántica</h3>{chapter.decisionSemantics.map(item=><article key={item.term}><header><b>{item.term}</b><span>{item.sourceStatus}</span></header><p>{item.definition??"La fuente no define este concepto de forma independiente."}</p><small>{item.source?.locator??"SOURCE MISSING"}</small></article>)}</div>}
      <div className="decidecards">{chapter.decideConcepts.map(concept=><article key={concept.id}><header><small>{concept.kind}</small><h3>{concept.title}</h3></header><p>{concept.what}</p>{concept.criteria&&<p><b>Criteria</b>{concept.criteria.join(" · ")}</p>}{concept.outputs&&<p><b>Output</b>{concept.outputs.join(" · ")}</p>}<footer>{concept.sourceLocators.map(source=>source.locator).join(" · ")}</footer></article>)}</div>
      {chapter.priorityCommitment&&<aside className="prioritycommitment"><b>PRIORITY ≠ START DECISION ≠ CAPACITY COMMITMENT</b><div><p><strong>HIGH PRIORITY</strong>{chapter.priorityCommitment.priorityDefinition}</p><p><strong>APPROVED TO EXECUTE</strong>{chapter.priorityCommitment.executionApprovalDefinition}</p><p><strong>CAPACITY COMMITTED</strong>{chapter.priorityCommitment.capacityCommitmentDefinition}</p></div><small>{chapter.priorityCommitment.distinctionStatus} · {chapter.priorityCommitment.source.locator}</small></aside>}
      {chapter.decisionObjects&&<div className="decisionobjects"><h3>Objetos de decisión fuente</h3>{chapter.decisionObjects.map(item=><article key={`${item.sourceTerm}-${item.objectType}`}><header><b>{item.sourceTerm}</b><span>{item.validationStatus==="pending"?"PENDING VALIDATION":item.validationStatus}</span></header><p><strong>{item.objectType}</strong>{item.decisionApplied.join(" · ")}</p><small>{item.artifactRelationship} · {item.source.locator}</small></article>)}</div>}
      {chapter.prioritizationMethods&&<details className="methods"><summary>Métodos y escalas fuente ({chapter.prioritizationMethods.length})</summary><div>{chapter.prioritizationMethods.map(method=><article key={method.name}><header><b>{method.name}</b><span>{method.methodClass}</span></header><p>{method.purpose}</p>{method.criteria&&<p><b>Criteria</b>{method.criteria.join(" · ")}</p>}{method.scale&&<p><b>Scale</b>{method.scale.join(" · ")}</p>}{method.caveat&&<small>{method.caveat}</small>}<footer>{method.source.locator}</footer></article>)}</div></details>}
      {chapter.discoveryDecideConnections&&<details className="handoffreview"><summary>Discovery → Decide: conexión de información</summary><div>{chapter.discoveryDecideConnections.map(item=><article key={item.element}><header><b>{item.element}</b><span>{item.status}</span></header><p>{item.rationale}</p><small>{item.source.locator}</small></article>)}</div></details>}
      {chapter.decisionRecord&&<div className="decisionrecord"><h3>{chapter.decisionRecord.artifactName}</h3><p>{chapter.decisionRecord.sourceFields.join(" · ")}</p><div>{Object.entries(chapter.decisionRecord.fields).map(([field,status])=><span key={field}><b>{field}</b>{status}</span>)}</div><small>{chapter.decisionRecord.source.locator}</small></div>}
      {chapter.decisionCadences&&<div className="decisioncadences"><h3>Cadencia de decisión</h3>{chapter.decisionCadences.map(item=><article key={item.name}><span>{item.cadenceType}</span><b>{item.name}</b><p>{item.decisions.join(" · ")}</p><small>{item.source.locator}</small></article>)}</div>}
      {chapter.decisionMetrics&&<details className="decisionmetrics"><summary>Métricas fuente ({chapter.decisionMetrics.length})</summary><div>{chapter.decisionMetrics.map(item=><article key={item.name}><header><b>{item.name}</b><span>{item.metricClass}</span></header><p>{item.definition}</p><small>{item.target??"TARGET · SOURCE MISSING"} · {item.source.locator}</small></article>)}</div></details>}
      <details className="completeness"><summary>HOW completeness de DECIDE ({chapter.decideConcepts.length})</summary><div>{chapter.decideConcepts.map(concept=><article key={concept.id}><header><b>{concept.title}</b><span className={`contentclass class-${concept.contentClass}`}>{contentClassLabel[concept.contentClass]}</span></header><div>{Object.entries(concept.completeness).map(([dimension,status])=><span key={dimension}><b>{dimension}</b>{status}</span>)}</div><footer>{concept.sourceLocators.map(source=>`${source.title} · ${source.locator}`).join(" | ")}</footer></article>)}</div></details>
      </div>}
      {chapter.deliveryConcepts&&<div className="deliveryplaybook"><div className="deliverypath"><b>DELIVER · SOURCE-SUPPORTED PATH</b><div>{["COMMITMENT","SLICE","FLOW","QUALITY","RELEASE","OBSERVE"].map((step,index)=><span key={step}><strong>{step}</strong>{index<5&&<i>→</i>}</span>)}</div></div>
      {chapter.deliverySemantics&&<div className="deliverysemantics"><h3>Done, Release y Value no son sinónimos</h3>{chapter.deliverySemantics.map(item=><article key={item.term}><header><b>{item.term}</b><span>{item.sourceStatus}</span></header><p>{item.definition??"La fuente no define este concepto de forma independiente."}</p><small>{item.source?.locator??"SOURCE MISSING"}</small></article>)}</div>}
      <div className="deliverycards">{chapter.deliveryConcepts.map(concept=><article key={concept.id}><header><small>{concept.kind}</small><h3>{concept.title}</h3></header><p>{concept.what}</p>{concept.activities?.length&&<p><b>Activities</b>{concept.activities.join(" · ")}</p>}{concept.outputs?.length&&<p><b>Output</b>{concept.outputs.join(" · ")}</p>}<footer>{concept.sourceLocators.map(source=>source.locator).join(" · ")}</footer></article>)}</div>
      {chapter.commitmentDeliveryConnections&&<details className="deliveryconnections"><summary>DECIDE → DELIVER: conexión de información y compromiso</summary><div>{chapter.commitmentDeliveryConnections.map(item=><article key={item.element}><header><b>{item.element}</b><span>{item.status}</span></header><p>{item.rationale}</p><small>{item.source.locator}</small></article>)}</div></details>}
      {chapter.deliveryObjects&&<div className="deliveryobjects"><h3>Objetos fuente de Delivery</h3>{chapter.deliveryObjects.map(item=><article key={item.sourceTerm}><header><b>{item.sourceTerm}</b><span>{item.validationStatus==="pending"?"PENDING VALIDATION":item.validationStatus}</span></header><p>{item.purpose}</p>{item.parentChildRelationship&&<small>{item.parentChildRelationship}</small>}<footer>{item.source.locator}</footer></article>)}</div>}
      {chapter.valuableSliceAssessment&&<aside className="sliceassessment"><b>SMALL ≠ VALUABLE</b><p>{chapter.valuableSliceAssessment.definition}</p><div>{chapter.valuableSliceAssessment.optimizes.map(item=><span key={item}>{item}</span>)}</div><small>{chapter.valuableSliceAssessment.sourceStatus} · {chapter.valuableSliceAssessment.source.locator}</small></aside>}
      {chapter.releaseDecisions&&<div className="releasedecisions"><h3>Decisiones de Release</h3>{chapter.releaseDecisions.map(item=><article key={item.decision}><header><b>{item.decision}</b><span>PENDING VALIDATION</span></header><p><strong>Trigger</strong>{item.trigger}</p><p><strong>Criteria</strong>{item.criteria.join(" · ")}</p><small>DECISION OWNER · {item.decisionOwner??"SOURCE MISSING"} · {item.source.locator}</small></article>)}</div>}
      {chapter.deliveryMetrics&&<details className="deliverymetrics"><summary>Flow, DORA, Quality, Reliability, Release y Value ({chapter.deliveryMetrics.length})</summary><div>{chapter.deliveryMetrics.map(item=><article key={item.name}><header><b>{item.name}</b><span>{item.metricClass}</span></header><p>{item.definition}</p><small>BASELINE · {item.baseline} · TARGET · {item.target} · {item.source.locator}</small></article>)}</div></details>}
      {chapter.deliveryCadences&&<div className="deliverycadences"><h3>Cadencias y actividades</h3>{chapter.deliveryCadences.map(item=><article key={item.name}><span>{item.cadenceType}</span><b>{item.name}</b><p>{item.purpose}</p><small>{item.frequency??"Trigger según contexto"} · {item.source.locator}</small></article>)}</div>}
      {chapter.releaseAdoptConnections&&<details className="deliveryconnections"><summary>RELEASE → ADOPT: conexión de evidencia</summary><div>{chapter.releaseAdoptConnections.map(item=><article key={item.element}><header><b>{item.element}</b><span>{item.status}</span></header><p>{item.rationale}</p><small>{item.source.locator}</small></article>)}</div></details>}
      {chapter.deliveryTooling&&<details className="deliverytooling"><summary>Tooling fuente — logical model first</summary><div>{chapter.deliveryTooling.map(item=><article key={item.tool}><header><b>{item.tool}</b><span>{item.classification}</span></header><p>{item.relationship}</p><small>{item.source.locator}</small></article>)}</div></details>}
      <details className="completeness"><summary>HOW completeness de Delivery ({chapter.deliveryConcepts.length})</summary><div>{chapter.deliveryConcepts.map(concept=><article key={concept.id}><header><b>{concept.title}</b><span className={`contentclass class-${concept.contentClass}`}>{contentClassLabel[concept.contentClass]}</span></header><div>{Object.entries(concept.completeness).map(([dimension,status])=><span key={dimension}><b>{dimension}</b>{status}</span>)}</div><footer>{concept.sourceLocators.map(source=>`${source.title} · ${source.locator}`).join(" | ")}</footer></article>)}</div></details>
      </div>}
      {chapter.adoptionConcepts&&<div className="adoptionplaybook"><div className="valuepath"><b>ADOPT · SOURCE-SUPPORTED VALUE PATH</b><div>{["RELEASE","ACTIVATION","TTV","ADOPTION","ADHERENCE","VALUE EVIDENCE","LEARNING","DECISION"].map((step,index)=><span key={step}><strong>{step}</strong>{index<7&&<i>→</i>}</span>)}</div></div>
      {chapter.adoptionSemantics&&<div className="adoptionsemantics"><h3>Actividad, adopción y valor no son sinónimos</h3>{chapter.adoptionSemantics.map(item=><article key={item.term}><header><b>{item.term}</b><span>{item.sourceStatus}</span></header><p>{item.definition??"La fuente no define este concepto de forma independiente."}</p><small>{item.source?.locator??"SOURCE MISSING"}</small></article>)}</div>}
      {chapter.timeToValue&&<aside className="ttvmodel"><b>{chapter.timeToValue.canonicalTerm}</b><p>{chapter.timeToValue.definition}</p><div><span><strong>START</strong>{chapter.timeToValue.startEvent}</span><span><strong>END</strong>{chapter.timeToValue.endEvent}</span><span><strong>SUCCESS</strong>{chapter.timeToValue.successCondition}</span></div><small>CLIENT VALIDATION REQUIRED · {chapter.timeToValue.source.locator}</small></aside>}
      <div className="adoptioncards">{chapter.adoptionConcepts.map(concept=><article key={concept.id}><header><h3>{concept.title}</h3><span>{concept.contentClass.toUpperCase()}</span></header><p>{concept.purpose}</p>{concept.behavior&&<p><b>Behavior</b>{concept.behavior}</p>}{concept.successCondition&&<p><b>Success</b>{concept.successCondition}</p>}<footer>{concept.sourceLocators.map(source=>source.locator).join(" · ")}</footer></article>)}</div>
      {chapter.customerOutcomeConnections&&<details className="valueconnections"><summary>Activation / TTV / Adoption / Adherence / Autonomy → Outcome</summary><div>{chapter.customerOutcomeConnections.map(item=><article key={item.element}><header><b>{item.element}</b><span>{item.status}</span></header><p>{item.rationale}</p><small>{item.source.locator}</small></article>)}</div></details>}
      {chapter.operatingExamples?.map(example=><aside className="sourceexample" key={example.name}><b>{example.name} · {example.classification}</b><div>{Object.entries(example.details).map(([key,value])=><p key={key}><strong>{key}</strong>{Array.isArray(value)?value.join(" · "):value}</p>)}</div><small>{example.source.locator}</small></aside>)}
      {chapter.growthRelationships&&<div className="growthlinks"><h3>Growth: relaciones, no causalidad probada</h3>{chapter.growthRelationships.map(item=><article key={`${item.from}-${item.to}`}><header><b>{item.from} → {item.to}</b><span>{item.classification}</span></header><p>{item.rationale}</p><small>{item.source.locator}</small></article>)}</div>}
      {chapter.northStarSupport&&<aside className="northstarcandidate"><b>{chapter.northStarSupport.candidate}</b><p>{chapter.northStarSupport.rationale}</p><span>{chapter.northStarSupport.supportStatus} · H1 · CLIENT VALIDATION REQUIRED</span><small>{chapter.northStarSupport.source.locator}</small></aside>}
      <details className="completeness"><summary>HOW completeness de Adoption ({chapter.adoptionConcepts.length})</summary><div>{chapter.adoptionConcepts.map(concept=><article key={concept.id}><header><b>{concept.title}</b><span className={`contentclass class-${concept.contentClass}`}>{contentClassLabel[concept.contentClass]}</span></header><div>{Object.entries(concept.completeness).map(([dimension,status])=><span key={dimension}><b>{dimension}</b>{status}</span>)}</div><footer>{concept.sourceLocators.map(source=>`${source.title} · ${source.locator}`).join(" | ")}</footer></article>)}</div></details>
      </div>}
      {chapter.learningConcepts&&<div className="learningplaybook"><div className="valuepath"><b>LEARN · SOURCE-SUPPORTED LOOP</b><div>{["SIGNAL","PATTERN","EVIDENCE","INSIGHT","LEARNING","DECISION"].map((step,index)=><span key={step}><strong>{step}</strong>{index<5&&<i>→</i>}</span>)}</div></div>
      {chapter.signalLearningChain&&<div className="learningchain"><h3>Reconciliación semántica</h3>{chapter.signalLearningChain.map(item=><article key={item.element}><header><b>{item.element}</b><span>{item.status}</span></header><p>{item.rationale}</p><small>{item.source.locator}</small></article>)}</div>}
      <div className="learningcards">{chapter.learningConcepts.map(concept=><article key={concept.id}><h3>{concept.title}</h3><p>{concept.purpose}</p>{concept.inputs&&<p><b>Input</b>{concept.inputs.join(" · ")}</p>}{concept.outputs&&<p><b>Output</b>{concept.outputs.join(" · ")}</p>}<footer>{concept.sourceLocators.map(source=>source.locator).join(" · ")}</footer></article>)}</div>
      {chapter.learningDecisions&&<div className="learningdecisions"><h3>Learning → Decision</h3>{chapter.learningDecisions.map(item=><article key={item.decision}><header><b>{item.decision}</b><span>PENDING VALIDATION</span></header><p>{item.output}</p><small>DECISION OWNER · {item.decisionOwner??"SOURCE MISSING"} · {item.source.locator}</small></article>)}</div>}
      {chapter.feedbackSignals&&<details className="feedbacksignals"><summary>Fuentes y señales ({chapter.feedbackSignals.length})</summary><div>{chapter.feedbackSignals.map(item=><article key={`${item.sourceRole}-${item.signal}`}><header><b>{item.sourceRole}</b><span>SIGNAL</span></header><p>{item.signal}</p><small>{item.format??"FORMAT · SOURCE MISSING"} · {item.source.locator}</small></article>)}</div></details>}
      {chapter.feedbackLoopConnections&&<details className="valueconnections"><summary>Learning vuelve al operating loop</summary><div>{chapter.feedbackLoopConnections.map(item=><article key={item.element}><header><b>{item.element}</b><span>{item.status}</span></header><p>{item.rationale}</p><small>{item.source.locator}</small></article>)}</div></details>}
      <details className="completeness"><summary>HOW completeness de Learning ({chapter.learningConcepts.length})</summary><div>{chapter.learningConcepts.map(concept=><article key={concept.id}><header><b>{concept.title}</b><span className={`contentclass class-${concept.contentClass}`}>{contentClassLabel[concept.contentClass]}</span></header><div>{Object.entries(concept.completeness).map(([dimension,status])=><span key={dimension}><b>{dimension}</b>{status}</span>)}</div><footer>{concept.sourceLocators.map(source=>`${source.title} · ${source.locator}`).join(" | ")}</footer></article>)}</div></details>
      </div>}
      {chapter.adoptionLearningMetrics&&<details className="adoptionmetrics"><summary>Métricas fuente ({chapter.adoptionLearningMetrics.length})</summary><div>{chapter.adoptionLearningMetrics.map(item=><article key={item.name}><header><b>{item.name}</b><span>{item.metricClass}</span></header><p>{item.definition}</p><small>BASELINE · {item.baseline} · TARGET · {item.target} · {item.source.locator}</small></article>)}</div></details>}
      {chapter.learningCadences&&<div className="learningcadences"><h3>Data collection, review, learning y decision</h3>{chapter.learningCadences.map(item=><article key={item.name}><span>{item.activityType}</span><b>{item.name}</b><p>{item.purpose}</p><small>{item.frequency??"Trigger según contexto"} · {item.source.locator}</small></article>)}</div>}
      {chapter.adoptionLearningTooling&&<details className="learningtooling"><summary>Tooling fuente — logical model first</summary><div>{chapter.adoptionLearningTooling.map(item=><article key={item.tool}><header><b>{item.tool}</b><span>{item.classification}</span></header><p>{item.relationship}</p><small>{item.source.locator}</small></article>)}</div></details>}
      {chapter.operatingConcepts&&<details className="completeness"><summary>HOW completeness y trazabilidad editorial ({chapter.operatingConcepts.length})</summary><div>{chapter.operatingConcepts.map(concept=><article key={concept.id}><header><b>{concept.title}</b><span className={`contentclass class-${concept.contentClass}`}>{contentClassLabel[concept.contentClass]}</span></header><p>{concept.canonicalLayers.join(" · ")}</p><div>{Object.entries(concept.completeness).map(([dimension,status])=><span key={dimension}><b>{dimension}</b>{status}</span>)}</div>{concept.gapIds.length>0&&<small>GAPS · {concept.gapIds.join(" · ")}</small>}<footer>{concept.sourceLocators.map(source=>`${source.title} · ${source.locator}`).join(" | ")}</footer></article>)}</div></details>}
    </section>}
    {infographicsFor(chapter.slug).map(graphic=><Infographic key={graphic.src} {...graphic} relatedSection="Resumen"/>)}
    {chapter.executive&&<div className="deepdividelabel"><span>DEEP DIVE</span><p>Evidencia, diagnóstico, detalle y artefactos de la fuente.</p></div>}
    {chapter.sections.map((section,sectionIndex)=><section id={section.id} className="docsection" key={section.id}><span className="sectionnum">{String(sectionIndex+1).padStart(2,"0")}</span><div>
      <h2>{section.title}<a className="anchor" href={`#${section.id}`} aria-label={`Enlace a ${section.title}`}>#</a></h2>{section.contentClass&&<span className={`contentclass class-${section.contentClass}`}>{contentClassLabel[section.contentClass]}</span>}
      {section.blocks?<ContentBlocks blocks={section.blocks}/>:section.kind&&section.kind!=="default"?<Callout kind={section.kind} title={section.kind==="evidence"?"Evidencia / lectura":"Punto clave"}><p>{section.body}</p>{section.bullets&&<ul>{section.bullets.map(item=><li key={item}>{item}</li>)}</ul>}</Callout>:<><p>{section.body}</p>{section.bullets&&<ul className={section.visual==="cards"?"bulletcards":""}>{section.bullets.map(item=><li key={item}>{item}</li>)}</ul>}</>}
      {section.visual==="flow"&&section.body&&<Flow text={section.body}/>}
      {section.impactSemantics&&<aside className="impactsemantics" role="note"><b>WASTE IMPACT SEMANTICS</b><div>{section.impactSemantics.map(value=><span className={`impact-${value.toLowerCase().replaceAll(" ","-")}`} key={value}>{value}</span>)}</div>{section.impactValidationStatus==="pending"&&<small>PENDING VALIDATION</small>}</aside>}
      {section.clientValidations?.map(validation=><aside className="clientvalidation sectionvalidation" key={validation.id} role="note"><b>{validation.id} · {validation.subject}</b><span>{validation.status}</span></aside>)}
      {section.evidence&&section.evidence.length>0&&<details className="evidencedetails"><summary>Evidencia y trazabilidad ({section.evidence.filter(evidence=>!structuralMarkerStatements.has(evidence.statement)).length} claims · {section.evidence.filter(evidence=>structuralMarkerStatements.has(evidence.statement)).length} structural markers)</summary><div>{section.evidence.map(evidence=>{const structural=structuralMarkerStatements.has(evidence.statement);return <article className={structural?"structuralmarker":undefined} key={evidence.id}><header><b>{evidence.sourceMark?`[${evidence.sourceMark}]`:"SOURCE MARK —"}</b><span>{structural?"STRUCTURAL MARKER":evidence.classification??"PENDING EVIDENCE REVIEW"}</span><small>{structural?"EXCLUDED FROM CLAIM COUNTS":`${evidence.confidence} · ${evidence.validationStatus}`}</small></header><p>{evidence.statement}</p>{!structural&&evidence.classification===null&&<em>PENDING EVIDENCE REVIEW</em>}<footer>{evidence.sourceArea} · {evidence.sourceLocator}</footer></article>})}</div></details>}
      {section.sources&&section.sources.length>0&&<details className="sourcerefs"><summary>Source reference</summary>{section.sources.map(source=><p key={source.locator}>{source.title} · {source.locator}</p>)}</details>}
      {infographicsFor(chapter.slug,section.id).map(graphic=><Infographic key={graphic.src} {...graphic} relatedSection={section.title}/>)}</div></section>)}
    <PageTools/>
    <div className="related"><h2>Temas relacionados</h2><div>{chapter.related.map(relatedSlug=>{const related=chapterBySlug(relatedSlug);return related&&<Link href={`/chapter/${relatedSlug}`} key={relatedSlug}>{related.title}<ChevronRight/></Link>})}</div></div>
    <nav className="prevnext">{previous?<Link href={`/chapter/${previous.slug}`}><ChevronLeft/><span><small>Anterior</small>{previous.title}</span></Link>:<span/>}{next&&<Link href={`/chapter/${next.slug}`}><span><small>Siguiente</small>{next.title}</span><ChevronRight/></Link>}</nav>
  </article><aside className="toc"><b>En esta página</b><a href="#content">Resumen</a>{chapter.sections.map(section=><a href={`#${section.id}`} key={section.id}>{section.title}</a>)}<div><span>Progreso</span><b>{index+1} / {chapters.length}</b><progress value={index+1} max={chapters.length}/></div></aside></div>;
}
