import type { Chapter, Section, SectionKind, VisualKind } from "@/types/content";

const S=(id:string,title:string,body:string,bullets?:string[],kind:SectionKind="default",visual?:VisualKind):Section=>({id,title,body,bullets,kind,visual});
export const legacyChapters: Chapter[] = [
 {slug:"jira",group:"Tooling / Jira",title:"Arquitectura Jira recomendada",eyebrow:"21 · Tooling",summary:"Jira hace visible el Operating System mediante capas simples y trazables.",takeaway:"Jira debe hacer visible el Product Operating System. No debe convertirse en el Product Operating System.",sections:[S("layers","Arquitectura por capas","Jira Product Discovery: Signal, Opportunity, Evidence, Outcome, Bet. Jira Software: Bet, Epic, Valuable Slice, Story/Task, Release. Customer Signals: CS, Support, UX, Analytics, Customer. Confluence: Research, Decisions, Success Criteria, Learning, Technical Knowledge.",undefined,"recommendation","cards"),S("minimal","Configuración mínima","Minimal Workflows · Minimal Fields · Minimal Automations · Minimal Dashboards."),S("anti","Anti-patterns","Project per client; project per cell; demasiados issue types; status como departamentos; explosión de campos o workflows; todo en Jira; Jira como monitoreo de personas.",undefined,"risk")],related:["artifacts","delivery"]},
 {slug:"roadmap",group:"Implementation",title:"Roadmap 30 / 60 / 90",eyebrow:"22 · Implementación",summary:"Un piloto recorre el loop completo antes de escalar el modelo.",takeaway:"Empezar pequeño. Demostrar valor. Escalar lo que funcione.",sections:[S("timeline","Plan","0–30 Enfocar: Outcome piloto, evidencia, board, value stream y baseline. 31–60 Probar: Discovery ligero, prototipo, Bet, slice, Flow Review y release. 61–90 Consolidar: Adoption, TTV, Adherence, Learning Review y estabilización.",undefined,"recommendation","timeline"),S("gates","Evidence gates","Gate 1: ¿evidencia suficiente para invertir? Gate 2: ¿justifica continuar? Gate 3: ¿escalar, ajustar o detener?",undefined,"decision"),S("results","Resultados esperados","D30 foco visible · D60 primer loop completo · D90 modelo repetible. Deben validarse como evolución, no como compromiso contractual.")],related:["quick-wins","adoption-plan"]},
 {slug:"quick-wins",group:"Implementation",title:"Quick Wins",eyebrow:"23 · Empezar mañana",summary:"Cinco movimientos reducen desperdicio sin crear una transformación paralela.",takeaway:"Quick Win ≠ más proceso. Quick Win = menos desperdicio.",sections:[S("wins","Cinco acciones","01 Focus — Outcome Board. 02 Frame — Opportunity Card. 03 Validate — Prototype Before Code. 04 Flow — Flow Review. 05 Learn — Adoption Review.",undefined,"recommendation","cards"),S("fields","Ficha mínima","Cada Quick Win registra Problem, Action, Effort, Expected impact, Metric y Owner. Effort e impacto se acuerdan, no se inventan.")],related:["roadmap","governance"]},
 {slug:"risks",group:"Implementation",title:"Riesgos de transformación",eyebrow:"24 · Risk radar",summary:"El principal riesgo es cambiar el vocabulario sin cambiar el sistema de decisión.",takeaway:"El éxito es cambiar el sistema de decisión, no el vocabulario.",sections:[S("radar","Risk radar","Outcome Theatre · WIP Overload · Bureaucracy · Ownership Gap · Vanity Metrics · Premature Scale.",undefined,"risk","cards"),S("protection","Protecciones","WIP Limits · Evidence Gates · Decision Rights · Minimum Artifacts · Value Metrics · Pilot First.",undefined,"recommendation"),S("warnings","Early warnings","WIP ↑ · Meetings ↑ · Forms ↑ · Jira + Excel · Release without Learning · Everything is Priority.",undefined,"risk")],related:["roadmap","definition-success"]},
 {slug:"adoption-plan",group:"Implementation",title:"Plan de adopción",eyebrow:"25 · Transferencia",summary:"El ownership evoluciona desde acompañamiento a operación autónoma de SEIF.",takeaway:"La transformación se completa cuando SEIF opera, adapta y mejora el sistema sin dependencia externa.",sections:[S("journey","Adoption journey","Aware → Understand → Practice → Evidence → Habit → Ownership.",undefined,"recommendation","flow"),S("transfer","Evolución conceptual","0–30 consultoría lidera / SEIF participa. 31–60 co-facilitación. 61–90 SEIF lidera. Post 90 SEIF owns. No representa porcentajes ni compromiso contractual.",undefined,"default","timeline")],related:["roadmap","definition-success"]},
 {slug:"definition-success",group:"Implementation",title:"Definition of Success",eyebrow:"26 · Medición",summary:"La transformación se evalúa por foco, evidencia, flujo, valor, aprendizaje y autonomía.",takeaway:"Success = Focus × Evidence × Flow × Value × Learning; es un modelo conceptual, no una fórmula financiera.",sections:[S("indicators","Indicadores","Focus: Strategic WIP. Evidence: Bets con evidencia. Flow: Cycle Time/Aging. Value: Activation/TTV/Adherence. Learning: Bets con decisión posterior a evidencia. Ownership: operación autónoma SEIF.",undefined,"default","cards"),S("candidate","North Star de transformación candidata","Proporción de Bets relevantes que completan Evidence → Delivery → Customer Evidence → Decision. Es temporal y requiere definición y baseline.",undefined,"recommendation")],related:["north-star","evidence-map"]},
 {slug:"evidence-map",group:"Evidence",title:"Anexos & Evidence Map",eyebrow:"27 · Evidencia",summary:"El repositorio protege el rigor separando hechos, convergencia, inferencias e hipótesis.",takeaway:"Una recomendación es tan confiable como la trazabilidad de la evidencia que la sostiene.",sections:[S("classification","Clasificación","E1 Direct Evidence · E2 Convergent Evidence · E3 Supported Inference · H1 Hypothesis to Validate.",undefined,"evidence"),S("records","Mapa inicial","Outcome orientation exists — E1. Discovery exists but depth varies — E2. Traceability is fragmented — E2/E3. North Star candidate — H1. Jira architecture — H1.",undefined,"default","cards"),S("schema","Ficha de evidencia","Source · Evidence Type · Assessment Finding · Confidence · Related Recommendation. Las fuentes detalladas deben completarse con los registros del assessment.",undefined,"recommendation")],related:["methodology","executive-summary"]}
];
