param([string]$Source="source-private/SEIF-master-v0.1.docx")
$ErrorActionPreference="Stop";$repo=Split-Path -Parent $PSScriptRoot;$sourcePath=Join-Path $repo $Source
if(-not(Test-Path -LiteralPath $sourcePath -PathType Leaf)){throw"SOURCE NOT FOUND"}
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($sourcePath)
try{$entry=$zip.GetEntry("word/document.xml");$reader=[IO.StreamReader]::new($entry.Open());try{[xml]$document=$reader.ReadToEnd()}finally{$reader.Dispose()}}finally{$zip.Dispose()}
$ns=[Xml.XmlNamespaceManager]::new($document.NameTable);$ns.AddNamespace("w","http://schemas.openxmlformats.org/wordprocessingml/2006/main");$body=$document.SelectSingleNode("//w:body",$ns)
function Text-Of($node){return(($node.SelectNodes(".//w:t",$ns)|ForEach-Object{$_.InnerText})-join"").Trim()}
function Max-Size($p){$s=@($p.SelectNodes(".//w:rPr/w:sz",$ns)|ForEach-Object{[int]$_.GetAttribute("val",$ns.LookupNamespace("w"))});if(!$s.Count){return 0};return($s|Measure-Object -Maximum).Maximum}
function Slugify([string]$v){$n=$v.Normalize([Text.NormalizationForm]::FormD);$c=$n.ToCharArray()|Where-Object{[Globalization.CharUnicodeInfo]::GetUnicodeCategory($_)-ne[Globalization.UnicodeCategory]::NonSpacingMark};return((-join$c).ToLowerInvariant()-replace"[^a-z0-9]+","-").Trim("-")}
function Ref([string]$locator){return [ordered]@{title="12. Product Discovery Model";locator=$locator}}
function CV([string]$id,[string]$subject){return [ordered]@{id=$id;subject=$subject;status="CLIENT VALIDATION REQUIRED"}}
function Completeness([string[]]$complete,[string[]]$partial,[string[]]$missing){$v=[ordered]@{};foreach($k in $complete){$v[$k]="SOURCE COMPLETE"};foreach($k in $partial){$v[$k]="SOURCE PARTIAL"};foreach($k in $missing){$v[$k]="SOURCE MISSING"};return $v}
function Section-Class([string]$title){if($title-match'(?i)Maturity|North Star'){return "hypothesis"};if($title-match'(?i)cambio fundamental|Estado SEIF|assessment|AS-IS|diagnóstico|Product Analytics'){return "mixed"};return "recommendation"}
function Validations-For([string]$title){$r=@();if($title-match'(?i)Discovery Team|Integración con Customer|Integración con Soporte|Integración con Marketing|Integración con Desarrollo'){$r+=,(CV "CL-04" "Mapeo de Product y demás roles fuente a roles organizacionales futuros")};if($title-match'(?i)Decision Gate|Decisiones de salida'){$r+=,(CV "CL-05" "Decision owner, participantes y autoridad del Discovery Gate")};if($title-match'(?i)WIP de Discovery'){$r+=,(CV "CL-09" "Límite numérico de WIP a establecer mediante baseline/piloto")};if($title-match'(?i)Discovery Cadence'){$r+=,(CV "CL-11" "Cadencia propuesta y participantes")};if($title-match'(?i)AI-Assisted|AI Prototype|Product Analytics'){$r+=,(CV "CL-10" "Relación futura de Analytics, IA y tooling con Discovery")};if($title-match'(?i)North Star'){$r+=,(CV "CL-06" "North Star candidate y conexión con Discovery")};if($title-match'(?i)Discovery Metrics|Learning Lead Time|Cost of Learning'){$r+=,(CV "CL-07" "Definiciones operacionales, instrumentación, baseline y ownership de métricas")};return $r}

$chapter=[ordered]@{sections=@();start=$null;end=$null};$current=0;$expected=1;$pi=0;$ti=0;$section=$null;$pending=@();$pendingStart=$null;$pendingEnd=$null
function Flush-List{if($null-ne$script:section-and$script:pending.Count){$script:section.blocks+=[ordered]@{type="list";items=@($script:pending);source=(Ref "P$script:pendingStart–P$script:pendingEnd")}};$script:pending=@();$script:pendingStart=$null;$script:pendingEnd=$null}
foreach($node in $body.ChildNodes){if($node.LocalName-eq"p"){$pi++;$text=Text-Of $node;if($expected-le13-and$text-match("^"+$expected+"\.\s+")-and(Max-Size $node)-ge36){Flush-List;$current=$expected;$expected++;if($current-eq12){$chapter.start="P$pi";$section=$null;continue};if($current-eq13){$chapter.end="P$($pi-1)";break}};if($current-ne12){continue};$chapter.end="P$pi";if(!$text){Flush-List;continue};if($text-match'^12\.\d+\s+'){Flush-List;$title=($text-replace'^12\.\d+\s+','').Trim();$section=[ordered]@{id=(Slugify $title);title=$title;contentClass=(Section-Class $title);blocks=@();evidence=@();sources=@((Ref "P$pi"))};$v=Validations-For $title;if($v.Count){$section.clientValidations=@($v)};$chapter.sections+=$section;continue};if($null-eq$section){continue};$isList=$null-ne$node.SelectSingleNode("./w:pPr/w:numPr",$ns);if($isList){if(!$pending.Count){$pendingStart=$pi};$pendingEnd=$pi;$pending+=$text}else{Flush-List;$section.blocks+=[ordered]@{type="paragraph";text=$text;source=(Ref "P$pi")}}}elseif($node.LocalName-eq"tbl"){$ti++;if($current-ne12){continue};Flush-List;$rows=@();foreach($row in $node.SelectNodes("./w:tr",$ns)){$rows+=,@($row.SelectNodes("./w:tc",$ns)|ForEach-Object{Text-Of $_})};if($rows.Count-and$null-ne$section){$headers=@($rows[0]);$data=if($rows.Count-gt1){@($rows[1..($rows.Count-1)])}else{@()};$kind=if(($headers-join" ")-match'(?i)Dimensión|Nivel|Riesgo'){"comparison"}elseif(($headers-join" ")-match'(?i)Métrica'){"scorecard"}else{"simple"};$section.blocks+=[ordered]@{type="table";table=[ordered]@{id=("source-table-{0:D3}"-f$ti);caption=$section.title;kind=$kind;headers=$headers;rows=$data;source=(Ref "T$ti")}}}}};Flush-List

$completeCore=Completeness @("WHAT","WHY","HOW","INPUT","OUTPUT","ARTIFACT","DECISION","EXAMPLE","EVIDENCE QUALITY","EXIT / DECISION CRITERIA","FEEDBACK LOOP") @("WHO","WHEN","METRIC") @("TOOL")
$partialTechnique=Completeness @("WHAT","WHY","HOW","INPUT","OUTPUT","EXAMPLE") @("WHO","WHEN","ARTIFACT","DECISION","EVIDENCE QUALITY") @("METRIC","TOOL","EXIT / DECISION CRITERIA","FEEDBACK LOOP")
function DC([string]$id,[string]$kind,[string]$title,[string]$purpose,[string]$locator,[string[]]$inputs,[string[]]$activities,[string[]]$outputs,[string[]]$roles,[string[]]$artifacts,[string[]]$evidence,[string]$decision,[string]$trigger=""){return [ordered]@{id=$id;kind=$kind;title=$title;purpose=$purpose;trigger=$trigger;inputs=$inputs;activities=$activities;outputs=$outputs;roles=$roles;artifacts=$artifacts;evidenceExpected=$evidence;decisionEnabled=$decision;sourceLocators=@((Ref $locator));contentClass="recommendation";completeness=$completeCore}}
$concepts=@(
 (DC "trigger" "TRIGGER" "Señal que merece investigación" "Iniciar aprendizaje desde una observación, problema o anomalía sin convertirla automáticamente en Feature." "P3570–P3586; P3643–P3657" @("señales de cliente, operación, mercado, datos o tecnología") @("capturar contexto","determinar si merece framing") @("Signal contextualizada") @("Product","fuente de señal") @("Signal") @("observación disponible") "Investigar o no" "Aparece una señal relevante"),
 (DC "signal" "SIGNAL" "SIGNAL" "Hacer visible algo relevante observado durante la operación." "P3683–P3689; P4183–P4188" @("observación") @("capturar durante la operación") @("Signal") @("CS","Soporte","Marketing","Analytics","Product") @("Signal") @("hecho observado o fuente identificable") "Convertir en Opportunity cuando se formula el problema"),
 (DC "opportunity" "PROBLEM / OPPORTUNITY" "Opportunity" "Representar una situación donde un actor puede obtener un resultado mejor." "P3638–P3681" @("Signal","contexto","evidencia disponible") @("identificar actor, resultado, impedimento, impacto y evidencia") @("Opportunity Statement") @("Product","UX/UI","fuente de evidencia") @("Opportunity Card") @("problema observado e impacto") "Explorar, ajustar, esperar o detener"),
 (DC "framing" "FRAMING" "Problem framing" "Eliminar ambigüedad antes de plantear una solución." "P3659–P3668; P4154–P4169" @("Opportunity") @("separar solicitud, problema y solución","hacer visibles unknowns") @("Opportunity en FRAMING / DISCOVERY") @("Product","UX/UI") @("Opportunity Card","Discovery Board") @("quién, qué intenta lograr, impedimento, impacto y evidencia") "Ingresar a Discovery o Wait / Stop"),
 (DC "assumption" "ASSUMPTION" "Assumption Mapping" "Identificar creencias importantes con poca evidencia para probar primero la incertidumbre que podría invalidar la inversión." "P3972–P3981" @("Hypothesis","Evidence Map") @("comparar importancia y evidencia") @("Key Assumptions priorizados") @("Product","UX/UI","Desarrollo/SRE según riesgo") @("Opportunity Card","Evidence Map") @("nivel de evidencia disponible") "Seleccionar qué validar primero"),
 (DC "hypothesis" "HYPOTHESIS" "Hypothesis Model" "Proponer una intervención separando lo conocido de lo que se cree que funcionará." "P3962–P3970" @("Opportunity","Outcome","assumptions") @("formular solución/cambio, usuario, Outcome y evidencia esperada") @("Hypothesis") @("Product","UX/UI","Desarrollo/SRE según incertidumbre") @("Opportunity Card") @("señal observable esperada") "Validar, ajustar o descartar"),
 (DC "research" "RESEARCH" "Investigación proporcional al riesgo" "Reducir incertidumbre del problema, comportamiento, experiencia, mercado o solución con técnicas proporcionales." "P3721–P3784" @("pregunta de aprendizaje","nivel de riesgo") @("analytics, tickets, entrevistas, observación, journey o research estructurado según riesgo") @("evidencia utilizable") @("Product","UX/UI","CS","Soporte","Marketing") @("Evidence Map") @("evidencia proporcional al riesgo") "Aceptar, modificar o descartar hipótesis"),
 (DC "experiment" "EXPERIMENT" "Cheapest Validation" "Comprar evidencia progresivamente mediante el mecanismo de menor costo capaz de responder la pregunta." "P3983–P4016" @("hipótesis riesgosa","pregunta de validación") @("seleccionar y ejecutar el nivel mínimo de la Validation Ladder") @("resultado observado") @("Product","UX/UI","Desarrollo/SRE cuando aplica") @("Prototype / Experiment","Evidence Map") @("respuesta observable a la pregunta") "Escalar la inversión o cambiar la hipótesis"),
 (DC "evidence" "EVIDENCE" "Evidence Map y jerarquía A–D" "Separar KNOWN, ASSUMED y UNKNOWN y ponderar la naturaleza de la evidencia sin scores de confianza." "P3849–P3893" @("señales, investigación y validación") @("clasificar conocimiento y fuente de evidencia") @("Evidence Map actualizada") @("quien posee evidencia relevante") @("Evidence Map") @("A comportamiento; B usuario; C comercial/operacional; D opinión/hipótesis") "Determinar si la incertidumbre es aceptable"),
 (DC "synthesis" "SYNTHESIS" "Síntesis de evidencia" "Consolidar patrones y resultados para mantener conectados problema, evidencia, Outcome e hipótesis." "P4018–P4036; P4399–P4420" @("research, feedback, datos y resultados") @("research synthesis","pattern detection","comparar expected vs actual") @("evidencia conectada y aprendizaje") @("Product","UX/UI") @("Evidence Map","Product Discovery Canvas") @("patrones trazables a fuentes") "Preparar Discovery Decision Gate"),
 (DC "decision" "DECISION" "Discovery Decision Gate" "Finalizar Discovery por evidencia suficiente para decidir, no por terminar diseño o documentación." "P4087–P4121" @("problem, user, Outcome, evidence, risk, validation, measurement") @("revisar preguntas críticas") @("PROCEED","ADJUST","EXPLORE MORE","STOP") @("Product","participantes con evidencia") @("Opportunity Card") @("evidencia proporcional al riesgo") "Proceed / Adjust / Explore More / Stop"),
 (DC "learning" "LEARNING" "Feedback loop" "Usar evidencia previa y posterior al release para cambiar la acción y alimentar nuevas oportunidades." "P4038–P4059; P4183–P4193; P4393–P4397" @("evidencia de validación o post-release") @("learn","adjust","validate again","Outcome Review") @("new learning","nueva decisión o Opportunity") @("Product","UX/UI","CS","Analytics") @("Evidence Map","Learning Card — conexión parcial") @("expected vs actual") "Ajustar, validar nuevamente o decidir inversión")
)

$evidenceModel=@(
 [ordered]@{term="ASSUMPTION";definition="Creencia cuya importancia para que la solución funcione se contrasta con el nivel de evidencia disponible.";sourceStatus="SOURCE COMPLETE";source=(Ref "P3972–P3981")},
 [ordered]@{term="HYPOTHESIS";definition="Propuesta de solución o cambio que se espera permita a un usuario lograr un Outcome y que declara la evidencia esperada.";sourceStatus="SOURCE COMPLETE";source=(Ref "P3962–P3970")},
 [ordered]@{term="EVIDENCE";definition="Información que permite separar KNOWN, ASSUMED y UNKNOWN y respaldar una decisión proporcional al riesgo.";qualityModel=@("Nivel A — Comportamiento observado","Nivel B — Evidencia directa del usuario","Nivel C — Evidencia comercial/operacional","Nivel D — Opinión / hipótesis interna; origen válido, no evidencia suficiente de problema");sourceStatus="SOURCE COMPLETE";source=(Ref "P3849–P3893")},
 [ordered]@{term="INSIGHT";sourceStatus="SOURCE MISSING"},
 [ordered]@{term="DECISION";definition="Resultado explícito de Discovery: PROCEED, ADJUST, EXPLORE MORE o STOP.";sourceStatus="SOURCE COMPLETE";source=(Ref "P4109–P4121")}
)
$gateInputs=@("Problem","User","Outcome","Evidence","Risk","Validation","Measurement");$gateEvidence=@("evidencia del problema","actor claro","Outcome definido","importancia respaldada","incertidumbres críticas identificadas","hipótesis más riesgosas suficientemente probadas","señal post-release definida")
$gates=@();foreach($d in @(@("proceed","PROCEED","Existe evidencia suficiente; la oportunidad puede convertirse en Delivery Bet."),@("adjust","ADJUST","El problema sigue siendo relevante, pero la hipótesis necesita modificación."),@("explore-more","EXPLORE MORE","Permanece una incertidumbre crítica que requiere aprendizaje adicional."),@("stop","STOP","La evidencia no justifica inversión adicional."))){$gates+=[ordered]@{id=$d[0];decision=$d[1];trigger="Discovery Decision Gate: evidencia suficiente para tomar una decisión explícita.";inputs=$gateInputs;evidenceRequired=$gateEvidence;participants=@("Product","participantes que poseen evidencia o reducen incertidumbre crítica");decisionOwner="Product — fuente; autoridad organizacional pendiente de validación";possibleOutputs=@($d[1],$d[2]);source=(Ref "P4087–P4121");validationStatus="pending"}}

function Technique([string]$id,[string]$name,[string]$purpose,[string]$when,[string]$evidence,[string]$locator,[string]$example=""){return [ordered]@{id=$id;name=$name;purpose=$purpose;whenUseful=$when;evidenceGenerated=$evidence;example=$example;source=(Ref $locator)}}
$techniques=@(
 (Technique "existing-evidence" "Existing Evidence / data analysis" "Responder primero con evidencia ya disponible." "Antes de generar nueva investigación o cuando el riesgo es bajo." "Analytics, tickets, datos y conversaciones existentes." "P3732–P3738; P3983–P3988"),
 (Technique "interviews" "Entrevistas" "Obtener evidencia directa del usuario." "Cuando la incertidumbre está en problema, comportamiento o necesidad." "Evidencia Nivel B." "P3748–P3756; P3876–P3880"),
 (Technique "observation" "Observación" "Ver comportamiento y fricción en contexto." "Cuando lo declarado puede diferir de lo que ocurre." "Comportamiento observado y evidencia directa." "P3876–P3880; P3919–P3928"),
 (Technique "journey" "Journey analysis" "Entender objetivo, pasos, fricción, dependencia, abandono y momento de éxito." "Para journeys existentes o incertidumbre end-to-end." "Fricciones y Moments of Truth." "P3919–P3960"),
 (Technique "concept" "Sketch / Concept" "Validar comprensión conceptual antes de construir interacción completa." "Cuando una representación ligera puede responder la pregunta." "Reacción y comprensión conceptual." "P3993–P3996"),
 (Technique "prototype" "Interactive Prototype" "Validar experiencia, Outcome, fricción, reglas y autonomía mediante un flujo integrado." "Cuando existe incertidumbre de solución o experiencia." "Evidencia de cliente sobre capacidad de lograr el resultado." "P3997–P4000; P4038–P4085"),
 (Technique "technical-spike" "Technical Spike / Simulation" "Reducir incertidumbre técnica crítica." "Cuando existen dudas de factibilidad, arquitectura, integración u operación." "Factibilidad, constraints y riesgos técnicos." "P4001–P4003; P4238–P4248"),
 (Technique "concierge" "Concierge / Manual Test" "Probar el resultado sin automatizar completamente." "Cuando el resultado puede validarse manualmente con menor inversión." "Respuesta real sin software completo." "P4005–P4007"),
 (Technique "mvp" "MVP" "Obtener evidencia en condiciones reales con software mínimo." "Solo cuando niveles más económicos no resuelven la incertidumbre." "Comportamiento en condiciones reales." "P4009–P4011"),
 (Technique "ai-assisted" "AI-assisted synthesis / prototype" "Reducir Learning Lead Time acelerando síntesis, patrones, hipótesis, prototipos, reglas y edge cases." "Como acelerador; el cliente o datos continúan aportando la evidencia." "No genera validación por sí sola." "P4018–P4059")
)
$cadences=@(
 [ordered]@{name="Captura de señales";cadenceType="CONTINUOUS";purpose="Capturar señales durante la operación.";participants=@("fuentes operativas","Product");source=(Ref "P4183–P4186")},
 [ordered]@{name="Revisión de señales y oportunidades";cadenceType="SCHEDULED";purpose="Producto revisa nuevas señales y oportunidades activas semanalmente.";participants=@("Product");source=(Ref "P4187–P4188")},
 [ordered]@{name="Revisión de evidencia y prototipos";cadenceType="SCHEDULED";purpose="Revisar quincenalmente evidencia relevante y prototipos cuando existen.";participants=@("participantes según evidencia/incertidumbre");source=(Ref "P4189–P4190")},
 [ordered]@{name="Outcome Review";cadenceType="EVENT-DRIVEN";purpose="Los resultados posteriores alimentan nuevas oportunidades dentro del Operating Cadence.";source=(Ref "P4191–P4193")},
 [ordered]@{name="Discovery Decision Gate";cadenceType="GATE";purpose="Decidir cuando existe evidencia proporcional al riesgo; no al terminar una ceremonia o sprint.";participants=@("Product","participantes pertinentes");source=(Ref "P4087–P4121")}
)
$flow=@(
 [ordered]@{from="Signal";to="Opportunity";status="SUPPORTED CONNECTION";rationale="El Discovery Funnel convierte la señal en problema.";source=(Ref "P3683–P3690")},
 [ordered]@{from="Opportunity";to="Outcome";status="PARTIAL CONNECTION";rationale="La fuente intercala Evidence antes de definir Outcome.";source=(Ref "P3688–P3696")},
 [ordered]@{from="Outcome";to="Bet";status="PARTIAL CONNECTION";rationale="La fuente requiere Hypothesis, Validation y Decision antes de Delivery Bet.";source=(Ref "P3694–P3707")},
 [ordered]@{from="Bet";to="Delivery";status="PARTIAL CONNECTION";rationale="Delivery Bet representa el compromiso posterior a la decisión, pero la conexión no se define como relación de artefactos.";source=(Ref "P3703–P3707")},
 [ordered]@{from="Delivery";to="Evidence";status="PARTIAL CONNECTION";rationale="La evidencia post-release aparece después de Release/Adoption, no directamente después de Delivery.";source=(Ref "P4390–P4396")},
 [ordered]@{from="Evidence";to="Learning";status="SUPPORTED CONNECTION";rationale="La fuente conecta evidencia observada con Learn/New Learning.";source=(Ref "P4038–P4056; P4393–P4397")},
 [ordered]@{from="Learning";to="Decision";status="PARTIAL CONNECTION";rationale="El loop de prototipo produce Delivery decision; el loop post-release vuelve a comenzar sin explicitar un Decision Log.";source=(Ref "P4050–P4056; P4393–P4397")}
)
$artifactUses=@(
 [ordered]@{artifactId="signal";artifactName="Signal";relationship="READS";usage="Discovery recibe señales capturadas durante la operación y las convierte en problemas cuando corresponde.";source=(Ref "P3683–P3690; P4183–P4188");validationStatus="pending"},
 [ordered]@{artifactId="opportunity-card";artifactName="Opportunity Card";relationship="UPDATES";usage="Artefacto central por oportunidad: Problem, User/Segment, Evidence, Outcome, Success Signal, Key Assumptions, Validation y Decision.";source=(Ref "P4132–P4152");validationStatus="pending"},
 [ordered]@{artifactId="evidence-map";artifactName="Evidence Map";relationship="UPDATES";usage="Distingue KNOWN, ASSUMED y UNKNOWN y evoluciona a medida que se obtiene evidencia.";source=(Ref "P3849–P3862");validationStatus="pending"},
 [ordered]@{artifactId="source-discovery-board";artifactName="Discovery Board";relationship="SOURCE TERMINOLOGY CONFLICT";usage="Artefacto adicional de la fuente para representar aprendizaje y estados de oportunidades; no se incorpora automáticamente al catálogo canónico.";source=(Ref "P4154–P4169");validationStatus="pending"},
 [ordered]@{artifactId="source-product-discovery-canvas";artifactName="Product Discovery Canvas — SEIF";relationship="SOURCE TERMINOLOGY CONFLICT";usage="Vista fuente adicional que resume Discovery; requiere revisión antes de decidir si es vista o artefacto independiente.";source=(Ref "P4478–P4480");validationStatus="pending"}
)
$antiPatterns=@(
 [ordered]@{antiPattern="Discovery as a one-time phase";status="NOT PRESENT";rationale="La fuente niega Discovery waterfall y define actividad concurrente y continua.";source=(Ref "P3709–P3719; P4183–P4193")},
 [ordered]@{antiPattern="Discovery disconnected from Outcomes";status="NOT PRESENT";rationale="Outcome y Success Criteria son condiciones operativas del modelo.";source=(Ref "P3895–P3917")},
 [ordered]@{antiPattern="Discovery disconnected from evidence";status="NOT PRESENT";rationale="Evidence Map, jerarquía A–D y el Decision Gate exigen evidencia proporcional al riesgo.";source=(Ref "P3849–P3893; P4087–P4107")},
 [ordered]@{antiPattern="Discovery ending in feature specification";status="NOT PRESENT";rationale="La fuente comienza con Opportunity y termina en una decisión, no en una Feature specification.";source=(Ref "P3638–P3657; P4087–P4121")},
 [ordered]@{antiPattern="Mandatory research theatre";status="NOT PRESENT";rationale="Las técnicas son proporcionales al riesgo y Research Theater aparece como anti-patrón explícito.";source=(Ref "P3721–P3784; P4332–P4335")},
 [ordered]@{antiPattern="Handoff from Discovery team to Delivery team";status="NOT PRESENT";rationale="Discovery es multidisciplinario y puede operar concurrentemente con Delivery; la fuente no define un equipo separado de handoff.";source=(Ref "P3709–P3719; P3792–P3847")},
 [ordered]@{antiPattern="Output-based success";status="NOT PRESENT";rationale="Discovery Done depende de evidencia para decidir, no de entrevistas, pantallas, prototipo o documento terminados.";source=(Ref "P4345–P4352")},
 [ordered]@{antiPattern="Evidence collected but not used for decisions";status="NOT PRESENT";rationale="Research Theater y Data Theater se rechazan explícitamente; toda validación debe producir decisión.";source=(Ref "P4325–P4343; P4506–P4507")},
 [ordered]@{antiPattern="Customer feedback arriving only after release";status="SOURCE RISK";rationale="El assessment reconoce feedback tardío como riesgo actual; el TO-BE introduce validación antes de inversión y evidencia posterior.";source=(Ref "P3578–P3584; P4038–P4059")}
)
$roleCompleteness=Completeness @("WHAT","WHY","WHO") @("HOW","INPUT","OUTPUT","DECISION","ARTIFACT") @("WHEN","METRIC","TOOL","EXAMPLE")
function Role([string]$id,[string]$name,[string]$purpose,[string[]]$responsibilities,[string[]]$stages,[string]$locator){return [ordered]@{id=$id;sourceRole=$name;purpose=$purpose;responsibilities=$responsibilities;canonicalStages=$stages;mappingStatus="ROLE MAPPING PENDING";completeness=$roleCompleteness;sourceLocators=@((Ref $locator));clientValidationIds=@("CL-04")}}
$roles=@(
 (Role "head-producto" "Product — source wording" "Framing, Outcome, priorización y decisión de inversión." @("Framing","Outcome","priorización","decisión de inversión") @("DISCOVER","DECIDE") "P3792–P3799"),
 (Role "ux-ui" "UX/UI" "Entendimiento del usuario, journey, interacción, prototipado y validación de experiencia." @("Research","journey","prototipado","validación") @("DISCOVER") "P3800–P3806"),
 (Role "desarrollo" "Desarrollo" "Participa cuando existe incertidumbre técnica relevante." @("Factibilidad","arquitectura","integración","complejidad") @("DISCOVER","DELIVER") "P3807–P3812"),
 (Role "sre" "SRE" "Participa cuando existen implicaciones operacionales o de confiabilidad." @("Confiabilidad","operación","seguridad","observabilidad","escalabilidad","deuda") @("DISCOVER","DELIVER") "P3813–P3820"),
 (Role "customer-success" "Customer Success" "Aporta señales y contexto antes, facilita evidencia durante y aporta señales de adopción después del release." @("Adopción","implementación","comportamiento","criterios de éxito") @("DISCOVER","ADOPT","LEARN") "P3821–P3828; P4195–P4205"),
 (Role "soporte" "Soporte" "Aporta incidentes, fricciones, consultas y patrones repetitivos." @("Detectar patrones de tickets") @("DISCOVER") "P3829–P3834; P4207–P4224"),
 (Role "marketing" "Marketing" "Participa cuando la incertidumbre afecta segmento, mercado, posicionamiento o propuesta de valor." @("Señales de mercado","validación de relevancia comercial") @("DISCOVER") "P3835–P3841; P4226–P4236")
)
$operatingConcepts=@(
 [ordered]@{id="product-discovery-system";title="Product Discovery proporcional al riesgo";canonicalLayers=@("DISCOVER","EVIDENCE","DECIDE","LEARN");sourceChapters=@("12");sourceLocators=@((Ref "P3568–P4511"));contentClass="recommendation";completeness=(Completeness @("WHAT","WHY","HOW","WHO","WHEN","INPUT","OUTPUT","ARTIFACT","DECISION","METRIC","EXAMPLE") @("TOOL") @());gapIds=@("CL-04","CL-05","CL-07","CL-10","CL-11")},
 [ordered]@{id="discovery-evidence-quality";title="Evidence quality A–D";canonicalLayers=@("DISCOVER","EVIDENCE");sourceChapters=@("12");sourceLocators=@((Ref "P3849–P3893"));contentClass="recommendation";completeness=(Completeness @("WHAT","WHY","HOW","INPUT","OUTPUT","DECISION","EXAMPLE") @("WHO","WHEN","ARTIFACT","METRIC") @("TOOL"));gapIds=@()},
 [ordered]@{id="discovery-feedback-loop";title="Discovery feedback loop";canonicalLayers=@("DISCOVER","ADOPT","LEARN");sourceChapters=@("12");sourceLocators=@((Ref "P4038–P4059; P4183–P4193; P4393–P4397"));contentClass="recommendation";completeness=(Completeness @("WHAT","WHY","HOW","INPUT","OUTPUT","DECISION","EXAMPLE") @("WHO","WHEN","ARTIFACT","METRIC","TOOL") @());gapIds=@()}
)
$sourceSequence=@([ordered]@{title="SIGNAL";locator="P3590";relationship="SOURCE SUB-STAGE"},[ordered]@{title="FRAME";locator="P3590";relationship="SOURCE SUB-STAGE"},[ordered]@{title="DISCOVER";locator="P3592";relationship="SOURCE TERMINOLOGY"},[ordered]@{title="DECIDE";locator="P3590";relationship="SOURCE TERMINOLOGY"},[ordered]@{title="VALIDATE";locator="P3595";relationship="SOURCE SUB-STAGE"},[ordered]@{title="DELIVER";locator="P3590";relationship="SOURCE TERMINOLOGY"},[ordered]@{title="RELEASE";locator="P3590";relationship="SOURCE SUB-STAGE"},[ordered]@{title="ADOPT";locator="P3590";relationship="SOURCE TERMINOLOGY"},[ordered]@{title="MEASURE & LEARN";locator="P3590";relationship="SOURCE SUB-STAGE"})
$discoveryStage=@([ordered]@{canonicalStage="DISCOVER";sourceSubStages=@([ordered]@{title="SIGNAL";locator="P3590";relationship="SOURCE SUB-STAGE"},[ordered]@{title="FRAME";locator="P3590";relationship="SOURCE SUB-STAGE"},[ordered]@{title="DISCOVER";locator="P3592";relationship="SOURCE TERMINOLOGY"},[ordered]@{title="VALIDATE";locator="P3595";relationship="SOURCE SUB-STAGE"});purpose="Reducir incertidumbre del problema y de la hipótesis de solución antes de invertir capacidad significativa.";triggers=@("Signal u Opportunity relevante");inputs=@("Signal","Opportunity","evidencia disponible");steps=@("FRAME","DISCOVER","VALIDATE");outputs=@("PROCEED","ADJUST","EXPLORE MORE","STOP");source=(Ref "P3588–P3602; P4087–P4121")})
$metadata=[ordered]@{slug="discovery";group="Operating Model";title="Product Discovery";sourceTitle="12. Product Discovery Model";eyebrow="12 · Discover";summary="Discovery convierte señales y oportunidades en decisiones respaldadas por evidencia proporcional al riesgo antes de comprometer capacidad significativa de Delivery.";takeaway="Discovery no termina cuando existe un diseño: termina cuando SEIF puede decidir Proceed, Adjust, Explore More o Stop con evidencia proporcional al riesgo.";executive=[ordered]@{keyFindings=@("Discovery ya existe en SEIF; el cambio es hacerlo consistente y proporcional al riesgo.","Problem Discovery y Solution Validation son momentos distintos dentro del modelo fuente.","La Opportunity es la unidad de Discovery y la evidencia se separa de supuestos e hipótesis.","El éxito se mide por velocidad y costo de aprendizaje, no por volumen de entrevistas o prototipos.");implication="El capítulo propone un sistema de aprendizaje ejecutable. Roles, autoridad, métricas, WIP, cadencias y tooling conservan sus validaciones abiertas.";evidenceConfidence="medium";evidenceStatus="pending";primaryVisual="flow";sources=@((Ref ($chapter.start+"–"+$chapter.end)))};clientValidations=@((CV "CL-04" "Mapeo de Product y roles participantes"),(CV "CL-05" "Authority del Discovery Decision Gate"),(CV "CL-10" "Arquitectura futura de tooling para Discovery"));operatingConcepts=$operatingConcepts;operatingStages=$discoveryStage;sourceOperatingSequence=$sourceSequence;operatingRoles=$roles;discoveryConcepts=$concepts;discoveryFlowConnections=$flow;discoveryEvidenceModel=$evidenceModel;discoveryGates=$gates;discoveryTechniques=$techniques;discoveryCadences=$cadences;artifactUses=$artifactUses;antiPatternAssessments=$antiPatterns;sections=@($chapter.sections);related=@("design-principles","operating-model","roles","artifacts","prioritization","feedback-loop","value-stream");source=[ordered]@{title="12. Product Discovery Model";locator=($chapter.start+"–"+$chapter.end);note="Locators internos de párrafo OOXML; no se muestran por defecto."}}
$json=$metadata|ConvertTo-Json -Depth 100;$content="import type { Chapter } from `"@/types/content`";`r`n`r`nexport const chapter = $json satisfies Chapter;`r`n";[IO.File]::WriteAllText((Join-Path $repo 'content/chapters/12-discovery.ts'),$content,[Text.UTF8Encoding]::new($false))
Write-Output "Block B Wave 3 ingestion generated Chapter 12 from $Source."
