param([string]$Source="source-private/SEIF-master-v0.1.docx")
$ErrorActionPreference="Stop";$repo=Split-Path -Parent $PSScriptRoot;$sourcePath=Join-Path $repo $Source
if(-not(Test-Path -LiteralPath $sourcePath -PathType Leaf)){throw"SOURCE NOT FOUND"}
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($sourcePath)
try{$entry=$zip.GetEntry("word/document.xml");$reader=[IO.StreamReader]::new($entry.Open());try{[xml]$document=$reader.ReadToEnd()}finally{$reader.Dispose()}}finally{$zip.Dispose()}
$ns=[Xml.XmlNamespaceManager]::new($document.NameTable);$ns.AddNamespace("w","http://schemas.openxmlformats.org/wordprocessingml/2006/main");$body=$document.SelectSingleNode("//w:body",$ns)
function Text-Of($node){return (($node.SelectNodes(".//w:t",$ns)|ForEach-Object{$_.InnerText})-join"").Trim()}
function Max-Size($p){$s=@($p.SelectNodes(".//w:rPr/w:sz",$ns)|ForEach-Object{[int]$_.GetAttribute("val",$ns.LookupNamespace("w"))});if(!$s.Count){return 0};return ($s|Measure-Object -Maximum).Maximum}
function Slugify([string]$v){$n=$v.Normalize([Text.NormalizationForm]::FormD);$c=$n.ToCharArray()|Where-Object{[Globalization.CharUnicodeInfo]::GetUnicodeCategory($_)-ne[Globalization.UnicodeCategory]::NonSpacingMark};return ((-join$c).ToLowerInvariant()-replace"[^a-z0-9]+","-").Trim("-")}
function Ref([string]$locator){return [ordered]@{title="13. Decision & Prioritization Model";locator=$locator}}
function CV([string]$id,[string]$subject){return [ordered]@{id=$id;subject=$subject;status="CLIENT VALIDATION REQUIRED"}}
function Completeness([string[]]$complete,[string[]]$partial,[string[]]$missing){$v=[ordered]@{};foreach($k in $complete){$v[$k]="SOURCE COMPLETE"};foreach($k in $partial){$v[$k]="SOURCE PARTIAL"};foreach($k in $missing){$v[$k]="SOURCE MISSING"};return $v}
function Section-Class([string]$title){if($title-match'(?i)Maturity|North Star'){return "hypothesis"};if($title-match'(?i)assessment|AS-IS|Cambio esperado|Diagnóstico final'){return "mixed"};return "recommendation"}
function Validations-For([string]$title){$r=@();if($title-match'(?i)Decision Rights|Rol de liderazgo'){$r+=,(CV "CL-05" "Authority, accountability y participación en decisiones")};if($title-match'(?i)WIP|Active Outcomes'){$r+=,(CV "CL-09" "Límites numéricos de WIP y Outcomes activos")};if($title-match'(?i)Balance de inversión|deuda técnica'){$r+=,(CV "CL-12" "Política de capacidad y deuda técnica")};if($title-match'(?i)Decision Cadence|Opportunity Review|Governance'){$r+=,(CV "CL-11" "Cadencias de decisión, participantes y triggers")};if($title-match'(?i)Métricas|Decision Lead Time|Focus Ratio'){$r+=,(CV "CL-07" "Definiciones operacionales, baseline, target y ownership de métricas")};if($title-match'(?i)Integración con Jira|Estados recomendados'){$r+=,(CV "CL-10" "Arquitectura futura de tooling para DECIDE")};if($title-match'(?i)North Star'){$r+=,(CV "CL-06" "North Star candidate como señal de priorización")};if($title-match'(?i)Growth'){$r+=,(CV "CL-13" "Ownership de Growth y Expansion")};return $r}

$chapter=[ordered]@{sections=@();start=$null;end=$null};$current=0;$expected=1;$pi=0;$ti=0;$section=$null;$pending=@();$pendingStart=$null;$pendingEnd=$null
function Flush-List{if($null-ne$script:section-and$script:pending.Count){$script:section.blocks+=[ordered]@{type="list";items=@($script:pending);source=(Ref "P$script:pendingStart–P$script:pendingEnd")}};$script:pending=@();$script:pendingStart=$null;$script:pendingEnd=$null}
foreach($node in $body.ChildNodes){if($node.LocalName-eq"p"){$pi++;$text=Text-Of $node;if($expected-le14-and$text-match("^"+$expected+"\.\s+")-and(Max-Size $node)-ge36){Flush-List;$current=$expected;$expected++;if($current-eq13){$chapter.start="P$pi";$section=$null;continue};if($current-eq14){$chapter.end="P$($pi-1)";break}};if($current-ne13){continue};$chapter.end="P$pi";if(!$text){Flush-List;continue};if($text-match'^13\.\d+\s+'){Flush-List;$title=($text-replace'^13\.\d+\s+','').Trim();$section=[ordered]@{id=(Slugify $title);title=$title;contentClass=(Section-Class $title);blocks=@();evidence=@();sources=@((Ref "P$pi"))};$v=Validations-For $title;if($v.Count){$section.clientValidations=@($v)};$chapter.sections+=$section;continue};if($null-eq$section){continue};$isList=$null-ne$node.SelectSingleNode("./w:pPr/w:numPr",$ns);if($isList){if(!$pending.Count){$pendingStart=$pi};$pendingEnd=$pi;$pending+=$text}else{Flush-List;$section.blocks+=[ordered]@{type="paragraph";text=$text;source=(Ref "P$pi")}}}elseif($node.LocalName-eq"tbl"){$ti++;if($current-ne13){continue};Flush-List;$rows=@();foreach($row in $node.SelectNodes("./w:tr",$ns)){$rows+=,@($row.SelectNodes("./w:tc",$ns)|ForEach-Object{Text-Of $_})};if($rows.Count-and$null-ne$section){$headers=@($rows[0]);$data=if($rows.Count-gt1){@($rows[1..($rows.Count-1)])}else{@()};$kind=if(($headers-join" ")-match'(?i)Dimensión|Decisión|Nivel|Opportunity'){"comparison"}elseif(($headers-join" ")-match'(?i)Métrica'){"scorecard"}else{"simple"};$section.blocks+=[ordered]@{type="table";table=[ordered]@{id=("source-table-{0:D3}"-f$ti);caption=$section.title;kind=$kind;headers=$headers;rows=$data;source=(Ref "T$ti")}}}}};Flush-List

$semantic=@(
 [ordered]@{term="ASSESSMENT";definition="Diagnóstico que evidencia criterios distribuidos y falta de lógica común trazable; no es la priorización misma.";sourceStatus="SOURCE PARTIAL";source=(Ref "P4513–P4525")},
 [ordered]@{term="PRIORITIZATION";definition="Decisión razonada sobre qué problema u Opportunity merece capacidad ahora, considerando Outcome, Evidence, Reach, Value y Feasibility.";sourceStatus="SOURCE COMPLETE";source=(Ref "P4527–P4577; P5261–P5287")},
 [ordered]@{term="RANKING";definition="Ordenar una lista no completa la priorización; la fuente rechaza que el número más alto produzca automáticamente prioridad.";sourceStatus="SOURCE PARTIAL";source=(Ref "P4731–P4742; P4886–P4898")},
 [ordered]@{term="SEQUENCING";definition="NOW, NEXT y LATER organizan horizontes sin convertirlos en promesas detalladas.";sourceStatus="SOURCE PARTIAL";source=(Ref "P4911–P4919")},
 [ordered]@{term="DECISION";definition="Salida explícita sobre una Opportunity: EXPLORE, PRIORITIZE, WAIT o DISCARD.";sourceStatus="SOURCE COMPLETE";source=(Ref "P4560–P4572")},
 [ordered]@{term="COMMITMENT";definition="Inicio posterior a la prioridad cuando existe capacidad; una Opportunity priorizada puede permanecer Not Started.";sourceStatus="SOURCE COMPLETE";source=(Ref "P4886–P4898; P5248–P5254")},
 [ordered]@{term="CAPACITY ALLOCATION";definition="Visibilidad y balance de capacidad comprometida por Outcome y Run/Grow/Transform; no se fijan porcentajes sin baseline.";sourceStatus="SOURCE PARTIAL";source=(Ref "P4766–P4788")},
 [ordered]@{term="FUNDING / INVESTMENT";definition="La fuente habla de decisión de inversión y compromiso financiero significativo, pero no define un mecanismo de funding separado.";sourceStatus="SOURCE PARTIAL";source=(Ref "P4513–P4514; P4755–P4763")},
 [ordered]@{term="BACKLOG ORDERING";definition="El backlog no es la unidad de decisión; guardar u ordenar oportunidades sin decisión explícita aparece como anti-patrón.";sourceStatus="SOURCE PARTIAL";source=(Ref "P4540–P4558; P4981–P4996")}
)
$decideComplete=Completeness @("WHAT","WHY","INPUT","OUTPUT","DECISION","DECISION CRITERIA","TRADE-OFF","CAPACITY CONSTRAINT","REVISIT CONDITION","DECISION RECORD") @("HOW","WHO","WHEN","ARTIFACT","METRIC","EXAMPLE") @("TOOL")
function DC([string]$id,[string]$kind,[string]$title,[string]$what,[string]$why,[string]$locator,[string[]]$criteria,[string[]]$outputs,[string]$trigger="",[string[]]$inputs=@(),[string[]]$participants=@(),[string]$owner="",[string]$artifact="",[string]$metric="",[string]$cadence=""){
 $value=[ordered]@{id=$id;kind=$kind;title=$title;what=$what;why=$why;trigger=$trigger;inputs=$inputs;criteria=$criteria;participants=$participants;decisionOwner=$owner;outputs=$outputs;metric=$metric;cadence=$cadence;sourceLocators=@((Ref $locator));contentClass="recommendation";completeness=$decideComplete}
 if($artifact){$value.artifacts=[string[]]@($artifact)}
 return $value
}
$concepts=@(
 (DC "decision-trigger" "DECISION TRIGGER" "Opportunity suficientemente entendida" "La Opportunity llega a decisión después de señal, framing y Discovery Evidence." "Evita convertir solicitudes directamente en trabajo comprometido." "P4513–P4558" @("Opportunity estructurada","Discovery Evidence") @("EXPLORE","PRIORITIZE","WAIT","DISCARD") "Opportunity lista para decisión" @("Opportunity","Discovery Evidence")),
 (DC "decision-object" "DECISION OBJECT" "Opportunities / Bets" "La fuente prioriza Opportunities / Bets, no tareas ni tickets." "Mantiene la decisión en el nivel de problema e inversión." "P4540–P4558" @("Outcome","Evidence","Reach","Value","Feasibility") @("estado decisional","Bet seleccionada")),
 (DC "evidence-package" "EVIDENCE PACKAGE" "Decision Canvas" "Vista de Opportunity, Outcome, Evidence, Reach, Value, Feasibility, riesgos, decisión y rationale." "Integra criterios distribuidos en una conversación trazable." "P4709–P4729" @("Outcome","Evidence","Reach","Value","Feasibility","Key Risks") @("Decision","Rationale") "Opportunity llega a decisión" @("Opportunity Card","Discovery Evidence") @() "" "Decision Canvas"),
 (DC "decision-criteria" "DECISION CRITERIA" "Cinco dimensiones" "Outcome + Evidence + Reach + Value + Feasibility." "Hace comparable la conversación sin algoritmo rígido." "P4527–P4538; P4574–P4707" @("Outcome","Evidence","Reach","Value","Feasibility") @("evaluación trazable")),
 (DC "evaluation" "EVALUATION" "Escala simple" "Las dimensiones pueden evaluarse Alta/Media/Baja o 1/2/3." "Aporta consistencia sin falsa precisión." "P4731–P4742" @("cinco dimensiones") @("conversación estructurada") "Comparar oportunidades"),
 (DC "prioritization" "PRIORITIZATION" "Priorizar problemas y Opportunities" "Seleccionar qué problema merece capacidad ahora y por qué." "Protege foco y conecta inversión con Outcomes." "P4560–P4572; P5261–P5287" @("Outcome","Evidence","Reach","Value","Feasibility","Strategic Fit","Urgency contextual") @("EXPLORE","PRIORITIZE","WAIT","DISCARD")),
 (DC "trade-off" "TRADE-OFF" "Trade-off explícito" "Cada decisión y repriorización muestra qué entra, qué sale, Outcome afectado y costo de cambio." "Hace visible el costo de cambiar prioridades." "P4779–P4788; P4869–P4884; P5016–P5031" @("capacidad","Outcomes","costo de cambio") @("trade-off registrado")),
 (DC "capacity" "CAPACITY CONSTRAINT" "Priority ≠ Start Decision" "La capacidad disponible condiciona el inicio; no toda Opportunity priorizada comienza inmediatamente." "Evita confundir importancia con trabajo comprometido." "P4886–P4909" @("WIP","Active Outcomes","capacidad comprometida") @("PRIORITIZED / NOT STARTED","Start Decision") "Opportunity priorizada"),
 (DC "decision" "DECISION" "Explore / Prioritize / Wait / Discard" "Toda Opportunity recibe un estado decisional explícito." "Evita backlog indefinido y convierte evidencia en acción." "P4560–P4572" @("cinco dimensiones y evidencia") @("EXPLORE","PRIORITIZE","WAIT","DISCARD") "Opportunity Review" @() @("Producto","consultados según T34") "Producto — fuente; autoridad organizacional pendiente" "Decision Log" "Decision Lead Time"),
 (DC "commitment" "COMMITMENT" "Capacity Commitment" "Después de priorizar y seleccionar una Bet, se compromete capacidad antes de Delivery." "Separa decisión de valor de inicio real." "P4886–P4898; P5248–P5254" @("prioridad","capacidad disponible","trade-offs") @("BET","CAPACITY COMMITMENT","DELIVERY")),
 (DC "revisit" "REVISIT" "Reprioritization y Review Trigger" "Nueva evidencia puede desplazar, ajustar o detener iniciativas haciendo visible el costo." "Mantiene adaptabilidad sin destruir foco." "P4869–P4884; P5016–P5031; P5254–P5258" @("nueva evidencia","riesgo","cambio estratégico","restricción") @("repriorizar","ajustar","detener","mantener")),
 (DC "stop-defer" "STOP / DEFER" "WAIT, DISCARD y Kill Criteria" "Diferir o detener es una decisión válida basada en evidencia y aprendizaje." "Protege capacidad frente a inversión no justificada." "P4560–P4572; P5002–P5014" @("valor","evidencia","alineación","costo","resultado observado") @("WAIT","DISCARD","STOP"))
)
$objects=@(
 [ordered]@{sourceTerm="Opportunity";objectType="problema u oportunidad estructurada";decisionApplied=@("EXPLORE","PRIORITIZE","WAIT","DISCARD");artifactRelationship="Opportunity Card — INPUT TO DECISION";source=(Ref "P4540–P4572");validationStatus="pending"},
 [ordered]@{sourceTerm="Bet";objectType="inversión seleccionada para modificar un Outcome";decisionApplied=@("seleccionar","comprometer capacidad","continuar/ajustar/detener");artifactRelationship="Bet source term; Bet Card relationship PARTIAL";source=(Ref "P4543–P4557; P5248–P5258");validationStatus="pending"},
 [ordered]@{sourceTerm="Technical Debt";objectType="riesgo/capacidad técnica con impacto";decisionApplied=@("comparar con evolución funcional","priorizar según riesgo, impacto, consecuencia, urgencia y factibilidad");artifactRelationship="No artifact name specified";source=(Ref "P4790–P4803");validationStatus="pending"},
 [ordered]@{sourceTerm="Ticket / Bug Pattern";objectType="patrón que puede convertirse en Opportunity";decisionApplied=@("gestionar por criticidad","convertir patrón relevante en Opportunity");artifactRelationship="Signal/Opportunity — PARTIAL";source=(Ref "P4805–P4826");validationStatus="pending"},
 [ordered]@{sourceTerm="Customer Request";objectType="señal que requiere evaluación del problema subyacente";decisionApplied=@("evaluar Evidence, Reach y Value","decidir") ;artifactRelationship="Signal/Opportunity — PARTIAL";source=(Ref "P4828–P4844");validationStatus="pending"},
 [ordered]@{sourceTerm="Growth Opportunity";objectType="Opportunity derivada de Marketing, CS o analytics";decisionApplied=@("Discovery","seleccionar intervención después") ;artifactRelationship="Opportunity / Bet — PARTIAL";source=(Ref "P5069–P5092");validationStatus="pending"},
 [ordered]@{sourceTerm="Capacity";objectType="capacidad organizacional comprometida";decisionApplied=@("balance Run/Grow/Transform","Start Decision","Capacity Commitment");artifactRelationship="Outcome Board not explicitly named";source=(Ref "P4766–P4788; P4886–P4909");validationStatus="pending"}
)
$methods=@(
 [ordered]@{name="Five-dimension conversation";methodClass="SOURCE RECOMMENDATION";criteria=@("Outcome","Evidence","Reach","Value","Feasibility");purpose="Hacer comparable la conversación.";caveat="No es algoritmo rígido.";source=(Ref "P4527–P4538; P4574–P4707");validationStatus="pending"},
 [ordered]@{name="Simple evaluation scale";methodClass="SOURCE RECOMMENDATION";scale=@("Alta / Media / Baja","1 / 2 / 3");purpose="Evaluar dimensiones con consistencia inicial.";caveat="Sin pesos, fórmula, normalización ni thresholds; el número no decide.";source=(Ref "P4731–P4742");validationStatus="pending"},
 [ordered]@{name="Initial decision matrix";methodClass="EXAMPLE";criteria=@("Outcome","Evidence","Reach","Value","Feasibility");purpose="Mostrar una vista simplificada de conversaciones posibles.";caveat="T33 es ejemplo; no sustituye juicio ni constituye política.";source=(Ref "T33");validationStatus="pending"},
 [ordered]@{name="Light scorecard";methodClass="H1 / PROPOSED";criteria=@("Outcome relevance","Evidence","Reach","Value","Feasibility");scale=@("Baja","Media","Alta");purpose="Comparar varias Opportunities mediante conversación estructurada.";caveat="No produce automáticamente la decisión.";source=(Ref "P5165–P5168; T36");validationStatus="pending"},
 [ordered]@{name="Strategic Fit";methodClass="SOURCE RECOMMENDATION";criteria=@("objetivos vigentes","Outcome prioritario");purpose="Comprobar pertenencia a la dirección que SEIF busca fortalecer.";caveat="No agrega una capa de scoring.";source=(Ref "P4846–P4850");validationStatus="pending"},
 [ordered]@{name="Urgency context";methodClass="SOURCE RECOMMENDATION";criteria=@("Real Urgency","Perceived Urgency");purpose="Hacer explícita la razón de urgencia sin reemplazar Value.";source=(Ref "P4852–P4867");validationStatus="pending"},
 [ordered]@{name="Run / Grow / Transform visibility";methodClass="SOURCE RECOMMENDATION";criteria=@("Run","Grow","Transform");purpose="Mostrar dónde se consume capacidad.";caveat="Sin porcentajes ni cuotas por falta de baseline.";source=(Ref "P4766–P4788");validationStatus="pending"}
)
$priorityCommitment=[ordered]@{priorityDefinition="Opportunity cuya evidencia y valor potencial justifican comprometer capacidad, pero que aún puede quedar Not Started.";executionApprovalDefinition="Start Decision posterior a Priority y condicionado por capacidad disponible.";capacityCommitmentDefinition="Capacidad asignada a una Bet antes de Delivery; NOW representa capacidad comprometida.";distinctionStatus="SUPPORTED";source=(Ref "P4565–P4566; P4886–P4898; P4911–P4918; P5248–P5254")}
$rightsData=@(@("signal-opportunity","Convertir señal en oportunidad","Producto",@("Fuente de la señal")),@("need-discovery","Determinar necesidad de Discovery","Producto",@("UX","área relevante")),@("define-outcome","Definir Outcome","Producto",@("Célula")),@("evaluate-evidence","Evaluar evidencia","Producto",@("UX","CS","Soporte","Marketing","Data")),@("evaluate-feasibility","Evaluar factibilidad","Desarrollo",@("SRE cuando aplique")),@("evaluate-technical-risk","Evaluar riesgo técnico","SRE",@("Desarrollo","Producto")),@("prioritize","Priorizar","Producto",@("Tech","liderazgo según impacto")),@("commit-capacity","Comprometer capacidad","Liderazgo técnico / Desarrollo",@("Producto")),@("reprioritize","Repriorizar","Producto",@("Célula","liderazgo según impacto")),@("stop-initiative","Detener iniciativa","Producto",@("Célula","stakeholders relevantes")))
$rights=@();foreach($r in $rightsData){$rights+=[ordered]@{id=$r[0];decision=$r[1];stage="DECIDE";decisionOwner=$r[2];participants=$r[3];source=(Ref "T34");validationStatus="pending"}}
$artifactUses=@(
 [ordered]@{artifactId="opportunity-card";artifactName="Opportunity Card";relationship="INPUT TO DECISION";usage="Estructura común para Opportunity y entrada al sistema de priorización.";source=(Ref "P4709–P4729; P5110–P5117");validationStatus="pending"},
 [ordered]@{artifactId="decision-log";artifactName="Decision Log";relationship="RECORD OF DECISION";usage="Registra Decision, Date, Evidence, Rationale, Trade-off y Review Trigger.";source=(Ref "P5016–P5031");validationStatus="pending"},
 [ordered]@{artifactId="source-decision-canvas";artifactName="Decision Canvas";relationship="SOURCE TERMINOLOGY CONFLICT";usage="Artefacto mínimo de decisión fuente; debe revisarse frente a Opportunity Card y Decision Log para evitar duplicación.";source=(Ref "P4709–P4729");validationStatus="pending"},
 [ordered]@{artifactId="bet-card";artifactName="Bet source term / Bet Card";relationship="OUTPUT OF DECISION";usage="La fuente produce una Bet después de PRIORITIZE, pero no nombra Bet Card en este capítulo.";source=(Ref "P4543–P4557; P5248–P5254");validationStatus="pending"}
)
$connections=@(
 [ordered]@{element="Evidence readiness";status="SUPPORTED";rationale="Discovery Evidence precede Decision y Evidence es dimensión explícita.";source=(Ref "P4546–P4555; P4603–P4629")},
 [ordered]@{element="Hypothesis status";status="PARTIAL";rationale="Bet se define como inversión seleccionada, pero Chapter 13 no exige un estado formal de hipótesis de Chapter 12.";source=(Ref "P4543–P4557")},
 [ordered]@{element="Opportunity framing";status="SUPPORTED";rationale="La unidad llega identificada y suficientemente entendida; Decision Canvas empieza por Opportunity.";source=(Ref "P4513–P4514; P4709–P4716")},
 [ordered]@{element="Outcome relationship";status="SUPPORTED";rationale="Outcome es primera dimensión y parte del Decision Canvas.";source=(Ref "P4579–P4601; P4711–P4716")},
 [ordered]@{element="Decision trigger";status="PARTIAL";rationale="La fuente indica Opportunity suficientemente formulada y Ready for Decision, sin formalizar un handoff organizacional.";source=(Ref "P4513–P4514; P5147–P5162")},
 [ordered]@{element="Decision criteria";status="SUPPORTED";rationale="Outcome, Evidence, Reach, Value y Feasibility están definidos como dimensiones comunes.";source=(Ref "P4527–P4538; P4574–P4707")}
)
$record=[ordered]@{artifactName="Decision Log";fields=[ordered]@{"DECISION"="SOURCE COMPLETE";"DATE / CADENCE"="SOURCE COMPLETE";"INPUTS"="SOURCE PARTIAL";"EVIDENCE"="SOURCE COMPLETE";"PARTICIPANTS"="SOURCE MISSING";"DECISION OWNER"="SOURCE MISSING";"RATIONALE"="SOURCE COMPLETE";"TRADE-OFF"="SOURCE COMPLETE";"RESULT"="SOURCE PARTIAL";"REVISIT CONDITION"="SOURCE COMPLETE"};sourceFields=@("Decision","Date","Evidence","Rationale","Trade-off","Review Trigger");source=(Ref "P5016–P5031")}
$cadences=@(
 [ordered]@{name="Weekly Flow Review";cadenceType="MEETING CADENCE";purpose="Observar Outcomes activos, bloqueos, cambios críticos, WIP y decisiones pendientes.";decisions=@("desbloquear","visibilizar cambios y decisiones pendientes");source=(Ref "P4940–P4949");validationStatus="pending"},
 [ordered]@{name="Biweekly Opportunity Review";cadenceType="MEETING CADENCE";purpose="Revisar Opportunities, Discovery y Evidence.";decisions=@("EXPLORE","PRIORITIZE","WAIT","DISCARD");source=(Ref "P4950–P4955");validationStatus="pending"},
 [ordered]@{name="Monthly Outcome Review";cadenceType="MEETING CADENCE";purpose="Revisar Outcomes y aprendizaje.";decisions=@("continuar","escalar","ajustar","detener","repriorizar");source=(Ref "P4956–P4962");validationStatus="pending"},
 [ordered]@{name="Quarterly Direction Review";cadenceType="MEETING CADENCE";purpose="Revisar trade-offs estratégicos y balance de inversión.";decisions=@("balance de inversión","trade-offs estratégicos");source=(Ref "P4963–P4964");validationStatus="pending"},
 [ordered]@{name="Fast Track operacional";cadenceType="EVENT-DRIVEN";purpose="Responder primero a incidentes o riesgos críticos sin esperar el ciclo completo.";decisions=@("CONTAIN","RESTORE","PROTECT","después LEARN / ROOT CAUSE / OPPORTUNITY");source=(Ref "P5094–P5108");validationStatus="pending"}
)
function Metric([string]$name,[string]$class,[string]$definition,[string]$locator){return [ordered]@{name=$name;metricClass=$class;definition=$definition;baseline="SOURCE MISSING";target="SOURCE MISSING";source=(Ref $locator);validationStatus="pending"}}
$metrics=@((Metric "Opportunity → Decision Time" "FLOW" "Velocidad para decidir; Chapter 13 define Decision Lead Time desde Opportunity suficientemente formulada hasta decisión explícita." "T35; P5038–P5047"),(Metric "% Opportunities with explicit Outcome" "VALUE" "Calidad de alineación con Outcome." "T35"),(Metric "% Decisions with Evidence" "LEARNING" "Disciplina de decisión basada en evidencia." "T35"),(Metric "Active Outcomes" "FLOW" "Nivel de foco." "T35"),(Metric "Priority Changes per period" "RISK" "Estabilidad de prioridades." "T35"),(Metric "Started vs Finished Bets" "FLOW" "Disciplina de WIP." "T35"),(Metric "Stop / Wait Rate" "LEARNING" "Capacidad de decir no o todavía no." "T35"),(Metric "Outcome Success Rate" "VALUE" "Calidad de apuestas." "T35"),(Metric "Time to Reprioritize after new evidence" "LEARNING" "Capacidad adaptativa ante nueva evidencia." "T35"),(Metric "Focus Ratio" "EFFORT" "Proporción de capacidad dedicada a Outcomes priorizados frente a trabajo no asociado o emergente." "P5049–P5053"))
$anti=@(
 [ordered]@{antiPattern="Everything is priority";status="SOURCE RISK";rationale="Aparece como anti-patrón explícito y el assessment identifica múltiples fuentes de demanda.";source=(Ref "P4515–P4522; P4991–P4992")},
 [ordered]@{antiPattern="Priority without capacity";status="SOURCE RISK";rationale="La fuente corrige el riesgo separando Priority de Start Decision y haciendo visible capacidad comprometida.";source=(Ref "P4779–P4788; P4886–P4909")},
 [ordered]@{antiPattern="Scoring theatre";status="NOT PRESENT";rationale="Score Worship se rechaza y el scorecard solo estructura conversación.";source=(Ref "P4731–P4742; P4995–P4996; P5165–P5168")},
 [ordered]@{antiPattern="False precision";status="NOT PRESENT";rationale="La fuente evita puntuación sofisticada, pesos y algoritmo rígido.";source=(Ref "P4574–P4577; P4731–P4742")},
 [ordered]@{antiPattern="Backlog ranking presented as strategy";status="SOURCE RISK";rationale="Backlog Accumulation aparece como anti-patrón y priorizar no termina al ordenar una lista.";source=(Ref "P4886–P4898; P4993–P4994")},
 [ordered]@{antiPattern="HiPPO decision making";status="SOURCE RISK";rationale="Executive Override by Default y presión jerárquica se identifican como riesgos.";source=(Ref "P4852–P4867; P4983–P4988")},
 [ordered]@{antiPattern="Committee consensus without owner";status="NOT PRESENT";rationale="La fuente rechaza comité permanente y define accountability en T34, pendiente de validación organizacional.";source=(Ref "P4749–P4764; T34")},
 [ordered]@{antiPattern="Discovery evidence ignored";status="NOT PRESENT";rationale="Discovery Evidence precede Decision y Evidence es dimensión explícita.";source=(Ref "P4546–P4555; P4603–P4629")},
 [ordered]@{antiPattern="Feature priority disconnected from Outcome";status="NOT PRESENT";rationale="La unidad es Opportunity/Bet y Outcome es primera dimensión.";source=(Ref "P4540–P4558; P4579–P4601")},
 [ordered]@{antiPattern="Decision without recorded rationale";status="SOURCE RISK";rationale="La falta de lógica trazable es hallazgo del assessment; Decision Canvas y Log son tratamiento TO-BE.";source=(Ref "P4515–P4525; P4709–P4729; P5016–P5031")},
 [ordered]@{antiPattern="Decision never revisited";status="NOT PRESENT";rationale="Reprioritization Rules, Kill Criteria y Review Trigger soportan revisión.";source=(Ref "P4869–P4884; P5002–P5031")},
 [ordered]@{antiPattern="Annual planning disguised as agility";status="OPERATING MODEL RISK";rationale="La fuente usa horizontes y cadencias, pero no distingue explícitamente decisiones continuas de un ciclo anual de planificación.";source=(Ref "P4911–P4964")},
 [ordered]@{antiPattern="Output commitment before evidence";status="SOURCE RISK";rationale="El modelo responde al antecedente de solicitud→construcción y exige Evidence antes de Decision/Bet.";source=(Ref "P4546–P4558; P5170–P5197")}
)
$operatingConcepts=@([ordered]@{id="decide-system";title="DECIDE — decisión de inversión trazable";canonicalLayers=@("DECIDE","GOVERNANCE","ROLES","EVIDENCE","METRICS");sourceChapters=@("13");sourceLocators=@((Ref "P4512–P5296"));contentClass="recommendation";completeness=(Completeness @("WHAT","WHY","HOW","WHO","WHEN","INPUT","OUTPUT","ARTIFACT","DECISION","METRIC","EXAMPLE") @("TOOL") @());gapIds=@("CL-05","CL-07","CL-09","CL-10","CL-11","CL-12")})
$metadata=[ordered]@{slug="prioritization";group="Operating Model";title="DECIDE: priorización y decisiones de inversión";sourceTitle="13. Decision & Prioritization Model";eyebrow="13 · Decide";summary="DECIDE integra evidencia, criterios, trade-offs y capacidad para convertir Opportunities en decisiones explícitas sin confundir prioridad con compromiso de ejecución.";takeaway="Una Opportunity priorizada no está automáticamente aprobada para iniciar: Priority, Start Decision y Capacity Commitment son decisiones distintas.";executive=[ordered]@{keyFindings=@("La unidad fuente de decisión es Opportunity / Bet, no tarea, ticket o solicitud.","Outcome, Evidence, Reach, Value y Feasibility estructuran la conversación sin algoritmo rígido.","EXPLORE, PRIORITIZE, WAIT y DISCARD evitan un backlog sin estado decisional.","Priority se separa explícitamente de Start Decision y Capacity Commitment.");implication="El modelo propone disciplina de inversión y foco. Authority, scoring, WIP, capacidad, métricas, cadencias y tooling permanecen pendientes de validación.";evidenceConfidence="medium";evidenceStatus="pending";primaryVisual="flow";sources=@((Ref ($chapter.start+"–"+$chapter.end)))};clientValidations=@((CV "CL-05" "Authority y accountability de decisiones"),(CV "CL-09" "Límites de WIP y Outcomes activos"),(CV "CL-12" "Política de capacidad, balance y deuda"),(CV "CL-10" "Arquitectura futura de tooling"));operatingConcepts=$operatingConcepts;decisionSemantics=$semantic;decideConcepts=$concepts;decisionObjects=$objects;prioritizationMethods=$methods;priorityCommitment=$priorityCommitment;decisionRights=$rights;artifactUses=$artifactUses;discoveryDecideConnections=$connections;decisionRecord=$record;decisionCadences=$cadences;decisionMetrics=$metrics;antiPatternAssessments=$anti;sections=@($chapter.sections);related=@("value-stream","design-principles","operating-model","discovery","roles","artifacts","delivery","north-star","governance");source=[ordered]@{title="13. Decision & Prioritization Model";locator=($chapter.start+"–"+$chapter.end);note="Locators internos de párrafo OOXML; no se muestran por defecto."}}
$json=$metadata|ConvertTo-Json -Depth 100;$content="import type { Chapter } from `"@/types/content`";`r`n`r`nexport const chapter = $json satisfies Chapter;`r`n";[IO.File]::WriteAllText((Join-Path $repo 'content/chapters/13-prioritization.ts'),$content,[Text.UTF8Encoding]::new($false))
Write-Output "Block B Wave 4 ingestion generated Chapter 13 from $Source."
