param([string]$Source="source-private/SEIF-master-v0.1.docx")
$ErrorActionPreference="Stop";$repo=Split-Path -Parent $PSScriptRoot;$sourcePath=Join-Path $repo $Source
if(-not(Test-Path -LiteralPath $sourcePath -PathType Leaf)){throw "SOURCE NOT FOUND"}
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($sourcePath)
try{$entry=$zip.GetEntry("word/document.xml");$reader=[IO.StreamReader]::new($entry.Open());try{[xml]$document=$reader.ReadToEnd()}finally{$reader.Dispose()}}finally{$zip.Dispose()}
$ns=[Xml.XmlNamespaceManager]::new($document.NameTable);$ns.AddNamespace("w","http://schemas.openxmlformats.org/wordprocessingml/2006/main");$body=$document.SelectSingleNode("//w:body",$ns)
function Text-Of($node){return (($node.SelectNodes(".//w:t",$ns)|ForEach-Object{$_.InnerText})-join"").Trim()}
function Max-Size($p){$s=@($p.SelectNodes(".//w:rPr/w:sz",$ns)|ForEach-Object{[int]$_.GetAttribute("val",$ns.LookupNamespace("w"))});if(!$s.Count){return 0};return ($s|Measure-Object -Maximum).Maximum}
function Slugify([string]$v){$n=$v.Normalize([Text.NormalizationForm]::FormD);$c=$n.ToCharArray()|Where-Object{[Globalization.CharUnicodeInfo]::GetUnicodeCategory($_)-ne[Globalization.UnicodeCategory]::NonSpacingMark};return ((-join$c).ToLowerInvariant()-replace"[^a-z0-9]+","-").Trim("-")}
function Ref([int]$chapter,[string]$locator){$title=if($chapter-eq15){"15. Adoption & Growth Model"}else{"16. Feedback & Learning Loop"};return [ordered]@{title=$title;locator=$locator}}
function CV([string]$id,[string]$subject){return [ordered]@{id=$id;subject=$subject;status="CLIENT VALIDATION REQUIRED"}}
function Complete([string[]]$complete,[string[]]$partial,[string[]]$missing){$v=[ordered]@{};foreach($k in $complete){$v[$k]="SOURCE COMPLETE"};foreach($k in $partial){$v[$k]="SOURCE PARTIAL"};foreach($k in $missing){$v[$k]="SOURCE MISSING"};return $v}
function Section-Class([string]$title){if($title-match'(?i)North Star|Churn Risk|IA|AI Feedback Agent|Maturity'){return "hypothesis"};if($title-match'(?i)assessment|AS-IS|Cambio fundamental|Diagnóstico final'){return "mixed"};return "recommendation"}
function Validations-For([int]$chapter,[string]$title){$r=@();if($title-match'(?i)Role|Customer Success|Support|Marketing|SRE|Producto'){$r+=,(CV "CL-04" "Mapeo organizacional de roles de Adoption y Learning")};if($title-match'(?i)Decision|Outcome Review|Roles dentro'){$r+=,(CV "CL-05" "Authority y accountability de decisiones basadas en aprendizaje")};if($title-match'(?i)Métrica|Dashboard|Health|Correlation|Churn'){$r+=,(CV "CL-07" "Definiciones operacionales, baseline, targets y ownership de métricas")};if($title-match'(?i)TTV|Activation|Adoption|Adherence'){$r+=,(CV "CL-08" "Definiciones operacionales de Activation, TTV, Adoption y Adherence")};if($title-match'(?i)Jira|JSM|Confluence|Tooling|IA|AI|Automatización'){$r+=,(CV "CL-10" "Arquitectura futura de tooling")};if($title-match'(?i)Cadencia|Review|Learning Window|Review Trigger'){$r+=,(CV "CL-11" "Cadencias, ventanas y triggers de revisión")};if($title-match'(?i)Growth|Expansion|Retention'){$r+=,(CV "CL-13" "Ownership y causalidad de Growth / Expansion")};if($title-match'(?i)North Star'){$r+=,(CV "CL-06" "North Star candidate")};if($title-match'(?i)Maturity|madurez'){$id=if($chapter-eq15){"CL-15"}else{"CL-16"};$r+=,(CV $id "Valoración del assessment — madurez pendiente de validación")};return $r}
function Extract-Chapter([int]$target,[int]$next){$result=[ordered]@{sections=@();start=$null;end=$null};$current=0;$expected=1;$pi=0;$ti=0;$script:section=$null;$script:pending=@();$script:pendingStart=$null;$script:pendingEnd=$null
 function Flush{if($null-ne$script:section-and$script:pending.Count){$script:section.blocks+=[ordered]@{type="list";items=@($script:pending);source=(Ref $target "P$script:pendingStart–P$script:pendingEnd")}};$script:pending=@();$script:pendingStart=$null;$script:pendingEnd=$null}
 foreach($node in $body.ChildNodes){if($node.LocalName-eq"p"){$pi++;$text=Text-Of $node;if($expected-le$next-and$text-match("^"+$expected+"\.\s+")-and(Max-Size $node)-ge36){Flush;$current=$expected;$expected++;if($current-eq$target){$result.start="P$pi";$script:section=$null;continue};if($current-eq$next){$result.end="P$($pi-1)";break}};if($current-ne$target){continue};$result.end="P$pi";if(!$text){Flush;continue};if($text-match("^"+$target+"\.\d+\s+")){Flush;$title=($text-replace("^"+$target+"\.\d+\s+"),'').Trim();$script:section=[ordered]@{id=(Slugify $title);title=$title;contentClass=(Section-Class $title);blocks=@();evidence=@();sources=@((Ref $target "P$pi"))};$v=Validations-For $target $title;if($v.Count){$script:section.clientValidations=@($v)};$result.sections+=$script:section;continue};if($null-eq$script:section){continue};$isList=$null-ne$node.SelectSingleNode("./w:pPr/w:numPr",$ns);if($isList){if(!$script:pending.Count){$script:pendingStart=$pi};$script:pendingEnd=$pi;$script:pending+=$text}else{Flush;$script:section.blocks+=[ordered]@{type="paragraph";text=$text;source=(Ref $target "P$pi")}}}elseif($node.LocalName-eq"tbl"){$ti++;if($current-ne$target){continue};Flush;$rows=@();foreach($row in $node.SelectNodes("./w:tr",$ns)){$rows+=,@($row.SelectNodes("./w:tc",$ns)|ForEach-Object{Text-Of $_})};if($rows.Count-and$null-ne$script:section){$headers=@($rows[0]);$data=if($rows.Count-gt1){@($rows[1..($rows.Count-1)])}else{@()};$kind=if(($headers-join" ")-match'(?i)Nivel|Dimensión|Decisión|Fuente|Cadencia'){"comparison"}elseif(($headers-join" ")-match'(?i)Métrica'){"scorecard"}else{"simple"};$script:section.blocks+=[ordered]@{type="table";table=[ordered]@{id=("source-table-{0:D3}"-f$ti);caption=$script:section.title;kind=$kind;headers=$headers;rows=$data;source=(Ref $target "T$ti")}}}}};Flush;return $result}
$ch15=Extract-Chapter 15 16;$ch16=Extract-Chapter 16 17

$adoptionComplete=Complete @("WHAT","WHY","HOW","WHEN","INPUT","OUTPUT","DECISION","METRIC","EXAMPLE","ACTIVATION CRITERIA","TTV DEFINITION","ADHERENCE CRITERIA","VALUE EVIDENCE","FEEDBACK SOURCE","LEARNING TRIGGER","DECISION LOOP","BUSINESS LINKAGE") @("WHO","ARTIFACT","TOOL") @()
$adoptionSemantics=@(
 [ordered]@{term="AVAILABILITY";definition="Capacidad contratada/elegible y disponible; no implica configuración, activación o valor.";sourceStatus="SOURCE COMPLETE";source=(Ref 15 "P6403–P6418; P6453–P6471")},
 [ordered]@{term="ACTIVATION";definition="El usuario logra su primer criterio de éxito mediante un evento observable y relevante.";sourceStatus="SOURCE COMPLETE";source=(Ref 15 "P6453–P6465; P6528–P6538")},
 [ordered]@{term="USAGE";definition="Actividad o comportamiento observado; puede ser señal, pero no prueba valor u Outcome.";sourceStatus="SOURCE COMPLETE";source=(Ref 15 "P6540–P6551; P6568–P6586")},
 [ordered]@{term="ADOPTION";definition="Uso recurrente relevante, consistente con el Outcome y definido por capacidad, módulo y rol.";sourceStatus="SOURCE COMPLETE";source=(Ref 15 "P6453–P6465; P6540–P6551")},
 [ordered]@{term="ADHERENCE";definition="Sostenimiento del criterio de éxito durante el tiempo esperado; el periodo concreto no está definido.";sourceStatus="SOURCE PARTIAL";source=(Ref 15 "P6553–P6566")},
 [ordered]@{term="CUSTOMER AUTONOMY";definition="Capacidad de obtener el resultado como Self-Service, Assisted o Dependent sin tratar toda asistencia como desperdicio.";sourceStatus="SOURCE COMPLETE";source=(Ref 15 "P6627–P6659")},
 [ordered]@{term="CUSTOMER VALUE";definition="Primer éxito, resultado recurrente y Outcome observable para usuario/cliente; no equivale a actividad.";sourceStatus="SOURCE PARTIAL";source=(Ref 15 "P6371–P6387; P6568–P6586")},
 [ordered]@{term="RETENTION";definition="Resultado de negocio a evaluar; la fuente no afirma causalidad con adopción o adherencia.";sourceStatus="SOURCE PARTIAL";source=(Ref 15 "P6764–P6797; P6882–P6890")},
 [ordered]@{term="EXPANSION";definition="Oportunidad potencial respaldada por evidencia de valor y necesidad adicional; no está probada como Outcome.";sourceStatus="SOURCE PARTIAL";source=(Ref 15 "P6903–P6927")},
 [ordered]@{term="BUSINESS VALUE";definition="Retention, Expansion y MRR aparecen como capa Business, sin fórmula causal aprobada.";sourceStatus="SOURCE PARTIAL";source=(Ref 15 "P7102–P7135")}
)
function Adoption-Concept([string]$id,[string]$title,[string]$purpose,[string]$locator,[string]$behavior,[string]$success,[string[]]$evidence,[string]$metric,[string]$owner=""){$v=[ordered]@{id=$id;title=$title;purpose=$purpose;behavior=$behavior;successCondition=$success;evidence=$evidence;metric=$metric;decisionEnabled="Diagnosticar barrera y seleccionar intervención";sourceLocators=@((Ref 15 $locator));contentClass="recommendation";completeness=$adoptionComplete};if($owner){$v.owner=$owner};return $v}
$adoptionConcepts=@(
 (Adoption-Concept "activation" "Activation" "Identificar la primera evidencia de valor mínimo." "P6528–P6538" "Primer criterio de éxito observable por capacidad." "Evento conectado al criterio de éxito." @("first success event") "Activation rate"),
 (Adoption-Concept "ttv" "Time to Value (TTV)" "Medir velocidad hasta primer valor." "P6503–P6526" "Transcurso desde Start Event definido hasta First Success Event." "Primer criterio de éxito del usuario." @("start event","first success event","friction signals") "TTV"),
 (Adoption-Concept "adoption" "Adoption" "Observar uso relevante recurrente consistente con el Outcome." "P6540–P6551" "Comportamiento esperado por módulo y rol." "Uso recurrente relevante." @("behavior","eligible population") "Adoption rate"),
 (Adoption-Concept "adherence" "Adherence" "Determinar si el comportamiento de valor se sostiene." "P6553–P6566" "Sostenimiento del criterio de éxito; periodo pendiente." "Criterio de éxito mantenido." @("sustained behavior") "Adherence rate"),
 (Adoption-Concept "autonomy" "Customer Autonomy" "Distinguir Self-Service, Assisted y Dependent." "P6627–P6659" "Obtención de resultado con nivel observable de intervención SEIF." "Asistencia prevista o dependencia recurrente diferenciadas." @("support dependency","CS intervention","manual operation") "Autonomy classification"),
 (Adoption-Concept "customer-value" "Customer value evidence" "Conectar actividad con Success y Outcome Metrics." "P6568–P6586; P7102–P7135" "Success behavior y Outcome observable." "Resultado central alcanzado y sostenido." @("success metric","Outcome metric") "Customers achieving recurring value")
)
$ttv=[ordered]@{canonicalTerm="Time to Value (TTV)";definition="Tiempo hasta que el usuario alcanza su primer criterio de éxito.";startEvent="Debe definirse por capacidad; la fuente no fija un evento universal.";endEvent="First Success Event / primer criterio de éxito.";population="Usuarios o clientes elegibles de la capacidad relevante; definición operacional pendiente.";momentOfTruth="Control de Rondas: primer recorrido completado correctamente con confirmación.";successCondition="Primer criterio de éxito definido para el usuario.";decisionEnabled="Detectar fricción en journey, configuración, onboarding, relevancia o autonomía.";source=(Ref 15 "P6503–P6538");validationStatus="pending"}
$outcomeConnections=@(
 [ordered]@{element="Activation → Outcome";status="SUPPORTED";rationale="El evento de activación se conecta al criterio de éxito.";source=(Ref 15 "P6528–P6538")},[ordered]@{element="TTV → Outcome";status="SUPPORTED";rationale="TTV termina en primer criterio de éxito.";source=(Ref 15 "P6503–P6526")},[ordered]@{element="Adoption → Outcome";status="SUPPORTED";rationale="Adoption exige comportamiento consistente con Outcome.";source=(Ref 15 "P6540–P6551")},[ordered]@{element="Adherence → Outcome";status="SUPPORTED";rationale="Adherence sostiene el criterio de éxito.";source=(Ref 15 "P6553–P6566")},[ordered]@{element="Autonomy → Outcome";status="PARTIAL";rationale="Autonomy explica dependencia al obtener valor, pero no demuestra por sí sola el Outcome.";source=(Ref 15 "P6627–P6659")}
)
$rounds=[ordered]@{name="Control de Rondas";classification="EXAMPLE";details=[ordered]@{Outcome="SOURCE MISSING en Chapter 15";actors=@("Vigilante","Supervisor","Cliente/Gerente");journey="SOURCE PARTIAL";MomentOfTruth="Primer recorrido completado correctamente con confirmación";TTV="Tiempo hasta el primer criterio de éxito; sin fórmula o target";Adherence="Sostenimiento del criterio de éxito; periodo no especificado";successCriteria=@("Vigilante: éxito operacional","Supervisor: capacidad de verificar sin reproceso","Cliente/Gerente: capacidad de demostrar y utilizar información confiable")};source=(Ref 15 "P6532–P6533; P6962–P6972")}
$growth=@(
 [ordered]@{from="Adoption";to="Growth";classification="ASSESSMENT INTERPRETATION";rationale="El modelo define Activation, Adoption, Expansion y Retention Growth sin probar causalidad.";source=(Ref 15 "P6764–P6797");validationStatus="pending"},[ordered]@{from="Adherence";to="Retention";classification="HYPOTHESIS";rationale="Se propone que adherencia sostenida protege la relación; debe medirse.";source=(Ref 15 "P6764–P6777; P6882–P6890");validationStatus="pending"},[ordered]@{from="Customer Value";to="Expansion";classification="HYPOTHESIS";rationale="La expansión debe basarse en evidencia de valor más oportunidad adicional; no es resultado probado.";source=(Ref 15 "P6903–P6927");validationStatus="pending"},[ordered]@{from="Adoption";to="Retention";classification="HYPOTHESIS";rationale="La fuente rechaza afirmar que baja adopción causa churn sin historia suficiente.";source=(Ref 15 "P6882–P6890");validationStatus="pending"}
)
$northStar=[ordered]@{candidate="Recurring Value / Clientes con Valor Recurrente · NORTH STAR CANDIDATE";contentClass="hypothesis";supportStatus="PARTIAL";rationale="Chapters 15–16 fortalecen la dirección hacia valor recurrente y evidencia, pero no aportan fórmula corporativa ni correlación de negocio validada.";source=(Ref 15 "P6799–P6835; P7102–P7135");validationStatus="pending"}
function AM([string]$name,[string]$class,[string]$definition,[string]$locator,[string]$population=""){$v=[ordered]@{name=$name;metricClass=$class;definition=$definition;decisionEnabled="Diagnosticar funnel, fricción, riesgo u oportunidad sin inferir causalidad";baseline="SOURCE MISSING";target="SOURCE MISSING";source=(Ref 15 $locator);validationStatus="pending"};if($population){$v.population=$population};return $v}
$adoptionMetrics=@((AM "Eligible users/customers" "USAGE" "Población con derecho o acceso a la capacidad." "T45"),(AM "% correctly configured" "USAGE" "Población configurada correctamente." "T45"),(AM "% reaching first success" "ACTIVATION" "Proporción que alcanza primer criterio de éxito." "T45" "eligible population"),(AM "Time to Value (TTV)" "TTV" "Tiempo hasta primer valor." "T45; P6503–P6526"),(AM "% relevant recurrent use" "ADOPTION" "Uso relevante según capacidad, módulo y rol." "T45; P6540–P6551"),(AM "% sustaining success criteria" "ADHERENCE" "Sostenimiento del criterio de éxito; periodo pendiente." "T45; P6553–P6566"),(AM "Tickets / related interventions" "SUPPORT / FRICTION" "Fricción e intervención asociadas al funnel." "T45"),(AM "% self-service / assisted / dependent" "AUTONOMY" "Clasificación operativa de autonomía." "T45; P6627–P6639"),(AM "License utilization" "USAGE" "Utilización sobre capacidad relevante; trigger de investigación." "T45; P6588–P6609"),(AM "% reaching success criteria" "CUSTOMER VALUE" "Población que alcanza criterio de éxito." "T45"),(AM "Accounts below defined threshold" "SUPPORT / FRICTION" "Cuentas bajo un umbral todavía no definido." "T45"),(AM "Accounts with additional opportunity evidence" "EXPANSION" "Cuentas con evidencia de valor y oportunidad adicional." "T45; P6903–P6927"),(AM "Retention" "RETENTION" "Resultado de negocio cuya relación con adopción requiere evidencia histórica." "P7102–P7135"),(AM "Expansion" "EXPANSION" "Crecimiento respaldado por valor; causalidad no probada." "P7102–P7135"),(AM "MRR" "RETENTION" "Métrica Business mencionada en el Metric Tree; definición operacional no provista." "P7102–P7135"))
$adoptionCadences=@([ordered]@{name="Customer Signals";activityType="DATA COLLECTION";frequency="weekly";purpose="CS y Soporte observan excepciones y riesgos en operación habitual.";source=(Ref 15 "P7057–P7078");validationStatus="pending"},[ordered]@{name="Growth / Discovery";activityType="REVIEW";frequency="biweekly";purpose="Analizar Opportunities de adopción y experimentos cuando corresponda.";source=(Ref 15 "P7057–P7078");validationStatus="pending"},[ordered]@{name="Outcome & Adoption Review";activityType="DECISION";frequency="monthly";purpose="Observar TTV, activación, adherencia, fricción, autonomía, riesgo y aprendizajes.";source=(Ref 15 "P7057–P7078");validationStatus="pending"},[ordered]@{name="Business / Product Direction";activityType="DECISION";frequency="quarterly";purpose="Analizar relación todavía no validada entre valor, retention, expansion e inversión.";source=(Ref 15 "P7057–P7078");validationStatus="pending"})
$adoptionTools=@([ordered]@{tool="Analytics / dashboards";classification="CURRENT STATE";relationship="Utilización, usuarios, módulos y funnel; actividad no equivale a valor.";source=(Ref 15 "P6373–P6383; P7137–P7154");validationStatus="pending"},[ordered]@{tool="Jira";classification="RECOMMENDATION";relationship="Trazabilidad Outcome → Bet → Delivery → Release.";source=(Ref 15 "P7188–P7203");validationStatus="pending"},[ordered]@{tool="Jira Service Management";classification="RECOMMENDATION";relationship="Tickets → módulo → fricción → recurrencia.";source=(Ref 15 "P7188–P7203");validationStatus="pending"},[ordered]@{tool="Confluence";classification="RECOMMENDATION";relationship="Playbook, criterios y aprendizajes.";source=(Ref 15 "P7188–P7203");validationStatus="pending"},[ordered]@{tool="AI";classification="H1 / TO VALIDATE";relationship="Clustering, patrones, resúmenes y apoyo a CS bajo reglas validadas.";source=(Ref 15 "P7174–P7186");validationStatus="pending"})

$learnComplete=Complete @("WHAT","WHY","HOW","WHO","WHEN","INPUT","OUTPUT","ARTIFACT","DECISION","METRIC","EXAMPLE","VALUE EVIDENCE","FEEDBACK SOURCE","LEARNING TRIGGER","DECISION LOOP") @("TOOL","BUSINESS LINKAGE") @("ACTIVATION CRITERIA","TTV DEFINITION","ADHERENCE CRITERIA")
function LC([string]$id,[string]$title,[string]$purpose,[string]$locator,[string[]]$inputs,[string[]]$outputs,[string]$decision=""){$v=[ordered]@{id=$id;title=$title;purpose=$purpose;inputs=$inputs;outputs=$outputs;decision=$decision;sourceLocators=@((Ref 16 $locator));contentClass="recommendation";completeness=$learnComplete};return $v}
$learningConcepts=@((LC "expected" "Expected Result" "Explicitar qué debería ocurrir antes de observar." "P7705–P7721; P7862–P7880" @("hypothesis","expected signal") @("comparison baseline")),(LC "actual" "Actual Result" "Registrar qué ocurrió realmente." "P7705–P7721; P7862–P7880" @("behavior","technical/product signals") @("observed result")),(LC "evidence" "Evidence" "Contrastar señales, comportamiento y sistema." "P7569–P7593; P7824–P7835" @("explicit","behavioral","operational","business feedback") @("evidence strength")),(LC "difference" "Difference" "Comparar Expected vs Actual y qué cambió/no cambió." "P7862–P7880" @("expected","actual") @("difference")),(LC "learning" "Learning" "Convertir evidencia en comprensión explícita asociada a Bet/Opportunity." "P7705–P7721; P8380–P8391" @("difference","evidence") @("Learning Card","insight")),(LC "decision" "Decision" "Cerrar el loop modificando la acción." "P7882–P7894" @("learning","evidence") @("SCALE","CONTINUE","ADJUST","EXPLORE","STOP") "Scale / Continue / Adjust / Explore / Stop"))
$signals=@(
 [ordered]@{signal="Problemas, prioridades y Outcomes";sourceRole="Product";trigger="feedback/evidence requiring integration";format="Opportunity / Evidence";decisionEnabled="Discovery or priority change";artifact="Evidence Map";source=(Ref 16 "P7360–P7382; P7995–P8008")},
 [ordered]@{signal="Comportamiento, journeys, fricción y Momentos de Verdad";sourceRole="UX/UI";format="research / validation";decisionEnabled="experience hypothesis";artifact="Evidence Map";source=(Ref 16 "P7360–P7382; P8010–P8020")},
 [ordered]@{signal="Adopción, barreras, dependencia y contexto de cuenta";sourceRole="Customer Success";format="structured account observation";decisionEnabled="Opportunity / adoption intervention";artifact="Signal";source=(Ref 16 "P7360–P7382; P8022–P8036")},
 [ordered]@{signal="Tickets, recurrencia, módulo, journey y causa";sourceRole="Support";trigger="recurring friction";format="ticket pattern";decisionEnabled="investigate pattern, not feature";artifact="Signal";source=(Ref 16 "P7360–P7382; P8038–P8048")},
 [ordered]@{signal="Percepción, mensajes, objeciones, segmentos y campañas";sourceRole="Marketing";format="market / communication feedback";decisionEnabled="positioning or Opportunity";artifact="Signal";source=(Ref 16 "P7360–P7382; P8050–P8059")},
 [ordered]@{signal="Deuda, limitaciones, recurrencia técnica y complejidad";sourceRole="Development";format="technical evidence";decisionEnabled="technical Opportunity";artifact="Signal";source=(Ref 16 "P7360–P7382; P8061–P8077")},
 [ordered]@{signal="Incidentes, confiabilidad, operación y deuda";sourceRole="SRE";trigger="operational behavior";format="operational evidence";decisionEnabled="reliability Opportunity";artifact="Signal";source=(Ref 16 "P7360–P7382; P8061–P8077")},
 [ordered]@{signal="Comportamiento cuantitativo";sourceRole="Analytics / Dashboards";format="behavioral data";decisionEnabled="investigation trigger";artifact="Signal";source=(Ref 16 "P7360–P7382")},
 [ordered]@{signal="Necesidad expresada, comportamiento y resultado";sourceRole="Customers / Users";format="interview / request / review / behavior";decisionEnabled="investigate underlying need";artifact="Signal";source=(Ref 16 "P7472–P7529")}
)
$chain=@([ordered]@{element="SIGNAL";status="SUPPORTED";rationale="Observación que todavía no determina acción.";source=(Ref 16 "P7422–P7464")},[ordered]@{element="PATTERN";status="SUPPORTED";rationale="Agrupación de señales con mayor fuerza.";source=(Ref 16 "P7554–P7567")},[ordered]@{element="EVIDENCE";status="SUPPORTED";rationale="Señales contrastadas y clasificadas por fuerza.";source=(Ref 16 "P7569–P7593")},[ordered]@{element="INSIGHT";status="SUPPORTED";rationale="Chapter 16 introduce explícitamente INSIGHT; Chapter 12 permanece sin modificación.";source=(Ref 16 "P7419–P7440; P8146–P8197")},[ordered]@{element="LEARNING";status="SUPPORTED";rationale="Resultado explícito de comparar hipótesis, acción y evidencia.";source=(Ref 16 "P7705–P7721; P8380–P8391")},[ordered]@{element="DECISION";status="SUPPORTED";rationale="El aprendizaje se completa cuando modifica una decisión.";source=(Ref 16 "P7882–P7894; P8380–P8391")})
$decisions=@();foreach($d in @(@("SCALE","La evidencia respalda ampliar."),@("CONTINUE","La hipótesis sigue válida y necesita más tiempo/evidencia."),@("ADJUST","La dirección parece válida y necesita modificación."),@("EXPLORE","Apareció nueva incertidumbre."),@("STOP","La evidencia no justifica continuar."))){$decisions+=[ordered]@{decision=$d[0];trigger="Outcome Review / Review Trigger con evidencia suficiente";evidence=@("Expected","Actual","Evidence","Difference","Learning");participants=@("Product","roles fuente según evidencia");output=$d[1];revisitCondition="Review Trigger según tiempo, volumen, evento o threshold definido; sin periodo universal";source=(Ref 16 "P7837–P7894");validationStatus="pending"}}
$loopConnections=@([ordered]@{element="Learning → Opportunity";status="SUPPORTED";rationale="Learning puede generar nueva Opportunity.";source=(Ref 16 "P7322–P7358")},[ordered]@{element="Learning → Outcome";status="SUPPORTED";rationale="Outcome Review compara resultado esperado y real.";source=(Ref 16 "P7862–P7880")},[ordered]@{element="Learning → Bet";status="SUPPORTED";rationale="Puede modificar, continuar, escalar o detener una Bet.";source=(Ref 16 "P7322–P7358; P8124–P8129")},[ordered]@{element="Learning → Discovery";status="SUPPORTED";rationale="EXPLORE y nueva incertidumbre reabren Discovery.";source=(Ref 16 "P7882–P7894; P8110–P8122")},[ordered]@{element="Learning → DECIDE";status="SUPPORTED";rationale="Evidence modifica Explore, Prioritize, Wait, Discard o Reframe.";source=(Ref 16 "P8110–P8122")})
function LM([string]$name,[string]$definition,[string]$locator,[string]$class="LEARNING"){$v=[ordered]@{name=$name;metricClass=$class;definition=$definition;decisionEnabled="Mejorar síntesis y decisiones, no volumen documental";baseline="SOURCE MISSING";target="SOURCE MISSING";source=(Ref 16 $locator);validationStatus="pending"};return $v}
$learningMetrics=@((LM "Signal → Opportunity Time" "Tiempo para procesar señales hasta Opportunity." "T50"),(LM "Learning Lead Time" "Tiempo desde incertidumbre relevante hasta evidencia suficiente para decidir." "T50; P7896–P7906"),(LM "% Opportunities with multiple evidence sources" "Calidad y triangulación de evidencia." "T50"),(LM "% Bets with explicit hypothesis" "Disciplina experimental." "T50"),(LM "% Bets with Review Trigger" "Capacidad de cerrar el loop." "T50"),(LM "Release → First Evidence" "Velocidad post-release." "T50"),(LM "% Bets with documented learning" "Cierre explícito del aprendizaje." "T50"),(LM "Scale / Adjust / Stop Rate" "Capacidad de actuar sobre evidencia." "T50"),(LM "Repeated Friction Rate" "Problemas que reaparecen." "T50" "SUPPORT / FRICTION"),(LM "Feedback → Decision Conversion" "Utilidad real del feedback." "T50"))
$learningCadences=@([ordered]@{name="Continuous signals";activityType="DATA COLLECTION";frequency="continuous";purpose="Capturar señales materialmente relevantes desde sensores organizacionales.";source=(Ref 16 "P7300–P7320; P7472–P7510");validationStatus="pending"},[ordered]@{name="Weekly Flow Review";activityType="REVIEW";frequency="weekly";purpose="Bloqueos y señales críticas.";source=(Ref 16 "T54");validationStatus="pending"},[ordered]@{name="Biweekly Opportunity Review";activityType="DECISION";frequency="biweekly";purpose="Evidence, Discovery y decisiones.";source=(Ref 16 "T54");validationStatus="pending"},[ordered]@{name="Customer Review";activityType="LEARNING";frequency="when needed";purpose="Validación de comportamiento, no aceptación contractual.";source=(Ref 16 "P7775–P7805; T54");validationStatus="pending"},[ordered]@{name="Monthly Outcome Review";activityType="DECISION";frequency="monthly";purpose="Expected vs Actual vs Learning.";source=(Ref 16 "P7862–P7880; T54");validationStatus="pending"},[ordered]@{name="Quarterly Direction Review";activityType="DECISION";frequency="quarterly";purpose="Aprendizaje estratégico y reasignación.";source=(Ref 16 "T54");validationStatus="pending"})
$learningTools=@([ordered]@{tool="Jira";classification="RECOMMENDATION";relationship="Trazabilidad Signal → Opportunity → Outcome → Bet → Delivery → Evidence/Learning; no toda signal es issue.";source=(Ref 16 "P8199–P8214");validationStatus="pending"},[ordered]@{tool="Jira Service Management";classification="RECOMMENDATION";relationship="Request/Incident → Module → Journey → Category → Pattern → Product Signal.";source=(Ref 16 "P8216–P8230");validationStatus="pending"},[ordered]@{tool="Confluence";classification="RECOMMENDATION";relationship="Contexto narrativo de Evidence Map, Decision Log, Learning Card y reviews.";source=(Ref 16 "P8233–P8244");validationStatus="pending"},[ordered]@{tool="Rovo / AI";classification="H1 / TO VALIDATE";relationship="Clustering, síntesis y retrieval; no sustituye juicio de Producto.";source=(Ref 16 "P8246–P8264");validationStatus="pending"},[ordered]@{tool="AI Feedback Agent";classification="H1 / TO VALIDATE";relationship="Evolución futura posterior a taxonomía, ownership, calidad y criterios.";source=(Ref 16 "P8266–P8285");validationStatus="pending"},[ordered]@{tool="Learning dashboard";classification="RECOMMENDATION";relationship="Mostrar aprendizaje y decisiones, no cantidad de feedback.";source=(Ref 16 "P8287–P8302");validationStatus="pending"})
$artifactUses=@([ordered]@{artifactId="evidence-map";artifactName="Evidence Map";relationship="UPDATES";usage="Artefacto vivo por Opportunity con fuentes y fuerza de evidencia.";source=(Ref 16 "P7700–P7703; T49");validationStatus="pending"},[ordered]@{artifactId="learning-card";artifactName="Learning Card";relationship="CREATES";usage="Cierra We believed → We observed → We learned → Therefore.";source=(Ref 16 "P7705–P7721");validationStatus="pending"},[ordered]@{artifactId="decision-log";artifactName="Decision Log";relationship="READS";usage="Mantiene contexto narrativo de decisiones junto al aprendizaje.";source=(Ref 16 "P8233–P8244");validationStatus="pending"},[ordered]@{artifactId="source-customer-feedback-repository";artifactName="Customer Feedback Repository";relationship="SOURCE TERMINOLOGY CONFLICT";usage="Fuente lógica compartida de evidencia, no necesariamente nueva plataforma.";source=(Ref 16 "P7684–P7697");validationStatus="pending"})
$anti15=@([ordered]@{antiPattern="Usage = Value";status="NOT PRESENT";rationale="Activity, Success y Outcome metrics se separan.";source=(Ref 15 "P6568–P6586")},[ordered]@{antiPattern="Login = Activation";status="NOT PRESENT";rationale="Login no demuestra valor; Activation exige primer criterio de éxito.";source=(Ref 15 "P6519–P6538")},[ordered]@{antiPattern="Release = Adoption";status="NOT PRESENT";rationale="El funnel comienza tras release y distingue Activated/Adopted/Adherent.";source=(Ref 15 "P6389–P6418")},[ordered]@{antiPattern="Adoption without success criteria";status="NOT PRESENT";rationale="Comportamiento y evento deben conectarse al criterio de éxito.";source=(Ref 15 "P6503–P6551")},[ordered]@{antiPattern="Vanity metrics";status="SOURCE RISK";rationale="Usuarios, logins, clicks, licencias y módulos no bastan como éxito.";source=(Ref 15 "P7083–P7100")},[ordered]@{antiPattern="CS used as permanent workaround";status="SOURCE RISK";rationale="CS as Human Middleware y Failure Demand aparecen explícitamente.";source=(Ref 15 "P6641–P6659; P7219–P7236")},[ordered]@{antiPattern="Support hiding product friction";status="NOT PRESENT";rationale="Tickets se convierten en señales según funnel y patrón.";source=(Ref 15 "P6712–P6723")},[ordered]@{antiPattern="North Star theatre";status="SOURCE RISK";rationale="No existe evidencia para fórmula corporativa única ni correlación de negocio validada.";source=(Ref 15 "P6799–P6811")},[ordered]@{antiPattern="Retention causality assumed";status="NOT PRESENT";rationale="La fuente rechaza afirmar causalidad sin historia.";source=(Ref 15 "P6882–P6890")},[ordered]@{antiPattern="Expansion causality assumed";status="NOT PRESENT";rationale="Expansion requiere evidencia de valor más oportunidad adicional.";source=(Ref 15 "P6903–P6927")})
$anti16=@([ordered]@{antiPattern="Feedback without synthesis";status="SOURCE RISK";rationale="La brecha fuente es feedback distribuido sin sistema común.";source=(Ref 16 "P7300–P7320")},[ordered]@{antiPattern="Ticket = feature";status="NOT PRESENT";rationale="Ticket es Signal y requiere patrón, causa y Opportunity.";source=(Ref 16 "P7384–P7440; P7646–P7664")},[ordered]@{antiPattern="Customer request = priority";status="NOT PRESENT";rationale="Request se investiga hasta Need, Evidence y Opportunity.";source=(Ref 16 "P7512–P7529; P7622–P7644")},[ordered]@{antiPattern="Learning without decision";status="NOT PRESENT";rationale="Definition of Learned exige decisión.";source=(Ref 16 "P7882–P7894; P8380–P8391")},[ordered]@{antiPattern="Review meeting without learning";status="SOURCE RISK";rationale="No se crea Learning Meeting; reviews deben producir evidencia o decisión.";source=(Ref 16 "P8079–P8090")},[ordered]@{antiPattern="No post-release measurement";status="SOURCE RISK";rationale="Release sin revisión aparece como Learning Debt.";source=(Ref 16 "P7824–P7859; P7944–P7958")},[ordered]@{antiPattern="Late customer feedback";status="SOURCE RISK";rationale="El TO-BE responde al feedback concentrado al final con reviews antes y durante Delivery.";source=(Ref 16 "P7738–P7822")},[ordered]@{antiPattern="Customer only consulted pre-release";status="NOT PRESENT";rationale="Existen feedback durante Delivery y después de Release.";source=(Ref 16 "P7807–P7835")},[ordered]@{antiPattern="Customer only consulted post-release";status="NOT PRESENT";rationale="Learning before building y prototyping preceden Delivery.";source=(Ref 16 "P7723–P7757")})

$op15=@([ordered]@{id="adoption-value-system";title="ADOPT — Adoption & Growth Model";canonicalLayers=@("ADOPT","LEARN","ROLES","METRICS","EVIDENCE");sourceChapters=@("15");sourceLocators=@((Ref 15 "P6371–P7298"));contentClass="recommendation";completeness=$adoptionComplete;gapIds=@("CL-04","CL-05","CL-06","CL-07","CL-08","CL-10","CL-11","CL-13","CL-15")})
$op16=@([ordered]@{id="feedback-learning-system";title="LEARN — Feedback & Learning Loop";canonicalLayers=@("LEARN","DISCOVER","DECIDE","EVIDENCE","CONTINUOUS IMPROVEMENT");sourceChapters=@("16");sourceLocators=@((Ref 16 "P7299–P8442"));contentClass="recommendation";completeness=$learnComplete;gapIds=@("CL-04","CL-05","CL-07","CL-10","CL-11","CL-16")})
$m15=[ordered]@{slug="adoption-growth";group="Operating Model";title="ADOPT: Adoption, valor y Growth";sourceTitle="15. Adoption & Growth Model";eyebrow="15 · Adopt";summary="Distingue disponibilidad, activación, TTV, adopción, adherencia, autonomía y evidencia de Outcome antes de inferir retención o expansión.";takeaway="Uso es señal; valor exige criterio de éxito, comportamiento relevante y Outcome observable.";executive=[ordered]@{keyFindings=@("Activation exige primer criterio de éxito; login y configuración no bastan.","TTV mide tiempo hasta primer valor, con eventos operacionales todavía pendientes de aprobación.","Adoption es uso relevante recurrente; Adherence sostiene el criterio de éxito.","Retention, Expansion y North Star permanecen hipótesis/relaciones por validar.");implication="SEIF puede pasar de medir utilización a gestionar el ciclo de valor sin asumir causalidad comercial.";evidenceConfidence="medium";evidenceStatus="pending";primaryVisual="flow";sources=@((Ref 15 ($ch15.start+"–"+$ch15.end)))};clientValidations=@((CV "CL-06" "North Star candidate"),(CV "CL-08" "Activation, TTV, Adoption y Adherence"),(CV "CL-13" "Growth / Expansion ownership"));operatingConcepts=$op15;adoptionSemantics=$adoptionSemantics;adoptionConcepts=$adoptionConcepts;timeToValue=$ttv;customerOutcomeConnections=$outcomeConnections;operatingExamples=@($rounds);growthRelationships=$growth;northStarSupport=$northStar;adoptionLearningMetrics=$adoptionMetrics;learningCadences=$adoptionCadences;adoptionLearningTooling=$adoptionTools;antiPatternAssessments=$anti15;sections=@($ch15.sections);related=@("value-stream","operating-model","discovery","prioritization","delivery","feedback-loop","roles","north-star","governance","artifacts");source=[ordered]@{title="15. Adoption & Growth Model";locator=($ch15.start+"–"+$ch15.end);note="Locators internos de párrafo OOXML; no se muestran por defecto."}}
$m16=[ordered]@{slug="feedback-loop";group="Operating Model";title="LEARN: Feedback & Learning Loop";sourceTitle="16. Feedback & Learning Loop";eyebrow="16 · Learn";summary="Convierte señales distribuidas en patrones, evidencia, insight, aprendizaje y decisiones que reabren Opportunity, Discovery y DECIDE.";takeaway="Una señal no es evidencia; una evidencia no es decisión; el aprendizaje no se completa hasta cambiar una decisión.";executive=[ordered]@{keyFindings=@("SEIF posee múltiples sensores; la brecha es integrarlos en un sistema de aprendizaje.","Chapter 16 introduce INSIGHT como término fuente explícito sin alterar Chapter 12.","Tickets y solicitudes permanecen señales, nunca features o prioridades automáticas.","SCALE, CONTINUE, ADJUST, EXPLORE y STOP cierran el loop con authority pendiente.");implication="El loop reduce deuda de feedback y aprendizaje mediante trazabilidad, síntesis y decisiones explícitas.";evidenceConfidence="medium";evidenceStatus="pending";primaryVisual="loop";sources=@((Ref 16 ($ch16.start+"–"+$ch16.end)))};clientValidations=@((CV "CL-05" "Authority de decisiones de aprendizaje"),(CV "CL-10" "Tooling lógico"),(CV "CL-11" "Cadencias y Review Triggers"));operatingConcepts=$op16;feedbackSignals=$signals;signalLearningChain=$chain;learningConcepts=$learningConcepts;learningDecisions=$decisions;feedbackLoopConnections=$loopConnections;artifactUses=$artifactUses;adoptionLearningMetrics=$learningMetrics;learningCadences=$learningCadences;adoptionLearningTooling=$learningTools;antiPatternAssessments=$anti16;sections=@($ch16.sections);related=@("value-stream","operating-model","discovery","prioritization","delivery","adoption-growth","roles","north-star","governance","artifacts");source=[ordered]@{title="16. Feedback & Learning Loop";locator=($ch16.start+"–"+$ch16.end);note="Locators internos de párrafo OOXML; no se muestran por defecto."}}
foreach($pair in @(@("15-adoption-growth.ts",$m15),@("16-feedback-loop.ts",$m16))){$json=$pair[1]|ConvertTo-Json -Depth 100;$content="import type { Chapter } from `"@/types/content`";`r`n`r`nexport const chapter = $json satisfies Chapter;`r`n";[IO.File]::WriteAllText((Join-Path $repo ("content/chapters/"+$pair[0])),$content,[Text.UTF8Encoding]::new($false))}
Write-Output "Block B Wave 6 ingestion generated Chapters 15–16 from $Source."
