param([string]$Source = "source-private/SEIF-master-v0.1.docx")

$ErrorActionPreference="Stop"
$repo=Split-Path -Parent $PSScriptRoot;$sourcePath=Join-Path $repo $Source
if(-not(Test-Path -LiteralPath $sourcePath -PathType Leaf)){throw "SOURCE NOT FOUND"}
Add-Type -AssemblyName System.IO.Compression.FileSystem
$zip=[IO.Compression.ZipFile]::OpenRead($sourcePath)
try{$entry=$zip.GetEntry("word/document.xml");$reader=[IO.StreamReader]::new($entry.Open());try{[xml]$document=$reader.ReadToEnd()}finally{$reader.Dispose()}}finally{$zip.Dispose()}
$ns=[Xml.XmlNamespaceManager]::new($document.NameTable);$ns.AddNamespace("w","http://schemas.openxmlformats.org/wordprocessingml/2006/main");$body=$document.SelectSingleNode("//w:body",$ns)
function Text-Of($node){return(($node.SelectNodes(".//w:t",$ns)|ForEach-Object{$_.InnerText})-join"").Trim()}
function Max-Size($p){$s=@($p.SelectNodes(".//w:rPr/w:sz",$ns)|ForEach-Object{[int]$_.GetAttribute("val",$ns.LookupNamespace("w"))});if(!$s.Count){return 0};return($s|Measure-Object -Maximum).Maximum}
function Slugify([string]$v){$n=$v.Normalize([Text.NormalizationForm]::FormD);$c=$n.ToCharArray()|Where-Object{[Globalization.CharUnicodeInfo]::GetUnicodeCategory($_)-ne[Globalization.UnicodeCategory]::NonSpacingMark};return((-join$c).ToLowerInvariant()-replace"[^a-z0-9]+","-").Trim("-")}
function Ref([string]$title,[string]$locator){return [ordered]@{title=$title;locator=$locator}}
function Completeness([string[]]$complete,[string[]]$partial,[string[]]$missing){$v=[ordered]@{};foreach($k in $complete){$v[$k]="SOURCE COMPLETE"};foreach($k in $partial){$v[$k]="SOURCE PARTIAL"};foreach($k in $missing){$v[$k]="SOURCE MISSING"};return $v}
function CV([string]$id,[string]$subject){return [ordered]@{id=$id;subject=$subject;status="CLIENT VALIDATION REQUIRED"}}

$meta=@{
  17=[ordered]@{file="17-roles.ts";slug="roles";title="Roles, responsabilidades y derechos de decisión";sourceTitle="17. Roles, Responsabilidades y Ownership";eyebrow="17 · Ownership";summary="El modelo fuente distribuye ownership según la naturaleza de la decisión y separa contribución, decisión y respuesta por el resultado.";takeaway="Ownership no significa ejecutar todo: exige distinguir quién contribuye, quién decide y quién responde por el resultado.";findings=@("La fuente conserva roles y capacidades existentes sin proponer una reorganización automática.","Producto responde por problema, Outcome, prioridad y decisión de aprendizaje; cada especialidad responde por la calidad de su capacidad.","La fuente incluye una matriz de decisiones y un RACI ligero explícitos.","Los mapeos organizacionales y la autoridad efectiva siguen pendientes de validación del cliente.");implication="El capítulo ofrece un contrato operativo propuesto; no constituye un organigrama aprobado ni resuelve Head de Producto, Product Owner, Outcome Owner o Domain Owner.";related=@("design-principles","operating-model","discovery","prioritization","delivery","adoption-growth","feedback-loop","governance","artifacts","jira")}
  20=[ordered]@{file="20-artifacts.ts";slug="artifacts";title="Artefactos mínimos";sourceTitle="20. Artefactos Mínimos";eyebrow="20 · Business objects";summary="Ocho artefactos fuente conservan el contexto mínimo para conectar señales, problemas, Outcomes, Bets, ejecución, evidencia, aprendizaje y decisiones.";takeaway="El artefacto mínimo es el que permite entender por qué importa, qué sabemos, qué falta, qué se decidió, quién responde y qué ocurre después.";findings=@("La fuente define ocho artefactos core y objetos embebidos cuando agregan evidencia o contexto.","Los campos se capturan únicamente donde el documento los especifica.","El lifecycle fuente evoluciona desde Signal hasta Decision y vuelve a comenzar.","La relación con Jira permanece lógica y recomendada; no define issue types ni workflows aprobados.");implication="Los objetos forman una gramática operativa propuesta. Ownership, tooling y campos operacionales conservan sus validaciones abiertas.";related=@("design-principles","operating-model","discovery","prioritization","delivery","adoption-growth","feedback-loop","roles","governance","jira")}
}
$chapters=@{17=[ordered]@{sections=@();start=$null;end=$null};20=[ordered]@{sections=@();start=$null;end=$null}}
$chapter=0;$expected=1;$pi=0;$ti=0;$section=$null;$pending=@();$pendingStart=$null;$pendingEnd=$null
function Flush-List{if($null-ne$script:section-and$script:pending.Count){$script:section.blocks+=[ordered]@{type="list";items=@($script:pending);source=(Ref $meta[$script:chapter].sourceTitle "P$script:pendingStart–P$script:pendingEnd")}};$script:pending=@();$script:pendingStart=$null;$script:pendingEnd=$null}
function Section-Class([int]$number,[string]$title){if($title-match'(?i)Maturity Model|Estado SEIF'){return "hypothesis"};if($title-match'(?i)AS-IS|diagnóstico|hallazgo|Assessment'){return "mixed"};if($number-eq20-and$title-match'(?i)Jira|Confluence|dashboard|Source of Truth'){return "recommendation"};return "recommendation"}
function Validations-For([int]$number,[string]$title){$r=@();if($number-eq17-and$title-match'(?i)Decision Rights Matrix|RACI|Escalamiento|Delegation'){$r+=,(CV "CL-05" "Accountability organizacional y derechos de decisión")};if($title-match'(?i)cadence|Ownership Review|ritual'){$r+=,(CV "CL-11" "Cadencia propuesta, participantes y triggers")};if($title-match'(?i)deuda técnica'){$r+=,(CV "CL-12" "Política de capacidad y deuda técnica")};if($title-match'(?i)Ownership de Growth|Ownership de Product Marketing'){$r+=,(CV "CL-13" "Ownership de Growth, Expansion y Product Marketing")};if($number-eq20-and$title-match'(?i)Source of Truth|Arquitectura lógica en Jira'){$r+=,(CV "CL-10" "Arquitectura de tooling y relación con business objects")};return $r}
foreach($node in $body.ChildNodes){if($node.LocalName-eq"p"){$pi++;$text=Text-Of $node;if($expected-le21-and$text-match("^"+$expected+"\.\s+")-and(Max-Size $node)-ge36){Flush-List;$chapter=$expected;$expected++;if($chapter-in17,20){$chapters[$chapter].start="P$pi";$section=$null;continue}};if($chapter-eq21){Flush-List;break};if($chapter-notin17,20){continue};$chapters[$chapter].end="P$pi";if(!$text){Flush-List;continue};if($text-match("^"+$chapter+"\.\d+\s+")){Flush-List;$title=($text-replace("^"+$chapter+"\.\d+\s+"),"").Trim();$section=[ordered]@{id=(Slugify $title);title=$title;contentClass=(Section-Class $chapter $title);blocks=@();evidence=@();sources=@((Ref $meta[$chapter].sourceTitle "P$pi"))};$v=Validations-For $chapter $title;if($v.Count){$section.clientValidations=@($v)};$chapters[$chapter].sections+=$section;continue};if($null-eq$section){continue};$isList=$null-ne$node.SelectSingleNode("./w:pPr/w:numPr",$ns);if($isList){if(!$pending.Count){$pendingStart=$pi};$pendingEnd=$pi;$pending+=$text}else{Flush-List;$section.blocks+=[ordered]@{type="paragraph";text=$text;source=(Ref $meta[$chapter].sourceTitle "P$pi")}}}elseif($node.LocalName-eq"tbl"){$ti++;if($chapter-notin17,20){continue};Flush-List;$rows=@();foreach($row in $node.SelectNodes("./w:tr",$ns)){$rows+=,@($row.SelectNodes("./w:tc",$ns)|ForEach-Object{Text-Of $_})};if($rows.Count-and$null-ne$section){$headers=@($rows[0]);$data=if($rows.Count-gt1){@($rows[1..($rows.Count-1)])}else{@()};$kind=if(($headers-join" ")-match'(?i)AS-IS|TO-BE|Decision|RACI|Etapa|Dimensión'){"comparison"}elseif(($headers-join" ")-match'(?i)Métrica'){"scorecard"}else{"simple"};$section.blocks+=[ordered]@{type="table";table=[ordered]@{id=("source-table-{0:D3}"-f$ti);caption=$section.title;kind=$kind;headers=$headers;rows=$data;source=(Ref $meta[$chapter].sourceTitle "T$ti")}}}}};Flush-List

$roleCompleteness=Completeness @("WHAT","WHY","WHO","DECISION") @("HOW","INPUT","OUTPUT","ARTIFACT","METRIC") @("WHEN","TOOL","EXAMPLE")
function Role([string]$id,[string]$name,[string]$locator,[string]$purpose,[string[]]$responsibilities,[string[]]$decisions,[string[]]$interactions,[string[]]$stages,[string[]]$semantics,[string[]]$validations=@("CL-04")){return [ordered]@{id=$id;sourceRole=$name;purpose=$purpose;responsibilities=$responsibilities;decisionRights=$decisions;interactions=$interactions;canonicalStages=$stages;semantics=$semantics;mappingStatus="ROLE MAPPING PENDING";completeness=$roleCompleteness;sourceLocators=@((Ref $meta[17].sourceTitle $locator));clientValidationIds=$validations}}
$roles=@(
 (Role "head-producto" "Head de Producto" "P8510–P8535" "Owner principal del sistema de decisiones de Producto." @("Signals, Opportunities, Outcomes, éxito, priorización, foco, Bets, feedback, learning y trazabilidad") @("Problem → Outcome → Priority → Learning Decision") @("UX","Desarrollo","SRE","CS","Soporte","Marketing","Liderazgo") @("DISCOVER","DECIDE","LEARN") @("ACCOUNTABLE","DECISION OWNER")),
 (Role "ux-ui" "UX/UI" "P8548–P8582" "Owner de comportamiento, experiencia, usabilidad y journey." @("Investigación","prototipado","validación de experiencia") @("Ajustes de interacción dentro de una Bet validada") @("Producto","usuarios","Desarrollo") @("DISCOVER","DELIVER","LEARN") @("RESPONSIBLE","CONTRIBUTOR")),
 (Role "desarrollo" "Desarrollo" "P8584–P8614" "Owner de factibilidad, solución técnica y calidad." @("Diseño e implementación técnica","estimación y dependencias","testing, deuda y release readiness") @("Decisiones técnicas internas") @("Producto","UX","SRE") @("DECIDE","DELIVER") @("RESPONSIBLE","DECISION OWNER")),
 (Role "sre" "SRE" "P8616–P8645" "Owner de confiabilidad, operabilidad y recuperación." @("Observabilidad","disponibilidad y resiliencia","riesgo operacional y readiness") @("Restore ante incidente crítico","aceptabilidad operacional") @("Desarrollo","Producto","Soporte") @("DELIVER","ADOPT","LEARN") @("RESPONSIBLE","DECISION OWNER")),
 (Role "soporte" "Soporte" "P8647–P8670" "Owner de resolución, contexto de fricción y patrones." @("Resolver reportes operacionales","capturar contexto, recurrencia y señales") @() @("CS","Producto","SRE") @("DISCOVER","ADOPT","LEARN") @("RESPONSIBLE","CONTRIBUTOR")),
 (Role "customer-success" "Customer Success" "P8672–P8705" "Owner del journey de valor de cuenta desde implementación hasta adopción." @("Activación, adopción y adherencia","riesgos, barreras y señales de expansión") @("Acción operativa de adopción") @("Producto","Soporte","Marketing") @("ADOPT","LEARN") @("RESPONSIBLE","CONTRIBUTOR") @("CL-04","CL-13")),
 (Role "marketing" "Marketing" "P8707–P8732" "Owner de señales de mercado y comunicación de valor." @("Market intelligence","posicionamiento, lanzamiento y comunicación de adopción") @() @("Producto","CS") @("DISCOVER","ADOPT") @("RESPONSIBLE","CONTRIBUTOR") @("CL-04","CL-13")),
 (Role "liderazgo" "Liderazgo" "P8734–P8760" "Owner de dirección estratégica y trade-offs mayores." @("Dirección, restricciones, prioridades corporativas y sponsorship") @("Inversión de alto impacto","trade-offs estratégicos") @("Producto","células") @("DECIDE") @("ACCOUNTABLE","DECISION OWNER") @("CL-04","CL-05")),
 (Role "outcome-owner" "Outcome Owner" "P8762–P8775" "Mantiene claridad, alineación, métrica, evidencia y revisión de un Outcome activo." @("Claridad y alineación","success metric","evidencia y review") @("Decisiones del Outcome según authority pendiente") @("Célula","Liderazgo") @("DECIDE","LEARN") @("ACCOUNTABLE","DECISION OWNER")),
 (Role "bet-owner" "Bet Owner" "P8777–P8783" "Distribuye ownership de valor, técnica y experiencia dentro de una Bet." @("Producto: valor","Desarrollo: técnica","UX: experiencia") @() @("Producto","Desarrollo","UX") @("DECIDE","DELIVER") @("RESPONSIBLE","CONTRIBUTOR")),
 (Role "technical-owner" "Technical Owner" "P8785–P8796" "Capacidad contextual de Dev o SRE, no un cargo nuevo." @("Decisiones técnicas, sostenibilidad, riesgos, dependencias y deuda") @("Solución técnica") @("Desarrollo","SRE","Producto") @("DECIDE","DELIVER") @("DECISION OWNER","RESPONSIBLE")),
 (Role "customer-outcome-owner" "Customer Outcome Owner" "P8798–P8811" "Separa la operación de adopción de la accountability por el Outcome de Producto." @("CS: activación, adopción y journey de cuenta","Producto: Outcome y barreras sistémicas") @() @("Customer Success","Producto") @("ADOPT","LEARN") @("ACCOUNTABLE","RESPONSIBLE")),
 (Role "cell-lead" "Cell Lead / Captain" "P8830–P8847" "Protege foco y flujo sin reemplazar las decisiones de las especialidades." @("Foco, flow, blockers, WIP, cadence y escalation") @() @("Célula","Outcome Owner") @("DECIDE","DELIVER","LEARN") @("FACILITATOR","CONTRIBUTOR") @("CL-04","CL-05","CL-11")),
 (Role "data-analytics" "Data / Analytics (capacidad transversal)" "P9025–P9036" "La fuente no evidencia una función Data formal con ownership organizacional específico." @("Producto define qué medir","Tecnología instrumenta cuando corresponde","CS y SRE aportan contexto") @() @("Producto","Tecnología","CS","SRE") @("ADOPT","LEARN") @("CONTRIBUTOR")),
 (Role "product-operations" "Product Operations (capacidad, no cargo)" "P9038–P9052" "Capacidad distribuida de trazabilidad, métricas, cadencias, tooling, documentación, governance y learning." @("Operación liderada por Head de Producto","automatización reduce carga administrativa") @() @("Head de Producto","capacidades actuales") @("DISCOVER","DECIDE","DELIVER","ADOPT","LEARN") @("FACILITATOR","CONTRIBUTOR"))
)
$decisionData=@(
 @("signal-worth-framing","¿La señal merece framing?","DISCOVER","Producto / fuente de señal","Producto / fuente de señal"),@("needs-discovery","¿Requiere Discovery?","DISCOVER","Producto","UX"),@("define-outcome","¿Cuál es el Outcome?","DECIDE","Producto","célula"),@("evidence-sufficient","¿Falta evidencia?","DISCOVER","Producto + UX","holder de evidencia"),@("experience-valid","¿La experiencia es válida?","DISCOVER","UX","Producto + usuario"),@("technical-feasibility","¿Es factible?","DECIDE","Desarrollo / SRE","Producto"),@("operational-acceptability","¿Es operacionalmente aceptable?","DELIVER","SRE","Desarrollo"),@("prioritize","¿Se prioriza?","DECIDE","Producto","Tecnología + contexto de Liderazgo"),@("start-delivery","¿Comienza Delivery?","DECIDE","Producto + Desarrollo","UX / SRE según riesgo"),@("technical-implementation","¿Cómo se implementa técnicamente?","DELIVER","Desarrollo / SRE","Producto"),@("technical-release","¿Está técnicamente listo para Release?","DELIVER","Desarrollo / SRE","Producto"),@("adoption-action","¿Qué acción de adopción corresponde?","ADOPT","Customer Success","Producto"),@("outcome-achieved","¿Se logró el Outcome?","LEARN","Producto","CS + UX + data"),@("next-learning-decision","¿Escalar, ajustar o detener?","LEARN","Producto","célula"),@("strategic-escalation","¿Debe escalarse la decisión?","DECIDE","Outcome Owner / Liderazgo","participantes según autoridad")
)
$decisions=@();foreach($d in $decisionData){$decisions+=[ordered]@{id=$d[0];decision=$d[1];stage=$d[2];decisionOwner=$d[3];participants=@($d[4]);source=(Ref $meta[17].sourceTitle "T57");validationStatus="pending"}}

$artifactCompleteness=Completeness @("WHAT","WHY","ARTIFACT","DECISION") @("HOW","WHO","WHEN","INPUT","OUTPUT","METRIC","TOOL","EXAMPLE") @()
function Artifact([string]$id,[string]$name,[string]$purpose,[string[]]$taxonomy,[string[]]$stages,[string]$locator,[string[]]$fields,[string]$owner,[string]$decision,[string[]]$lifecycle=@()){return [ordered]@{id=$id;name=$name;purpose=$purpose;taxonomy=$taxonomy;canonicalStages=$stages;owner=$owner;requiredFields=$fields;lifecycle=$lifecycle;lifecycleCompleteness="SOURCE PARTIAL";decisionEnabled=$decision;contentClass="recommendation";completeness=$artifactCompleteness;sourceLocators=@((Ref $meta[20].sourceTitle $locator));clientValidationIds=@("CL-04")}}
$artifacts=@(
 (Artifact "signal" "Signal" "Capturar una observación relevante sin convertirla prematuramente en requerimiento." @("DISCOVERY","EVIDENCE") @("DISCOVER") "P11128–P11155" @("Source","Actor","Signal","Context","Module / Journey","Evidence","Observable impact") "Fuente de señal" "¿La señal merece framing?" @("Nace cuando aparece una observación relevante")),
 (Artifact "opportunity-card" "Opportunity Card" "Convertir señales y patrones en un problema suficientemente claro para decidir atención." @("DISCOVERY","DECISION") @("DISCOVER","DECIDE") "P11172–P11193" @("Problem","Actor / Segment","Context","Evidence","Impact","Outcome Link","Evidence Strength","Unknowns","Decision State") "Producto" "Explore / Prioritize / Wait / Discard" @("Cuando existe un problema que merece atención")),
 (Artifact "evidence-map" "Evidence Map" "Consolidar evidencia distribuida vinculada al mismo problema; no es un reporte separado por defecto." @("EVIDENCE","DISCOVERY") @("DISCOVER") "P11210–P11221" @("Source","Signal / Evidence","Strength","What it indicates") "Producto" "Determinar qué se sabe y qué falta" @("Cuando el usuario o sistema responde")),
 (Artifact "outcome-card" "Outcome Card" "Definir el resultado de valor, población, línea base, criterios, métrica y guardrails." @("STRATEGY","GOVERNANCE") @("DECIDE","LEARN") "P11223–P11245" @("Outcome","Actor / Population","Current State / Baseline","Success Criteria","Outcome Metric","Leading Indicators","Guardrails","Outcome Owner","Review Frequency") "Producto" "Alinear dirección de valor y revisar resultado" @("Cuando existe una dirección de valor")),
 (Artifact "bet-card" "Bet Card" "Hacer explícita una hipótesis de inversión, evidencia esperada, guardrails y trigger de revisión." @("DECISION","DELIVERY") @("DECIDE","DELIVER") "P11276–P11309" @("We believe","For","By","We expect","Evidence","Guardrails","Review Trigger","Owner") "Producto" "Start / Continue / Adjust / Stop / Scale" @("Cuando SEIF decide intervenir")),
 (Artifact "outcome-board" "Outcome Board" "Mostrar portafolio, flujo, WIP, blockers, aging, reviews y decisiones pendientes." @("GOVERNANCE","DELIVERY") @("DECIDE","DELIVER","ADOPT","LEARN") "P11322–P11347" @("Outcome","Opportunity","Bet","Owner","State","WIP","Blockers","Aging","Review Trigger","Pending Decision") "Producto / célula" "Desbloquear, priorizar y revisar inversión" @("Opportunities","Discovery","Prioritized","Delivery","Released","Measuring","Learned")),
 (Artifact "learning-card" "Learning Card" "Comparar expectativa y observación para producir aprendizaje y una decisión posterior." @("LEARNING","EVIDENCE") @("LEARN") "P11359–P11385" @("We believed","Because","Expected","Observed","Learned","Decision") "Producto" "Scale / Continue / Adjust / Explore / Stop" @("Cuando interpretamos el resultado")),
 (Artifact "decision-log" "Decision Log" "Conservar contexto, evidencia, rationale, trade-off, owner y review trigger de decisiones relevantes." @("DECISION","GOVERNANCE") @("DECIDE","LEARN") "P11387–P11423" @("Decision","Date","Context","Evidence","Rationale","Trade-off","Owner","Review Trigger") "Decision owner" "Registrar qué y por qué se decidió" @("Cuando cambia la acción"))
)
$relationships=@();$flow=@(@("Signal","Opportunity","la observación se formula como problema","P11725–P11729"),@("Opportunity","Outcome","el problema se vincula a dirección de valor","P11728–P11732"),@("Outcome","Bet","SEIF decide intervenir","P11731–P11735"),@("Bet","Delivery","se compromete construcción","P11734–P11738"),@("Delivery","Evidence","usuario o sistema responde","P11737–P11741"),@("Evidence","Learning","se interpreta el resultado","P11740–P11744"),@("Learning","Decision","el aprendizaje cambia la acción","P11743–P11747"));foreach($f in $flow){$relationships+=[ordered]@{from=$f[0];to=$f[1];relationship=$f[2];source=(Ref $meta[20].sourceTitle $f[3]);validationStatus="pending"}}
$concepts=@{17=@([ordered]@{id="role-contract";title="Contrato operativo de roles";canonicalLayers=@("ROLES","GOVERNANCE","DECIDE");sourceChapters=@("17");sourceLocators=@((Ref $meta[17].sourceTitle "P8510–P9205"));contentClass="recommendation";completeness=(Completeness @("WHAT","WHY","WHO","DECISION","EXAMPLE") @("HOW","WHEN","INPUT","OUTPUT","ARTIFACT","METRIC") @("TOOL"));gapIds=@("CL-04","CL-05")});20=@([ordered]@{id="minimum-artifacts";title="Sistema de artefactos mínimos";canonicalLayers=@("DISCOVER","DECIDE","DELIVER","ADOPT","LEARN","EVIDENCE");sourceChapters=@("20");sourceLocators=@((Ref $meta[20].sourceTitle "P11128–P11866"));contentClass="recommendation";completeness=(Completeness @("WHAT","WHY","HOW","INPUT","OUTPUT","ARTIFACT","DECISION","EXAMPLE") @("WHO","WHEN","METRIC","TOOL") @());gapIds=@("CL-04","CL-10")})}

$utf8=[Text.UTF8Encoding]::new($false)
foreach($number in 17,20){$m=$meta[$number];$data=[ordered]@{slug=$m.slug;group="Operating Model";title=$m.title;sourceTitle=$m.sourceTitle;eyebrow=$m.eyebrow;summary=$m.summary;takeaway=$m.takeaway;executive=[ordered]@{keyFindings=$m.findings;implication=$m.implication;evidenceConfidence="medium";evidenceStatus="pending";primaryVisual="cards";sources=@((Ref $m.sourceTitle ($chapters[$number].start+"–"+$chapters[$number].end)))};operatingConcepts=$concepts[$number];sections=@($chapters[$number].sections);related=$m.related;source=[ordered]@{title=$m.sourceTitle;locator=($chapters[$number].start+"–"+$chapters[$number].end);note="Locators internos de párrafo OOXML; no se muestran por defecto."}};if($number-eq17){$data.operatingRoles=$roles;$data.decisionRights=$decisions;$data.clientValidations=@((CV "CL-04" "Mapeo entre roles fuente y futuros roles canónicos"),(CV "CL-05" "Accountability organizacional y derechos de decisión"))}else{$data.operatingArtifacts=$artifacts;$data.artifactRelationships=$relationships;$data.clientValidations=@((CV "CL-04" "Ownership de artefactos y mapeo de roles"),(CV "CL-10" "Arquitectura de tooling y relación con business objects"))};$json=$data|ConvertTo-Json -Depth 100;$content="import type { Chapter } from `"@/types/content`";`r`n`r`nexport const chapter = $json satisfies Chapter;`r`n";[IO.File]::WriteAllText((Join-Path $repo("content/chapters/"+$m.file)),$content,$utf8)}
Write-Output "Block B Wave 2 ingestion generated Chapters 17 and 20 from $Source."
