param([string]$Source="source-private/SEIF-master-v0.1.docx")
$ErrorActionPreference="Stop";$repo=Split-Path -Parent $PSScriptRoot;$sourcePath=Join-Path $repo $Source
if(-not(Test-Path -LiteralPath $sourcePath -PathType Leaf)){throw "SOURCE NOT FOUND"}
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($sourcePath)
try{$entry=$zip.GetEntry("word/document.xml");$reader=[IO.StreamReader]::new($entry.Open());try{[xml]$document=$reader.ReadToEnd()}finally{$reader.Dispose()}}finally{$zip.Dispose()}
$ns=[Xml.XmlNamespaceManager]::new($document.NameTable);$ns.AddNamespace("w","http://schemas.openxmlformats.org/wordprocessingml/2006/main");$body=$document.SelectSingleNode("//w:body",$ns)
function Text-Of($node){return (($node.SelectNodes(".//w:t",$ns)|ForEach-Object{$_.InnerText})-join"").Trim()}
function Max-Size($p){$s=@($p.SelectNodes(".//w:rPr/w:sz",$ns)|ForEach-Object{[int]$_.GetAttribute("val",$ns.LookupNamespace("w"))});if(!$s.Count){return 0};return ($s|Measure-Object -Maximum).Maximum}
function Slugify([string]$v){$n=$v.Normalize([Text.NormalizationForm]::FormD);$c=$n.ToCharArray()|Where-Object{[Globalization.CharUnicodeInfo]::GetUnicodeCategory($_)-ne[Globalization.UnicodeCategory]::NonSpacingMark};return ((-join$c).ToLowerInvariant()-replace"[^a-z0-9]+","-").Trim("-")}
function Ref([string]$locator){return [ordered]@{title="14. Delivery & Release Model";locator=$locator}}
function CV([string]$id,[string]$subject){return [ordered]@{id=$id;subject=$subject;status="CLIENT VALIDATION REQUIRED"}}
function Complete([string[]]$complete,[string[]]$partial,[string[]]$missing){$v=[ordered]@{};foreach($k in $complete){$v[$k]="SOURCE COMPLETE"};foreach($k in $partial){$v[$k]="SOURCE PARTIAL"};foreach($k in $missing){$v[$k]="SOURCE MISSING"};return $v}
function Section-Class([string]$title){if($title-match'(?i)Maturity'){return "hypothesis"};if($title-match'(?i)AS-IS|Cambio fundamental|Cambio esperado|Diagnóstico final|entrevistas'){return "mixed"};return "recommendation"}
function Validations-For([string]$title){$r=@();if($title-match'(?i)Producto|UX|SRE|Support|Customer|accountability'){$r+=,(CV "CL-04" "Mapeo organizacional de roles participantes en Delivery")};if($title-match'(?i)Release Decision'){$r+=,(CV "CL-05" "Authority y accountability de decisiones de release")};if($title-match'(?i)Métrica|DORA|Predictability|Dashboard'){$r+=,(CV "CL-07" "Definiciones operacionales, baseline, target y ownership de métricas")};if($title-match'(?i)Adoption|TTV|Release Success|Post-Release'){$r+=,(CV "CL-08" "Definiciones de Activation, Adoption, TTV y evidencia posterior")};if($title-match'(?i)WIP'){$r+=,(CV "CL-09" "Límites numéricos de WIP")};if($title-match'(?i)Tooling|Jira|Automatización|IA|Feature Flags|Workflow'){$r+=,(CV "CL-10" "Arquitectura futura de tooling y automatización")};if($title-match'(?i)Review|Cadence'){$r+=,(CV "CL-11" "Cadencias, participantes y triggers operativos")};if($title-match'(?i)Capacity|deuda técnica'){$r+=,(CV "CL-12" "Política de capacidad y deuda técnica")};if($title-match'(?i)Maturity|madurez'){$r+=,(CV "CL-14" "Valoración del assessment — madurez Delivery pendiente de validación")};return $r}

$chapter=[ordered]@{sections=@();start=$null;end=$null};$current=0;$expected=1;$pi=0;$ti=0;$section=$null;$pending=@();$pendingStart=$null;$pendingEnd=$null
function Flush-List{if($null-ne$script:section-and$script:pending.Count){$script:section.blocks+=[ordered]@{type="list";items=@($script:pending);source=(Ref "P$script:pendingStart–P$script:pendingEnd")}};$script:pending=@();$script:pendingStart=$null;$script:pendingEnd=$null}
foreach($node in $body.ChildNodes){if($node.LocalName-eq"p"){$pi++;$text=Text-Of $node;if($expected-le15-and$text-match("^"+$expected+"\.\s+")-and(Max-Size $node)-ge36){Flush-List;$current=$expected;$expected++;if($current-eq14){$chapter.start="P$pi";$section=$null;continue};if($current-eq15){$chapter.end="P$($pi-1)";break}};if($current-ne14){continue};$chapter.end="P$pi";if(!$text){Flush-List;continue};if($text-match'^14\.\d+\s+'){Flush-List;$title=($text-replace'^14\.\d+\s+','').Trim();$section=[ordered]@{id=(Slugify $title);title=$title;contentClass=(Section-Class $title);blocks=@();evidence=@();sources=@((Ref "P$pi"))};$v=Validations-For $title;if($v.Count){$section.clientValidations=@($v)};$chapter.sections+=$section;continue};if($null-eq$section){continue};$isList=$null-ne$node.SelectSingleNode("./w:pPr/w:numPr",$ns);if($isList){if(!$pending.Count){$pendingStart=$pi};$pendingEnd=$pi;$pending+=$text}else{Flush-List;$section.blocks+=[ordered]@{type="paragraph";text=$text;source=(Ref "P$pi")}}}elseif($node.LocalName-eq"tbl"){$ti++;if($current-ne14){continue};Flush-List;$rows=@();foreach($row in $node.SelectNodes("./w:tr",$ns)){$rows+=,@($row.SelectNodes("./w:tc",$ns)|ForEach-Object{Text-Of $_})};if($rows.Count-and$null-ne$section){$headers=@($rows[0]);$data=if($rows.Count-gt1){@($rows[1..($rows.Count-1)])}else{@()};$kind=if(($headers-join" ")-match'(?i)Nivel|Dimensión'){"comparison"}elseif(($headers-join" ")-match'(?i)Métrica'){"scorecard"}else{"simple"};$section.blocks+=[ordered]@{type="table";table=[ordered]@{id=("source-table-{0:D3}"-f$ti);caption=$section.title;kind=$kind;headers=$headers;rows=$data;source=(Ref "T$ti")}}}}};Flush-List

$semantics=@(
 [ordered]@{term="DONE";definition="Technical Done: la capacidad está correctamente construida; no implica release ni valor.";sourceStatus="SOURCE PARTIAL";source=(Ref "P5665–P5690")},
 [ordered]@{term="READY FOR RELEASE";definition="Estado posterior a validación con readiness técnica, operacional y de medición por comprobar.";sourceStatus="SOURCE COMPLETE";source=(Ref "P5490–P5507; P5706–P5726")},
 [ordered]@{term="RELEASED";definition="La capacidad está disponible en producción; no demuestra adopción ni Outcome.";sourceStatus="SOURCE COMPLETE";source=(Ref "P5679–P5690")},
 [ordered]@{term="IN PRODUCTION";definition="Código desplegado o capacidad liberada en el contexto real; Deployment y Release pueden separarse.";sourceStatus="SOURCE PARTIAL";source=(Ref "P5728–P5745")},
 [ordered]@{term="AVAILABLE";definition="Capacidad habilitada para usuarios después de Release; la fuente no define un estado independiente adicional.";sourceStatus="SOURCE PARTIAL";source=(Ref "P5733–P5737")},
 [ordered]@{term="ADOPTED";definition="Existe uso recurrente relevante.";sourceStatus="SOURCE COMPLETE";source=(Ref "P5679–P5690")},
 [ordered]@{term="VALUE VALIDATED";definition="Existe evidencia de que el comportamiento esperado modificó el Outcome.";sourceStatus="SOURCE COMPLETE";source=(Ref "P5490–P5504; P6246–P6255")}
)
$deliveryCompleteness=Complete @("WHAT","WHY","HOW","WHO","WHEN","INPUT","OUTPUT","ARTIFACT","DECISION","METRIC","EXAMPLE","FLOW","QUALITY","RELEASE CRITERIA","RECOVERY","POST-RELEASE OBSERVATION") @("TOOL") @()
function DC([string]$id,[string]$kind,[string]$title,[string]$what,[string]$why,[string]$locator,[string[]]$activities=@(),[string[]]$outputs=@(),[string[]]$participants=@(),[string]$decision="",[string]$metric=""){$v=[ordered]@{id=$id;kind=$kind;title=$title;what=$what;why=$why;activities=$activities;outputs=$outputs;participants=$participants;decision=$decision;metric=$metric;sourceLocators=@((Ref $locator));contentClass="recommendation";completeness=$deliveryCompleteness};return $v}
$concepts=@(
 (DC "commitment" "COMMITMENT" "Bet priorizada y capacidad comprometida" "Delivery comienza con una Bet priorizada y suficientemente validada." "Evita ingresar una feature aprobada sin Outcome, evidencia o scope acotado." "P5316–P5326; P5390–P5414" @("comprobar Delivery Readiness") @("Delivery Bet") @("Producto","Desarrollo") "Comprometer capacidad"),
 (DC "delivery-object" "DELIVERY OBJECT" "Delivery Bet" "Inversión acotada que puede modificar un Outcome." "Conecta decisión y trabajo sin documentación extensa." "P5390–P5397; T38" @("definir Problem, Outcome, User, Evidence, Hypothesis, Success Signal, Scope y Risks") @("Bet lista")),
 (DC "decomposition" "WORK DECOMPOSITION" "Outcome → Bet → Valuable Slices" "Descompone una inversión en incrementos que producen evidencia." "Reduce el tiempo entre empezar y aprender." "P5429–P5487" @("vertical slicing") @("Valuable Slices")),
 (DC "valuable-slice" "VALUABLE SLICE" "Smallest Valuable Slice" "Incremento pequeño pero capaz de producir comportamiento observable, capacidad utilizable, evidencia y aprendizaje." "Small no equivale a Valuable." "P5429–P5487" @("reducir tiempo, riesgo, complejidad y feedback tardío") @("working increment")),
 (DC "wip" "WORK IN PROGRESS" "Finish before starting more" "Limita trabajo simultáneo mediante Pull y WIP visible sin fijar número fuente." "Reduce inventario, espera y pérdida de foco." "P5387–P5388; P5511–P5536" @("calibrar con throughput, bloqueos, dependencias y Cycle Time") @("WIP visible") @() "Tomar nuevo trabajo cuando exista capacidad" "WIP"),
 (DC "flow" "FLOW" "Flujo real del trabajo" "READY → IN DELIVERY → VALIDATING → READY FOR RELEASE → RELEASED → OBSERVING → VALUE VALIDATED." "Representa estados del trabajo, no departamentos." "P5490–P5508" @("pull","build","test","observe") @("incremento liberable") @("Producto","UX/UI","Desarrollo","SRE") "Avanzar según evidencia" "Cycle Time / Throughput"),
 (DC "dependency" "DEPENDENCY" "Dependencias visibles" "La espera por dependencias se separa del tiempo activo." "Permite diagnosticar fricción sistémica." "P5538–P5565" @("clasificar dependencia") @("causa visible") @() "Resolver o escalar según riesgo" "Blocked Time"),
 (DC "blocker" "BLOCKER" "BLOCKED como condición" "Bloqueo Product, UX, Technical, SRE/Infrastructure, External u Organizational." "Evita convertir BLOCKED en destino permanente." "P5505–P5507; P5538–P5565" @("hacer visible","medir espera") @("bloqueo resuelto") @() "Desbloquear antes de iniciar más" "Blocked Time"),
 (DC "quality" "QUALITY" "Quality built-in" "Calidad funcional, de experiencia, técnica y operacional integrada en Delivery." "Pasar pruebas funcionales no garantiza production readiness." "P5376–P5378; P5639–P5677" @("fast feedback","integration validation","critical journey validation") @("Technical Done") @("UX/UI","Desarrollo","SRE") "Aceptar Technical Done según riesgo" "defectos / rework"),
 (DC "validation" "VALIDATION" "Continuous validation" "Producto, UX y Tecnología revisan incrementos útiles antes de completar inversiones significativas." "Reduce handoff y feedback tardío." "P5571–P5601; P5818–P5851" @("review working increment") @("Evidence","Decision") @("Producto","UX/UI","Desarrollo","Customer Success","SRE") "Continuar o ajustar"),
 (DC "release-readiness" "RELEASE READINESS" "Readiness técnica, operacional y de medición" "Comprueba funcionamiento, operación/recuperación y observabilidad posterior." "Release seguro necesita más que código terminado." "P5706–P5726; P6060–P6073" @("Technical Readiness","Operational Readiness","Measurement Readiness") @("release decision") @("Producto","Desarrollo","SRE") "Release / hold"),
 (DC "release" "RELEASE" "Release como capacidad del sistema" "Liberación repetible de cambios pequeños, recuperables y observables." "Release no es Outcome." "P5693–P5704; P5763–P5773" @("release","progressive exposure") @("capacidad disponible") @("Producto","Desarrollo","SRE") "Release; exposición progresiva o rollback lógico cuando aplique" "Deployment Frequency"),
 (DC "production" "PRODUCTION" "Deploy ≠ Release" "Deployment pone código disponible técnicamente; Release habilita capacidad a usuarios." "Permite exposición progresiva y reducción de riesgo." "P5728–P5761" @("deploy","habilitar","observar","expandir") @("general availability") @("Desarrollo","SRE") "Expand / rollback lógico"),
 (DC "technical-feedback" "TECHNICAL FEEDBACK" "Change Failure e Incident Learning" "Incidentes, rollback y corrección urgente alimentan calidad, testing, arquitectura y observabilidad." "No son fracaso individual." "P5854–P5878; P6091–P6111" @("restore","understand","root cause","corrective action") @("system learning") @("Desarrollo","SRE") "Corrective action" "Change Failure Rate / MTTR"),
 (DC "post-release" "POST-RELEASE OBSERVATION" "Observe antes de concluir valor" "Compara Expected, Actual, Friction, Technical Health y Adoption." "Conecta Release con Adoption y Learning." "P5802–P5816; P5908–P5957; P6075–P6088" @("activation observation","feedback","friction detection") @("continue","adjust","scale","stop") @("Producto","Customer Success","Soporte","Desarrollo","SRE") "Continue / adjust / scale / stop" "Release → First Evidence")
)
$commitConnections=@(
 [ordered]@{element="Decision";status="SUPPORTED";rationale="El flujo fuente conecta Decision con Bet y Delivery.";source=(Ref "P5299–P5301; P6306–P6310")},
 [ordered]@{element="Commitment";status="SUPPORTED";rationale="Delivery Readiness comprueba claridad suficiente para comprometer capacidad.";source=(Ref "P5399–P5414")},
 [ordered]@{element="Bet";status="SUPPORTED";rationale="La entrada explícita es una Delivery Bet priorizada y validada.";source=(Ref "P5319; P5390–P5397")},
 [ordered]@{element="Capacity";status="PARTIAL";rationale="La capacidad condiciona Pull, WIP e inicio; no hay porcentajes ni límite rígido.";source=(Ref "P5511–P5536; P5975–P5986")},
 [ordered]@{element="Delivery Object";status="SUPPORTED";rationale="Delivery Bet y Valuable Slice son objetos lógicos fuente.";source=(Ref "P5390–P5397; P5429–P5467")},
 [ordered]@{element="Epic / Slice / Story / Task";status="PARTIAL";rationale="La jerarquía aparece como recomendación conceptual de tooling, no como arquitectura aprobada.";source=(Ref "P6163–P6175")},
 [ordered]@{element="Release";status="SUPPORTED";rationale="El modelo consolidado traza Bet → Delivery → Release.";source=(Ref "P6268–P6303")}
)
$objects=@(
 [ordered]@{sourceTerm="Delivery Bet";purpose="Entrada acotada a Delivery";parentChildRelationship="Outcome → Bet";decisionRelationship="Resultado de priorización y compromiso";releaseRelationship="Se descompone antes de Release";source=(Ref "P5390–P5397; T38");validationStatus="pending"},
 [ordered]@{sourceTerm="Smallest Valuable Slice";purpose="Menor incremento capaz de producir comportamiento observable, evidencia y aprendizaje";parentChildRelationship="Bet → Valuable Slice";lifecycle=@("IN DELIVERY","VALIDATING","READY FOR RELEASE","RELEASED","OBSERVING");decisionRelationship="Permite validar/ajustar la Bet";releaseRelationship="Puede convertirse en incremento liberable";source=(Ref "P5429–P5507");validationStatus="pending"},
 [ordered]@{sourceTerm="Epic / Valuable Slice";purpose="Nivel conceptual de descomposición";parentChildRelationship="Bet / Initiative → Epic / Valuable Slice";decisionRelationship="Trazabilidad hacia Bet/Outcome";releaseRelationship="No definido como unidad obligatoria de release";source=(Ref "P6163–P6175");validationStatus="pending"},
 [ordered]@{sourceTerm="Story / Task / Bug";purpose="Trabajo de implementación en jerarquía conceptual";parentChildRelationship="Epic / Valuable Slice → Story / Task / Bug";decisionRelationship="No es unidad de inversión";releaseRelationship="SOURCE MISSING";source=(Ref "P6163–P6175");validationStatus="pending"},
 [ordered]@{sourceTerm="Change";purpose="Cambio técnico medido desde commit hasta producción";decisionRelationship="Puede generar release, hold o corrective action";releaseRelationship="Deployment / Release";source=(Ref "P5854–P5876; P5728–P5745");validationStatus="pending"},
 [ordered]@{sourceTerm="Release";purpose="Capacidad habilitada para usuarios";lifecycle=@("progressive exposure","general availability","observe");decisionRelationship="Release Decision";releaseRelationship="No equivale a Adoption ni Outcome";source=(Ref "P5679–P5704; P5747–P5773");validationStatus="pending"},
 [ordered]@{sourceTerm="Technical Debt";purpose="Trabajo embedded, dedicated o preventive";decisionRelationship="Priorizado por impacto, riesgo, recurrencia, costo y oportunidad";releaseRelationship="Puede integrarse en cambios o iniciativa explícita";source=(Ref "P5959–P5973");validationStatus="pending"}
)
$slice=[ordered]@{sourceStatus="SOURCE COMPLETE";optimizes=@("VALUE","LEARNING","RISK","FLOW");definition="Slice pequeña para reducir tiempo, riesgo, complejidad y feedback tardío, y completa para producir comportamiento observable, capacidad utilizable, evidencia y aprendizaje.";risks=@([ordered]@{risk="Feature decomposition without customer value";status="NOT PRESENT";rationale="Small no equivale a Valuable."},[ordered]@{risk="Technical slicing only";status="NOT PRESENT";rationale="La fuente favorece vertical slicing y experiencia observable."},[ordered]@{risk="Big-batch delivery";status="SOURCE RISK";rationale="El AS-IS y los principios TO-BE señalan lotes grandes como riesgo."});source=(Ref "P5429–P5487")}
$releaseDecisions=@(
 [ordered]@{decision="Release";trigger="Cambio relevante alcanza Release Readiness";inputs=@("Technical Readiness","Operational Readiness","Measurement Readiness");participants=@("Producto","Desarrollo","SRE cuando corresponda");criteria=@("representa la Bet","calidad técnica suficiente","riesgo operacional aceptable");outputs=@("Release decision");evidence=@("quality","operability","measurement readiness");source=(Ref "P5706–P5726; P5763–P5773");validationStatus="pending"},
 [ordered]@{decision="Expand / Observe / Rollback lógico";trigger="Exposición progresiva cuando el riesgo lo justifique";inputs=@("technical signals","product signals");participants=@("Producto","Desarrollo","SRE");criteria=@("comportamiento observado","riesgo");outputs=@("Expand","Observe","Rollback lógico");evidence=@("observability","customer behavior");source=(Ref "P5728–P5761");validationStatus="pending"},
 [ordered]@{decision="Continue / Adjust / Scale / Stop";trigger="Evidencia post-release suficiente";inputs=@("Expected","Actual","Friction","Technical Health","Adoption");participants=@("Producto","Customer Success","Desarrollo","SRE cuando corresponda");criteria=@("evidencia técnica y de producto");outputs=@("Continue","Adjust","Scale","Stop");evidence=@("activation","friction","technical health","Outcome evidence");source=(Ref "P6075–P6088");validationStatus="pending"}
)
function Metric([string]$name,[string]$class,[string]$definition,[string]$locator,[string]$formula=""){return [ordered]@{name=$name;metricClass=$class;definition=$definition;formula=$formula;decisionEnabled="Diagnosticar y ajustar el sistema, no evaluar individuos";baseline="SOURCE MISSING";target="SOURCE MISSING";source=(Ref $locator);validationStatus="pending"}}
$metrics=@(
 (Metric "Deployment Frequency" "DORA" "Frecuencia con que se ponen cambios en producción." "P5866–P5878"),(Metric "Lead Time for Changes" "DORA" "Tiempo desde commit hasta producción." "P5866–P5878"),(Metric "Change Failure Rate" "DORA" "Proporción de cambios que genera degradación o requiere intervención." "P5866–P5878"),(Metric "Time to Restore Service (MTTR)" "DORA" "Tiempo para recuperar el servicio." "P5866–P5878"),
 (Metric "Cycle Time" "FLOW" "Tiempo desde inicio de trabajo hasta finalización." "P5880–P5895"),(Metric "Throughput" "FLOW" "Elementos terminados por periodo." "P5880–P5895"),(Metric "WIP" "FLOW" "Trabajo simultáneamente activo." "P5880–P5895"),(Metric "Blocked Time" "FLOW" "Tiempo detenido por dependencia o decisión." "P5555–P5565; P5880–P5895"),(Metric "Flow Efficiency" "FLOW" "Relación entre tiempo activo y tiempo total." "P5880–P5895" "Touch Time / total elapsed time"),(Metric "Aging Work in Progress" "FLOW" "Antigüedad de elementos abiertos actuales." "P5880–P5895"),
 (Metric "Post-release defects" "QUALITY" "Defectos observados después de release." "P5897–P5906"),(Metric "Rework" "QUALITY" "Trabajo reconstruido o corregido." "P5897–P5906"),(Metric "Change-related incidents" "RELIABILITY" "Incidentes asociados a cambios." "P5897–P5906"),(Metric "Quality escapes" "QUALITY" "Fallas que escaparon los controles previos." "P5897–P5906"),(Metric "Rollback" "RELEASE" "Releases que requieren reversión." "P5897–P5906"),(Metric "Critical journey errors" "QUALITY" "Errores sobre journeys críticos." "P5897–P5906"),
 (Metric "Release → Activation Time" "VALUE" "Tiempo hasta que un usuario elegible alcanza activación." "P5908–P5921"),(Metric "Release → First Evidence" "VALUE" "Tiempo hasta obtener evidencia útil." "P5908–P5921"),(Metric "Adoption" "VALUE" "Uso relevante de la capacidad." "P5908–P5921"),(Metric "Support after Release" "VALUE" "Fricción generada después de release." "P5908–P5921"),(Metric "Outcome Achievement" "VALUE" "Cambio observado en el resultado esperado." "P5908–P5921"),(Metric "Decision → Production" "FLOW" "Velocidad de Delivery desde decisión hasta producción." "P5923–P5938"),(Metric "Opportunity → Outcome Evidence" "VALUE" "Tiempo end-to-end hasta evidencia del Outcome." "P5923–P5938")
)
$cadences=@(
 [ordered]@{name="Continuous Delivery flow";cadenceType="OPERATING CADENCE";purpose="Pull, build, test, validate y observe trabajo en flujo.";frequency="continuous";source=(Ref "P5490–P5536");validationStatus="pending"},
 [ordered]@{name="Early Customer Review";cadenceType="EVENT-DRIVEN ACTIVITY";purpose="Validar incrementos integrados útiles antes de completar la inversión.";source=(Ref "P5818–P5829");validationStatus="pending"},
 [ordered]@{name="Unified Module Review";cadenceType="MEETING CADENCE";purpose="Revisar Outcome, Journey, increment, Moment of Truth, Evidence y Decision.";source=(Ref "P5831–P5851");validationStatus="pending"},
 [ordered]@{name="Flow Review";cadenceType="MEETING CADENCE";purpose="Observar WIP, Aging, bloqueos, dependencias, releases, riesgos y decisiones.";frequency="weekly · 30–45 minutes proposed";source=(Ref "P6029–P6058");validationStatus="pending"},
 [ordered]@{name="Release Review";cadenceType="DECISION CADENCE";purpose="Verificar Value, Quality, Operational Risk, Measurement y Adoption según riesgo.";frequency="event-driven; no meeting required for every release";source=(Ref "P6060–P6073");validationStatus="pending"},
 [ordered]@{name="Post-Release Observation";cadenceType="EVENT-DRIVEN ACTIVITY";purpose="Comparar Expected, Actual, Friction, Technical Health y Adoption.";source=(Ref "P6075–P6088");validationStatus="pending"}
)
$adoptConnections=@(
 [ordered]@{element="Instrumentation";status="SUPPORTED";rationale="Measurement Readiness exige evento, métrica, criterio y responsable cuando corresponda.";source=(Ref "P5716–P5726")},
 [ordered]@{element="Activation measurement";status="SUPPORTED";rationale="Release → Activation Time y el handoff observan activación.";source=(Ref "P5802–P5816; P5908–P5921")},
 [ordered]@{element="Customer communication";status="SUPPORTED";rationale="Release Communication define contexto mínimo para CS y Soporte.";source=(Ref "P5775–P5800")},
 [ordered]@{element="Adoption observation";status="SUPPORTED";rationale="Released, Activated, Adopted y Outcome Validated se distinguen.";source=(Ref "P5679–P5690; P6075–P6088")},
 [ordered]@{element="TTV";status="PARTIAL";rationale="Aparece en Flow Metrics Model, pero su definición operacional pertenece al capítulo futuro de Adoption.";source=(Ref "P5941–P5957")},
 [ordered]@{element="Feedback";status="SUPPORTED";rationale="CS/Product feedback y Early Customer Reviews alimentan ajuste.";source=(Ref "P5802–P5851")},
 [ordered]@{element="Support signals";status="SUPPORTED";rationale="Release Communication define Support signal y Support Readiness.";source=(Ref "P5775–P5800")},
 [ordered]@{element="Learning trigger";status="SUPPORTED";rationale="Post-release evidence habilita Continue, Adjust, Scale o Stop.";source=(Ref "P6075–P6088")}
)
$tooling=@(
 [ordered]@{tool="Jira";classification="RECOMMENDATION";relationship="Representar flujo real, WIP, bloqueos y trazabilidad Bet/Outcome; no es configuración aprobada.";source=(Ref "P6150–P6190");validationStatus="pending"},
 [ordered]@{tool="CI/CD";classification="RECOMMENDATION";relationship="Build, test y deployment repetibles.";source=(Ref "P6113–P6133");validationStatus="pending"},
 [ordered]@{tool="Testing automation";classification="RECOMMENDATION";relationship="Automatizar progresivamente donde exista retorno y riesgo relevante.";source=(Ref "P5651–P5663; P6113–P6133");validationStatus="pending"},
 [ordered]@{tool="Observability / monitoring";classification="RECOMMENDATION";relationship="Technical y Product Observability para operación y validación.";source=(Ref "P6011–P6027; P6113–P6133");validationStatus="pending"},
 [ordered]@{tool="Feature flags / progressive delivery";classification="H1 / TO VALIDATE";relationship="Separar Deployment de Release cuando riesgo e incertidumbre lo justifiquen.";source=(Ref "P5728–P5761");validationStatus="pending"},
 [ordered]@{tool="Delivery dashboards";classification="RECOMMENDATION";relationship="Flow, Reliability, Delivery y Value Connection; no medir personas.";source=(Ref "P6192–P6227");validationStatus="pending"},
 [ordered]@{tool="AI-assisted engineering";classification="H1 / TO VALIDATE";relationship="Acelera tareas; engineering controls quality.";source=(Ref "P6135–P6148");validationStatus="pending"}
)
$anti=@(
 [ordered]@{antiPattern="Release = Done";status="NOT PRESENT";rationale="Technical Done, Released, Activated, Adopted y Outcome Validated se distinguen.";source=(Ref "P5679–P5690")},[ordered]@{antiPattern="Release = Value";status="NOT PRESENT";rationale="Release is not Outcome es principio explícito.";source=(Ref "P5381–P5386; P6246–P6255")},[ordered]@{antiPattern="Large batch delivery";status="SOURCE RISK";rationale="El TO-BE responde a Large Initiative/Large Epic y favorece lotes pequeños.";source=(Ref "P5374–P5375; P5429–P5471")},[ordered]@{antiPattern="Too much WIP";status="SOURCE RISK";rationale="WIP excesivo incrementa espera y pérdida de foco; no existe baseline numérico.";source=(Ref "P5387–P5388; P5525–P5536")},[ordered]@{antiPattern="Feature factory";status="SOURCE RISK";rationale="La entrada no debe ser Feature aprobada y el éxito no es entregar tickets.";source=(Ref "P5390–P5397; P6366–P6370")},[ordered]@{antiPattern="Status-driven delivery";status="SOURCE RISK";rationale="Delivery Review cambia actividad por flujo y no recorre ticket por ticket.";source=(Ref "P6029–P6058")},[ordered]@{antiPattern="Story points as productivity";status="OPERATING MODEL RISK";rationale="La fuente prohíbe métricas sistémicas como evaluación individual, pero no trata story points de forma explícita.";source=(Ref "P6213–P6227")},[ordered]@{antiPattern="DORA as individual performance";status="NOT PRESENT";rationale="DORA y flow metrics diagnostican el sistema, no individuos.";source=(Ref "P5866–P5878; P6213–P6227")},[ordered]@{antiPattern="Technical handoff to SRE";status="NOT PRESENT";rationale="SRE participa temprano y proporcionalmente al riesgo.";source=(Ref "P5603–P5620")},[ordered]@{antiPattern="Quality as final-phase testing";status="NOT PRESENT";rationale="Quality built-in y cuatro dimensiones de calidad.";source=(Ref "P5376–P5378; P5639–P5663")},[ordered]@{antiPattern="Release without instrumentation";status="SOURCE RISK";rationale="Measurement Readiness es tratamiento TO-BE y observabilidad actual se describe fragmentada.";source=(Ref "P5706–P5726; T42")},[ordered]@{antiPattern="Release without adoption observation";status="SOURCE RISK";rationale="El handoff tradicional se rechaza y se propone observación posterior.";source=(Ref "P5802–P5816")},[ordered]@{antiPattern="Long-lived branches / integration delay";status="OPERATING MODEL RISK";rationale="La fuente recomienda código integrado y CI/CD, pero no evalúa ramas de larga duración.";source=(Ref "P5665–P5675; P6113–P6129")},[ordered]@{antiPattern="Dependency queues";status="SOURCE RISK";rationale="Waiting, handoffs y dependencias se identifican como desperdicio y causa de bloqueo.";source=(Ref "P5538–P5568; T39")},[ordered]@{antiPattern="Rework hidden as normal flow";status="SOURCE RISK";rationale="Rework es waste y métrica de calidad explícita.";source=(Ref "T39; P5897–P5906")}
)
$operatingConcepts=@([ordered]@{id="delivery-release-system";title="DELIVER — Delivery & Release Model";canonicalLayers=@("DELIVER","ADOPT","LEARN","ROLES","METRICS","EVIDENCE","TOOLING / JIRA");sourceChapters=@("14");sourceLocators=@((Ref "P5297–P6370"));contentClass="recommendation";completeness=(Complete @("WHAT","WHY","HOW","WHO","WHEN","INPUT","OUTPUT","ARTIFACT","DECISION","METRIC","EXAMPLE") @("TOOL") @());gapIds=@("CL-04","CL-05","CL-07","CL-08","CL-09","CL-10","CL-11","CL-12")})
$metadata=[ordered]@{slug="delivery";group="Operating Model";title="DELIVER: Delivery & Release Model";sourceTitle="14. Delivery & Release Model";eyebrow="14 · Deliver";summary="Convierte una Bet comprometida en slices valiosas, confiables y observables, separando construcción, release, adopción y evidencia de Outcome.";takeaway="Technical Done, Released, Adopted y Value Validated son estados distintos: Release expone una hipótesis al contexto real, no demuestra valor.";executive=[ordered]@{keyFindings=@("Delivery entra con una Bet priorizada y Delivery Readiness suficiente, no con una feature simplemente aprobada.","Smallest Valuable Slice reduce tiempo, riesgo y feedback tardío sin confundir pequeño con valioso.","DORA y flow metrics diagnostican capacidad del sistema; no miden productividad individual ni valor de producto.","Release exige readiness técnica, operacional y de medición, y abre observación de Adoption y Outcome.");implication="El TO-BE propone disciplina de flujo y confiabilidad. Límites WIP, authority, métricas, cadencias, tooling y definiciones de Adoption permanecen pendientes de validación.";evidenceConfidence="medium";evidenceStatus="pending";primaryVisual="flow";sources=@((Ref ($chapter.start+"–"+$chapter.end)))};clientValidations=@((CV "CL-05" "Decision rights de release"),(CV "CL-08" "Activation, Adoption y TTV"),(CV "CL-09" "WIP numérico"),(CV "CL-10" "Tooling"));operatingConcepts=$operatingConcepts;deliverySemantics=$semantics;deliveryConcepts=$concepts;commitmentDeliveryConnections=$commitConnections;deliveryObjects=$objects;valuableSliceAssessment=$slice;releaseDecisions=$releaseDecisions;artifactUses=@([ordered]@{artifactId="bet-card";artifactName="Bet Card / Delivery Bet";relationship="SOURCE TERMINOLOGY CONFLICT";usage="Chapter 14 nombra Delivery Bet y define contenido mínimo, pero no usa literalmente Bet Card.";source=(Ref "P5390–P5397; T38");validationStatus="pending"});deliveryCadences=$cadences;deliveryMetrics=$metrics;releaseAdoptConnections=$adoptConnections;deliveryTooling=$tooling;antiPatternAssessments=$anti;sections=@($chapter.sections);related=@("value-stream","operating-model","prioritization","roles","artifacts","adoption-growth","feedback-loop","jira");source=[ordered]@{title="14. Delivery & Release Model";locator=($chapter.start+"–"+$chapter.end);note="Locators internos de párrafo OOXML; no se muestran por defecto."}}
$json=$metadata|ConvertTo-Json -Depth 100;$content="import type { Chapter } from `"@/types/content`";`r`n`r`nexport const chapter = $json satisfies Chapter;`r`n";[IO.File]::WriteAllText((Join-Path $repo 'content/chapters/14-delivery.ts'),$content,[Text.UTF8Encoding]::new($false))
Write-Output "Block B Wave 5 ingestion generated Chapter 14 from $Source."
